import pw from '/Users/macbookm3/Desktop/permigo-v7/permigo-game/node_modules/playwright/index.js';
const { chromium } = pw;
const DIR = '/private/tmp/claude-501/-Users-macbookm3-Desktop-permigo-v7/5e14c278-0238-4c01-8093-789b5077043d/scratchpad';
const browser = await chromium.launch({ args: ['--allow-file-access-from-files'] });
const page = await browser.newPage({ viewport: { width: 1300, height: 2600 }, deviceScaleFactor: 1 });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
await page.goto(`file://${DIR}/plates.html`, { waitUntil: 'networkidle' });
await page.waitForTimeout(600);
await page.locator('#plate-gauche').screenshot({ path: `${DIR}/out-3-gauche-rabattement.png` });
await page.locator('#plate-droite').screenshot({ path: `${DIR}/out-2-droite-toutdroit.png` });
if (errs.length) console.log('ERRORS', JSON.stringify(errs));
await browser.close();
console.log('done');
