-- Rééquilibre la longueur des réponses du lot 1 déjà déployé.
-- Les correct_index restent inchangés et chaque option garde le même sens en FR, EN et AR.

-- C1d
update public.questions_competence set options = $pg$["Les rétroviseurs puis l'angle mort du côté où tu comptes réellement partir", "Seulement le compteur pour confirmer que la voiture reste à faible vitesse", "Uniquement la voiture devant pour copier son départ au même moment"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000001';
update public.question_translations set options = $pg$["The mirrors, then the blind spot on the side you are actually moving into", "Only the speedometer to confirm that the car remains at a low speed", "Only the car ahead so you can copy exactly when and where it moves off"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000001' and lang = 'en';
update public.question_translations set options = $pg$["المرايا ثم الزاوية الميتة في الجهة التي ستنطلق إليها فعليًا", "عداد السرعة فقط للتأكد من بقاء السيارة على سرعة منخفضة", "السيارة أمامك فقط لتقلد لحظة انطلاقها إلى الطريق"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000001' and lang = 'ar';

update public.questions_competence set options = $pg$["Dès que le moteur tourne, même sans avoir choisi la direction", "Quand la direction est choisie et que la voie est libre", "Après avoir accéléré fort pour forcer l'insertion dans la voie"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000002';
update public.question_translations set options = $pg$["As soon as the engine is running, even before choosing a direction", "When the direction is selected and the road is clear", "After accelerating hard to force your way into the lane"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000002' and lang = 'en';
update public.question_translations set options = $pg$["بمجرد أن يعمل المحرك حتى دون اختيار الاتجاه", "عندما تختار الاتجاه ويصبح الطريق خاليًا", "بعد الضغط بقوة على الوقود لفرض دخولك إلى المسار"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000002' and lang = 'ar';

update public.questions_competence set options = $pg$["Appuyer beaucoup plus sur l'accélérateur pour empêcher la voiture de reculer", "La retenir seulement avec l'accélérateur jusqu'à trouver le bon régime", "Reprendre le frein ou le frein à main puis préparer le départ"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000003';
update public.question_translations set options = $pg$["Press the accelerator much harder to prevent the car from rolling back", "Hold it only with the accelerator until you find the right engine speed", "Apply the brake or handbrake again, then prepare to move off"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000003' and lang = 'en';
update public.question_translations set options = $pg$["تضغط دواسة الوقود بقوة أكبر لمنع السيارة من الرجوع", "تثبتها بدواسة الوقود فقط حتى تجد سرعة المحرك المناسبة", "تستعمل الفرامل أو فرامل اليد من جديد ثم تجهز الانطلاق بأمان"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000003' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu freines progressivement puis tu allèges la pression sans la lâcher", "Tu gardes la même force sur le frein jusqu'au blocage complet des roues", "Tu relâches le frein dans le dernier mètre pour laisser rouler la voiture"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000004';
update public.question_translations set options = $pg$["Brake progressively, then ease the pressure without letting go", "Keep the same pressure on the brake until the wheels lock completely", "Release the brake over the last metre to let the car roll"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000004' and lang = 'en';
update public.question_translations set options = $pg$["تفرمل تدريجيًا ثم تخفف الضغط دون أن ترفع قدمك عن الدواسة", "تبقي الضغط نفسه على الفرامل حتى تنغلق العجلات بالكامل", "تحرر الفرامل في المتر الأخير لتترك السيارة تتحرك"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000004' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu gardes un peu d'accélérateur pour empêcher la voiture de repartir seule", "Tu serres le frein à main et places la boîte dans une position sûre", "Tu lâches toutes les commandes en supposant que la voiture restera immobile"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000005';
update public.question_translations set options = $pg$["Keep a little accelerator on to prevent the car from moving by itself", "Apply the handbrake and put the gearbox in a safe position", "Release every control and assume that the car will remain still"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000005' and lang = 'en';
update public.question_translations set options = $pg$["تبقي قليلًا من الضغط على الوقود لمنع السيارة من التحرك وحدها", "تشد فرامل اليد بالكامل وتضع ناقل الحركة في وضع آمن قبل المغادرة", "تترك كل أدوات التحكم وتفترض أن السيارة ستبقى ثابتة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000005' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu accélères pour reprendre le contrôle et ramener la voiture vers l'avant", "Tu braques rapidement pour orienter la voiture loin de la pente", "Tu maintiens le frein et immobilises la voiture avant de vérifier la boîte"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000006';
update public.question_translations set options = $pg$["Accelerate to regain control and move the car forwards again", "Turn the wheel quickly to point the car away from the slope", "Keep the brake on and stop the car before checking the gearbox"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000006' and lang = 'en';
update public.question_translations set options = $pg$["تسرع لاستعادة التحكم وإعادة السيارة إلى الأمام", "تدير المقود بسرعة لتوجيه السيارة بعيدًا عن المنحدر", "تبقي الفرامل مضغوطة وتوقف السيارة قبل فحص ناقل الحركة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000006' and lang = 'ar';

-- C1e
update public.questions_competence set options = $pg$["Tu allèges doucement le frein sur les derniers mètres", "Tu relâches la pédale d'un coup pour laisser la voiture finir seule", "Tu freines beaucoup plus tard et plus fort pour raccourcir l'arrêt"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000011';
update public.question_translations set options = $pg$["Ease the brake gently and progressively over the final metres before stopping", "Release the pedal suddenly and let the car finish stopping by itself", "Brake much later and harder to shorten the stopping distance"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000011' and lang = 'en';
update public.question_translations set options = $pg$["تخفف الفرامل بلطف وتدرج في الأمتار الأخيرة قبل التوقف", "ترفع قدمك فجأة عن الدواسة وتترك السيارة تتوقف وحدها", "تفرمل متأخرًا أكثر وبقوة أكبر لتقصير مسافة التوقف"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000011' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu alternes rapidement accélérateur et frein pour corriger chaque variation", "Tu regardes loin et fais de petits mouvements avec le pied droit", "Tu bloques la cheville et appuies plus fort pour stabiliser ton allure"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000012';
update public.question_translations set options = $pg$["Alternate rapidly between accelerator and brake to correct every change", "Look far ahead and make small movements with your right foot", "Lock your ankle and press harder to keep your speed stable"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000012' and lang = 'en';
update public.question_translations set options = $pg$["تنتقل بسرعة بين الوقود والفرامل لتصحيح كل تغير", "تنظر بعيدًا وتحرك قدمك اليمنى حركات صغيرة", "تثبت كاحلك وتضغط بقوة أكبر للحفاظ على سرعة ثابتة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000012' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu passes au point mort pour laisser la voiture descendre sans retenue", "Tu attends le bas de la pente avant de commencer à ralentir", "Tu gardes la boîte engagée et freines progressivement"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000013';
update public.question_translations set options = $pg$["Shift to neutral and let the car travel downhill without restraint", "Wait until the bottom of the hill before you start slowing down", "Keep the gearbox engaged and brake progressively throughout the descent"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000013' and lang = 'en';
update public.question_translations set options = $pg$["تضع ناقل الحركة في الوضع المحايد لتترك السيارة تنزل بلا مقاومة", "تنتظر حتى نهاية النزول قبل أن تبدأ في التباطؤ هناك", "تبقي ناقل الحركة موصولًا وتفرمل تدريجيًا طوال النزول"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000013' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu appuies franchement et tu maintiens le frein jusqu'à l'arrêt", "Tu commences par une pression très légère puis tu attends une réaction", "Tu pompes rapidement sur la pédale pour multiplier les freinages"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000014';
update public.question_translations set options = $pg$["Press firmly and keep the brake applied until the car stops", "Start with very light pressure and then wait for a reaction", "Pump the pedal quickly to create a series of braking actions"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000014' and lang = 'en';
update public.question_translations set options = $pg$["تضغط بقوة وتبقي الفرامل مضغوطة حتى تتوقف السيارة", "تبدأ بضغط خفيف جدًا ثم تنتظر ظهور أي استجابة", "تضغط الدواسة وترفعها بسرعة لتكرر الفرملة عدة مرات"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000014' and lang = 'ar';

update public.questions_competence set options = $pg$["Il garde les deux pédales enfoncées pour accélérer et freiner ensemble", "Il quitte complètement l'accélérateur puis se déplace sur le frein", "Il reste entre les deux pédales afin de pouvoir toucher les deux"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000015';
update public.question_translations set options = $pg$["It keeps both pedals pressed to accelerate and brake at the same time", "It comes fully off the accelerator, then moves to the brake", "It stays between both pedals so it can reach both of them"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000015' and lang = 'en';
update public.question_translations set options = $pg$["تبقي الدواستين مضغوطتين للتسارع والفرملة في الوقت نفسه", "ترتفع تمامًا عن دواسة الوقود ثم تنتقل إلى الفرامل", "تبقى بين الدواستين حتى تستطيع لمس كلتيهما"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000015' and lang = 'ar';

update public.questions_competence set options = $pg$["Oui, les pédales réagissent toujours pareil même quand la route devient glissante", "Oui, si les pneus sont récents et conservent encore toute leur adhérence", "Non, tu anticipes davantage et rends chaque pression plus progressive"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000016';
update public.question_translations set options = $pg$["Yes, the pedals always react the same way even when the road becomes slippery", "Yes, if the tyres are recent and still retain all of their grip", "No, act earlier and make every press more progressive as grip decreases"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000016' and lang = 'en';
update public.question_translations set options = $pg$["نعم، تستجيب الدواسات بالطريقة نفسها حتى عندما يصبح الطريق زلقًا", "نعم، إذا كانت الإطارات حديثة وما زالت تحتفظ بكل تماسكها", "لا، تتصرف أبكر وتجعل كل ضغط أكثر تدرجًا مع انخفاض التماسك"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000016' and lang = 'ar';

-- C1f
update public.questions_competence set options = $pg$["Quand la voiture est complètement immobile et le frein maintenu", "Pendant qu'elle roule encore doucement pour gagner quelques secondes", "Dès que le volant est droit même si les roues continuent de tourner"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000021';
update public.question_translations set options = $pg$["When the car is completely still and the brake is held", "While it is still rolling slowly to save a few seconds", "As soon as the wheel is straight even if the wheels are still turning"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000021' and lang = 'en';
update public.question_translations set options = $pg$["عندما تتوقف السيارة تمامًا وتبقي الفرامل مضغوطة", "بينما لا تزال تتحرك ببطء لتوفير بضع ثوان", "بمجرد أن يصبح المقود مستقيمًا حتى لو ظلت العجلات تدور"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000021' and lang = 'ar';

update public.questions_competence set options = $pg$["Oui, la voiture consomme toujours moins dès que la boîte est au point mort", "Non, tu gardes la boîte engagée pour conserver le frein moteur", "Oui, si la route est droite et que personne ne roule devant toi"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000022';
update public.question_translations set options = $pg$["Yes, the car always uses less fuel as soon as the gearbox is in neutral", "No, keep the gearbox engaged to retain engine braking throughout the descent", "Yes, if the road is straight and nobody is driving ahead of you"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000022' and lang = 'en';
update public.question_translations set options = $pg$["نعم، تستهلك السيارة وقودًا أقل دائمًا بمجرد وضع الناقل في المحايد", "لا، تبقي ناقل الحركة موصولًا للاستفادة من فرملة المحرك", "نعم، إذا كان الطريق مستقيمًا ولا توجد مركبة أمامك"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000022' and lang = 'ar';

update public.question_translations set options = $pg$["It stays resting on the control long after the gear change", "It looks for the next gear immediately after the change", "It returns to the steering wheel after the gear change"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000023' and lang = 'en';
update public.question_translations set options = $pg$["تبقى على أداة التحكم وقتًا طويلًا بعد تغيير السرعة", "تبحث فورًا عن السرعة التالية بعد التغيير", "تعود إلى المقود بعد الانتهاء من تغيير السرعة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000023' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu vérifies la position de la boîte pendant que la voiture reste immobile", "Tu accélères un peu pour tester le rapport alors que la voiture est encore arrêtée", "Tu demandes à ton passager de deviner la position affichée sur la boîte"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000024';
update public.question_translations set options = $pg$["Check the gearbox position while the car remains still", "Accelerate slightly to test the gear while the car is still stopped", "Ask your passenger to guess the position shown on the gearbox"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000024' and lang = 'en';
update public.question_translations set options = $pg$["تفحص وضع ناقل الحركة بينما تبقى السيارة ثابتة", "تسرع قليلًا لاختبار الوضع بينما لا تزال السيارة متوقفة", "تطلب من الراكب أن يخمن الوضع الظاهر على ناقل الحركة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000024' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu forces fortement le levier jusqu'à ce que la position passe malgré toute la résistance", "Tu gardes le frein, reviens à une position sûre et recommences sans forcer", "Tu accélères pour débloquer la boîte pendant que le frein reste maintenu"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000025';
update public.question_translations set options = $pg$["Force the lever hard until the position engages despite all the resistance", "Hold the brake, return to a safe position and try again without force", "Accelerate to release the gearbox while continuing to hold the brake"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000025' and lang = 'en';
update public.question_translations set options = $pg$["تجبر الرافعة بقوة حتى يستجيب الوضع رغم كل المقاومة", "تبقي الفرامل وتعود إلى وضع آمن ثم تحاول دون قوة", "تسرع لتحرير ناقل الحركة مع إبقاء الفرامل مضغوطة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000025' and lang = 'ar';

update public.question_translations set options = $pg$["تتابع السير حتى ينطفئ التحذير وحده بعد مسافة", "تغير الوضع عدة مرات أثناء السير حتى يستجيب النظام", "تتوقف بأمان وتطلب فحص السيارة قبل متابعة الرحلة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000026' and lang = 'ar';

-- C1g
update public.questions_competence set options = $pg$["Tu ne pars pas et tu fais contrôler le pneu avant de reprendre la route", "Tu roules doucement jusqu'au prochain plein en surveillant seulement l'alerte", "Tu ajoutes beaucoup d'air pour faire disparaître rapidement l'alerte"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000031';
update public.question_translations set options = $pg$["Do not set off and have the tyre checked before returning to the road", "Drive slowly until the next fuel stop while only watching the warning", "Add a lot of air to make the warning disappear quickly"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000031' and lang = 'en';
update public.question_translations set options = $pg$["لا تنطلق وتطلب فحص الإطار قبل العودة إلى الطريق", "تقود ببطء حتى محطة الوقود التالية وتراقب التحذير فقط", "تضيف كمية كبيرة من الهواء لإخفاء التحذير بسرعة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000031' and lang = 'ar';

update public.questions_competence set options = $pg$["Sur le pneu de la voiture voisine qui semble avoir exactement le même modèle", "Sur l'étiquette du véhicule ou dans son manuel prévu par le constructeur", "Sur le ticket de carburant conservé après ton dernier plein"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000032';
update public.question_translations set options = $pg$["On the tyre of the neighbouring car that appears to be exactly the same model", "On the vehicle label or in the handbook supplied by its manufacturer", "On the fuel receipt kept after your last visit to the station"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000032' and lang = 'en';
update public.question_translations set options = $pg$["على إطار السيارة المجاورة التي تبدو من الطراز نفسه تمامًا", "على ملصق السيارة أو في الدليل الذي قدمته الشركة المصنعة", "على إيصال الوقود المحفوظ بعد آخر تعبئة لك في المحطة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000032' and lang = 'ar';

update public.questions_competence set options = $pg$["Oui, la pluie les nettoiera complètement pendant les premiers kilomètres", "Oui, les feux servent seulement la nuit et restent inutiles sous la pluie", "Non, tu les nettoies avant de rouler pour rester visible de tous"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000033';
update public.question_translations set options = $pg$["Yes, the rain will clean them completely during the first few miles", "Yes, lights are only used at night and remain useless in the rain", "No, clean them before driving so that everyone can see you"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000033' and lang = 'en';
update public.question_translations set options = $pg$["نعم، سيغسلها المطر بالكامل خلال الكيلومترات الأولى", "نعم، لا تستعمل الأضواء إلا ليلًا وتبقى بلا فائدة تحت المطر", "لا، تنظفها بنفسك قبل القيادة حتى يراك جميع مستخدمي الطريق"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000033' and lang = 'ar';

update public.questions_competence set options = $pg$["Moteur froid, en lisant le niveau entre les repères", "Juste après un long trajet, en ouvrant immédiatement le bouchon", "Moteur chaud, bouchon ouvert juste après avoir coupé le contact"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000034';
update public.question_translations set options = $pg$["With the engine cold, reading the level between the marks", "Just after a long drive, by opening the cap immediately", "With the engine hot and the cap open just after switching off"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000034' and lang = 'en';
update public.question_translations set options = $pg$["عندما يكون المحرك باردًا مع قراءة المستوى بين العلامتين", "بعد رحلة طويلة مباشرة مع فتح السدادة فورًا", "عندما يكون المحرك ساخنًا وفتح السدادة بعد إطفائه مباشرة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000034' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu regardes uniquement tous les témoins du tableau de bord pour confirmer leur fonctionnement", "Tu utilises leur reflet sur un mur ou une vitrine pour vérifier chaque feu", "Tu allumes les feux de détresse et observes seulement leur témoin sur le tableau de bord"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000035';
update public.question_translations set options = $pg$["Look only at every dashboard warning light to confirm that the lamps work", "Use their reflection on a wall or shop window to check every light", "Switch on the hazard lights and only watch their dashboard indicator"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000035' and lang = 'en';
update public.question_translations set options = $pg$["تنظر فقط إلى كل مؤشرات لوحة القيادة للتأكد من عمل الأضواء", "تستعمل انعكاسها على جدار أو واجهة متجر لفحص كل ضوء", "تشغل أضواء الخطر وتراقب مؤشرها على اللوحة فقط"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000035' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu démarres et roules pour voir si elle disparaît après quelques mètres", "Tu recouvres la flaque avec de l'eau pour vérifier si elle se dilue", "Tu cherches son origine et signales la fuite avant de rouler"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000036';
update public.question_translations set options = $pg$["Start driving to see whether it disappears after a short distance", "Cover the puddle with water to check whether it becomes diluted", "Find its source and report the leak before driving"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000036' and lang = 'en';
update public.question_translations set options = $pg$["تشغل المحرك وتقود لترى إن كانت ستختفي بعد مسافة قصيرة", "تغطي البقعة بالماء لترى إن كانت ستصبح مخففة", "تبحث عن مصدرها وتبلغ عن التسرب قبل بدء القيادة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000036' and lang = 'ar';

-- C1h
update public.questions_competence set options = $pg$["Non, tu alternes toujours vision directe, rétroviseurs et écran", "Oui, l'écran montre tout autour de la voiture sans laisser de zone cachée", "Oui, si la voiture émet des bips qui remplacent tous tes contrôles"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000041';
update public.question_translations set options = $pg$["No, always alternate between direct vision, mirrors and the screen", "Yes, the screen shows everything around the car without any hidden area", "Yes, if the car beeps and replaces all of your own checks"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000041' and lang = 'en';
update public.question_translations set options = $pg$["لا، تتناوب دائمًا بين الرؤية المباشرة والمرايا والشاشة", "نعم، تعرض الشاشة كل ما حول السيارة دون أي منطقة مخفية", "نعم، إذا أصدرت السيارة صفيرًا يعوض كل مراقبتك"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000041' and lang = 'ar';

update public.questions_competence set options = $pg$["Seulement la roue arrière droite car elle suit directement le braquage", "L'avant de la voiture qui se déporte vers le côté opposé", "Aucune partie car toute la voiture reste dans la largeur de départ"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000042';
update public.question_translations set options = $pg$["Only the right rear wheel because it follows the steering directly", "The front of the car as it swings towards the opposite side", "No part of it because the whole car stays within its starting width"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000042' and lang = 'en';
update public.question_translations set options = $pg$["العجلة الخلفية اليمنى فقط لأنها تتبع التوجيه مباشرة", "مقدمة السيارة التي تنحرف نحو الجهة المقابلة", "لا ينحرف أي جزء لأن السيارة كلها تبقى ضمن عرضها الأول"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000042' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu continues car tes feux de recul sont allumés et lui demandent de s'écarter", "Tu klaxonnes plusieurs fois et poursuis la marche arrière sans attendre", "Tu t'arrêtes, tu le laisses passer puis tu contrôles de nouveau"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000043';
update public.question_translations set options = $pg$["Carry on because your reversing lights are on and tell the person to move", "Sound the horn several times and continue reversing without waiting", "Stop, let the person pass, then carefully check the whole area again"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000043' and lang = 'en';
update public.question_translations set options = $pg$["تتابع لأن أضواء الرجوع مضاءة وتطلب من الشخص أن يبتعد", "تستعمل المنبه عدة مرات وتواصل الرجوع دون انتظار", "تتوقف وتترك الشخص يمر ثم تراقب المنطقة من جديد"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000043' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu ajoutes des mouvements en contrôlant autour de la voiture à chaque fois", "Tu montes sur le trottoir pour gagner la place qui manque dans la rue", "Tu accélères pour braquer plus vite et terminer dans les trois mouvements"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000044';
update public.question_translations set options = $pg$["Add more movements and check the surroundings every time", "Drive onto the pavement to gain the space missing from the street", "Accelerate to steer faster and finish within the three movements"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000044' and lang = 'en';
update public.question_translations set options = $pg$["تضيف حركات أخرى مع مراقبة ما حول السيارة في كل مرة", "تصعد على الرصيف لكسب المساحة الناقصة في الشارع", "تسرع لتدير المقود أسرع وتنهي المناورة في ثلاث حركات"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000044' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu termines vite en espérant être dans les lignes sans effectuer de nouveau contrôle", "Tu t'arrêtes, te replaces et reprends avec de nouveaux contrôles", "Tu regardes seulement la voiture de gauche pour guider toute ta correction"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000045';
update public.question_translations set options = $pg$["Finish quickly and hope you are inside the lines without making another check", "Stop completely, reposition the car and start again after making fresh checks", "Look only at the car on the left to guide your whole correction"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000045' and lang = 'en';
update public.question_translations set options = $pg$["تنهي بسرعة وتأمل أن تكون داخل الخطوط دون إجراء مراقبة جديدة", "تتوقف تمامًا وتعيد وضع السيارة ثم تبدأ بعد مراقبة جديدة", "تنظر فقط إلى السيارة اليسرى لتوجيه التصحيح كله"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000045' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu continues au pas en supposant que l'enfant restera hors de ta trajectoire", "Tu te fies entièrement aux capteurs pour retrouver sa position autour de la voiture", "Tu t'arrêtes et restes immobile jusqu'à savoir exactement où se trouve l'enfant"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000046';
update public.question_translations set options = $pg$["Carry on at walking pace and assume the child will remain outside your path", "Rely entirely on the sensors to locate the child somewhere around the car", "Stop and remain still until you know exactly where the child is"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000046' and lang = 'en';
update public.question_translations set options = $pg$["تتابع بسرعة المشي وتفترض أن الطفل سيبقى خارج مسارك", "تعتمد بالكامل على الحساسات لمعرفة مكان الطفل حول السيارة", "تتوقف وتبقى ثابتًا حتى تعرف مكان الطفل بدقة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000046' and lang = 'ar';

-- C1i
update public.questions_competence set options = $pg$["Chercher une autre place avec une marge suffisante pour manœuvrer", "Essayer quand même pour prouver ton niveau à la personne qui te regarde", "Attendre que quelqu'un te guide pendant toute la manœuvre"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000051';
update public.question_translations set options = $pg$["Find another space with enough room to complete the manoeuvre", "Try anyway to prove your skill to the person watching you", "Wait for someone to guide you throughout the whole manoeuvre"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000051' and lang = 'en';
update public.question_translations set options = $pg$["تبحث عن مكان آخر فيه مساحة كافية للمناورة", "تحاول رغم ذلك لتثبت مهارتك أمام من يراقبك", "تنتظر من يوجهك طوال المناورة خطوة بخطوة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000051' and lang = 'ar';

update public.questions_competence set options = $pg$["La voiture derrière toi qui attend de pouvoir reprendre sa route", "Toi, après avoir vérifié que la place est autorisée et adaptée", "Ton passager qui te dicte chaque geste pendant toute la manœuvre"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000052';
update public.question_translations set options = $pg$["The car behind you that is waiting to continue its journey", "You, after checking that the space is allowed and suitable", "Your passenger who dictates each move throughout the manoeuvre"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000052' and lang = 'en';
update public.question_translations set options = $pg$["السيارة خلفك التي تنتظر حتى تواصل طريقها", "أنت، بعد التأكد من أن المكان مسموح ومناسب", "الراكب معك الذي يملي عليك كل حركة طوال المناورة"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000052' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu restes immobile, tu le laisses passer puis tu réévalues la situation", "Tu commences rapidement la correction avant que le véhicule ne se rapproche", "Tu lui fais signe de te contourner sans interrompre ta préparation"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000054';
update public.question_translations set options = $pg$["Stay still, let it pass, then assess the situation again", "Start the correction quickly before the vehicle comes any closer", "Signal for it to go around you without interrupting your preparation"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000054' and lang = 'en';
update public.question_translations set options = $pg$["تبقى ثابتًا وتتركها تمر ثم تعيد تقييم الوضع", "تبدأ التصحيح بسرعة قبل أن تقترب المركبة أكثر", "تطلب منها بالإشارة أن تتجاوزك دون إيقاف استعدادك"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000054' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu recules aussitôt sur la chaussée pour retrouver l'entrée manquée", "Tu continues et cherches un endroit sûr pour revenir", "Tu t'arrêtes au milieu de la voie pour réfléchir au trajet"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000055';
update public.question_translations set options = $pg$["Reverse immediately on the road to return to the missed entrance", "Carry on calmly and find a safe place from which to come back", "Stop in the middle of the lane to think about the route"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000055' and lang = 'en';
update public.question_translations set options = $pg$["ترجع فورًا على الطريق للعودة إلى المدخل الذي فاتك", "تتابع بهدوء وتبحث عن مكان آمن يمكنك العودة منه", "تتوقف في وسط المسار للتفكير في الطريق"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000055' and lang = 'ar';

update public.questions_competence set options = $pg$["Tu coupes le moteur alors que la voiture roule encore vers sa position finale", "Tu ouvres la porte pendant la manœuvre pour vérifier précisément les lignes au sol", "Tu immobilises la voiture, la sécurises puis contrôles qu'elle ne gêne personne"]$pg$::jsonb where id = 'c1d1c1e1-8000-4000-8000-000000000056';
update public.question_translations set options = $pg$["Switch off the engine while the car is still moving towards its final position", "Open the door during the manoeuvre to check the road markings precisely", "Stop the car, secure it, then check that it obstructs nobody"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000056' and lang = 'en';
update public.question_translations set options = $pg$["تطفئ المحرك بينما لا تزال السيارة تتحرك نحو موضعها النهائي", "تفتح الباب أثناء المناورة لفحص الخطوط على الأرض بدقة", "توقف السيارة وتؤمنها ثم تتأكد من أنها لا تعيق أحدًا قبل تركها"]$pg$::jsonb where question_id = 'c1d1c1e1-8000-4000-8000-000000000056' and lang = 'ar';
