-- Banque de certification, lot 3.
-- C3a à C3g atteignent au moins 12 questions jouables pour chaque boîte.
-- Les 42 questions ajoutées portent sur des gestes communs aux deux boîtes.

insert into public.questions_competence
  (id, competence_id, question, options, correct_index, explanation, difficulty, type, boite)
values
('c3a3c3b3-8000-4000-8000-000000000001','C3a',
 $pg$Tu roules à faible distance derrière une voiture sur une route noire. Quels feux gardes-tu ?$pg$,
 $pg$["Les feux de croisement", "Les feux de route", "Les feux de brouillard arrière"]$pg$::jsonb,
 0,
 $pg$Les feux de route se reflètent dans ses rétroviseurs et gênent son conducteur. Les feux de croisement éclairent sans remplir son habitacle de lumière.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000002','C3a',
 $pg$Tu arrives au sommet d'une côte avec les feux de route. Quand repasses-tu en feux de croisement ?$pg$,
 $pg$["Seulement après avoir vu une voiture", "Avant le sommet car un usager peut être caché", "Une fois engagé dans la descente"]$pg$::jsonb,
 1,
 $pg$Le relief cache la route opposée mais pas ton faisceau. Baisser les feux avant le sommet évite d'éblouir quelqu'un dès son apparition.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000003','C3a',
 $pg$Une voiture en face garde ses feux de route et t'éblouit. Comment conserves-tu ta trajectoire ?$pg$,
 $pg$["Tu lui réponds avec tes feux de route", "Tu fixes ses phares pour suivre sa position", "Tu ralentis et guides ton regard vers le bord droit"]$pg$::jsonb,
 2,
 $pg$Fixer la lumière prolonge l'éblouissement. Le bord droit reste un repère de trajectoire pendant que la baisse d'allure réduit la distance parcourue presque à l'aveugle.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000004','C3a',
 $pg$Tu t'arrêtes de nuit sur un emplacement sûr hors de la chaussée. Que fais-tu de tes feux de route ?$pg$,
 $pg$["Tu les éteins", "Tu les gardes pour éclairer loin", "Tu les fais clignoter en continu"]$pg$::jsonb,
 0,
 $pg$Les feux de route servent à circuler et peuvent éblouir même quand la voiture ne bouge plus. À l'arrêt, tu utilises seulement la signalisation adaptée à ta situation.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000005','C3a',
 $pg$Ta vitesse ne te permet plus de t'arrêter dans la portion éclairée devant toi. Que corriges-tu ?$pg$,
 $pg$["Tu regardes juste plus loin", "Tu ralentis jusqu'à pouvoir t'arrêter dans ce que tu vois", "Tu te rapproches du véhicule devant"]$pg$::jsonb,
 1,
 $pg$La nuit cache l'obstacle au-delà du faisceau. Ta distance d'arrêt doit tenir dans la route réellement visible, pas dans celle que tu imagines libre.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000006','C3a',
 $pg$Les phares d'une voiture derrière se reflètent fortement dans ton rétroviseur intérieur. Ton geste ?$pg$,
 $pg$["Tu retournes complètement le rétroviseur", "Tu accélères pour t'éloigner", "Tu utilises sa position nuit sans cesser de surveiller derrière"]$pg$::jsonb,
 2,
 $pg$La position nuit atténue le reflet tout en gardant le véhicule visible. Retourner le miroir supprimerait une information utile au lieu de réduire seulement l'éblouissement.$pg$,
 3,'post_validation',null),

('c3a3c3b3-8000-4000-8000-000000000011','C3b',
 $pg$Tu entres dans une nappe de brouillard. Quels feux évitent de créer un mur lumineux devant toi ?$pg$,
 $pg$["Les feux de croisement", "Les feux de route", "Les feux de position seuls"]$pg$::jsonb,
 0,
 $pg$Les feux de route renvoient leur lumière sur les gouttelettes et réduisent encore la vue. Les feux de croisement éclairent plus bas et te rendent visible.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000012','C3b',
 $pg$Le brouillard se lève et une voiture roule derrière toi. Que fais-tu du feu de brouillard arrière ?$pg$,
 $pg$["Tu le gardes jusqu'à la fin du trajet", "Tu l'éteins dès qu'il n'est plus nécessaire", "Tu le remplaces par les feux de détresse"]$pg$::jsonb,
 1,
 $pg$Ce feu très puissant aide à te repérer dans le brouillard ou la neige. Quand la visibilité revient, il éblouit inutilement celui qui te suit.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000013','C3b',
 $pg$Une pluie violente dépasse la capacité de tes essuie-glaces. Quelle décision prends-tu ?$pg$,
 $pg$["Tu suis de près les feux devant", "Tu gardes l'allure pour sortir vite de l'averse", "Tu ralentis sans geste brusque et t'arrêtes en lieu sûr si la vue reste insuffisante"]$pg$::jsonb,
 2,
 $pg$Quand les balais ne rendent plus une vue exploitable, la vitesse doit tomber avec la visibilité. Un arrêt sûr vaut mieux qu'une trajectoire devinée.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000014','C3b',
 $pg$Les projections d'un camion masquent ton pare-brise avant un dépassement. Comment retrouves-tu de la visibilité ?$pg$,
 $pg$["Tu augmentes d'abord l'écart et règles les essuie-glaces", "Tu te rapproches pour réduire le temps de dépassement", "Tu te décales sans attendre de voir"]$pg$::jsonb,
 0,
 $pg$Plus loin du camion, le nuage d'eau est moins dense et ton champ de vision s'ouvre. Tu ne commences le dépassement qu'avec une route de nouveau lisible.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000015','C3b',
 $pg$Le soleil rasant efface presque un feu et les silhouettes devant toi. Quelle marge crées-tu ?$pg$,
 $pg$["Tu te guides sur la voiture devant", "Tu utilises le pare-soleil et ralentis jusqu'à distinguer la route", "Tu mets les feux de route"]$pg$::jsonb,
 1,
 $pg$Le pare-soleil coupe la source directe mais ne rend pas immédiatement tous les détails. Ralentir te laisse le temps d'identifier un feu, un piéton ou un arrêt.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000016','C3b',
 $pg$Dans le brouillard, la voiture que tu suivais disparaît au loin. Comment choisis-tu ton allure ?$pg$,
 $pg$["Tu accélères pour retrouver ses feux", "Tu gardes sa dernière vitesse connue", "Tu te fies à ta propre distance visible et conserves un grand écart"]$pg$::jsonb,
 2,
 $pg$Les feux d'un autre véhicule ne prouvent pas que l'espace entre vous est libre. Ta visibilité et ta capacité à t'arrêter doivent seules fixer ton allure.$pg$,
 3,'post_validation',null),

('c3a3c3b3-8000-4000-8000-000000000021','C3c',
 $pg$Les premières gouttes tombent après plusieurs jours secs. Comment abordes-tu le prochain giratoire ?$pg$,
 $pg$["Tu ralentis avant et gardes des gestes souples", "Tu freines fort une fois engagé", "Tu gardes l'allure car la route paraît propre"]$pg$::jsonb,
 0,
 $pg$Le début de pluie mélange l'eau aux poussières et résidus de la chaussée. Anticiper avant le virage évite de demander trop d'adhérence aux pneus.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000022','C3c',
 $pg$Dans une grande flaque, le volant devient soudain très léger. Ton premier geste ?$pg$,
 $pg$["Tu freines à fond", "Tu lèves progressivement le pied et gardes le volant stable", "Tu braques vite vers le bord"]$pg$::jsonb,
 1,
 $pg$Les pneus peuvent flotter sur l'eau et ne plus guider la voiture. Lever le pied sans freinage ni coup de volant leur permet de retrouver le contact.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000023','C3c',
 $pg$Tu dois traverser des flèches peintes mouillées dans un virage. Quelle action évites-tu dessus ?$pg$,
 $pg$["Regarder la sortie", "Tenir le volant des deux mains", "Freiner ou tourner brusquement"]$pg$::jsonb,
 2,
 $pg$La peinture mouillée accroche moins que l'enrobé. Une vitesse réglée avant et une trajectoire douce laissent aux pneus la petite adhérence disponible.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000024','C3c',
 $pg$Une descente enneigée commence devant toi. Que règles-tu avant la pente ?$pg$,
 $pg$["Une faible allure et un grand espace devant", "Une allure élevée pour ne pas rester bloqué", "Un freinage continu pendant toute la descente"]$pg$::jsonb,
 0,
 $pg$Dans la pente, la gravité pousse alors que les pneus accrochent peu. La marge se prépare avant, avec de la distance et des commandes progressives.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000025','C3c',
 $pg$Des graviers couvrent l'entrée d'un virage. Comment traverses-tu la zone ?$pg$,
 $pg$["Tu piles juste avant chaque gravier", "Tu ralentis avant puis gardes une trajectoire régulière", "Tu coupes le virage pour les éviter"]$pg$::jsonb,
 1,
 $pg$Les graviers roulent sous le pneu comme de petites billes. Réduire l'allure avant évite de devoir freiner ou corriger fortement dessus.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000026','C3c',
 $pg$Une flaque profonde ne touche que les roues droites. Comment limites-tu le déport de la voiture ?$pg$,
 $pg$["Tu lâches le volant pour le laisser revenir", "Tu donnes un coup de volant à gauche", "Tu ralentis avant et tiens le volant sans geste brusque"]$pg$::jsonb,
 2,
 $pg$L'eau freine davantage un côté et peut tirer la voiture. Des mains stables gardent l'axe, tandis qu'une faible allure réduit la force du déport.$pg$,
 3,'post_validation',null),

('c3a3c3b3-8000-4000-8000-000000000031','C3d',
 $pg$Le voyant de pression des pneus s'allume avant une voie rapide. Ton premier choix ?$pg$,
 $pg$["Tu contrôles les pneus et la pression avant de poursuivre vite", "Tu accélères pour voir si le voyant s'éteint", "Tu ignores le voyant jusqu'au prochain entretien"]$pg$::jsonb,
 0,
 $pg$Un pneu mal gonflé se déforme et tient moins bien sa trajectoire. Le vérifier avant la vitesse protège l'adhérence dont le freinage dépend.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000032','C3d',
 $pg$Une longue descente commence alors qu'une file roule devant toi. Quelle marge augmentes-tu ?$pg$,
 $pg$["La vitesse pour ne pas freiner", "La distance avec le véhicule précédent", "Le régime du moteur à l'arrêt"]$pg$::jsonb,
 1,
 $pg$La pente pousse la voiture et réduit ta marge si la file s'arrête. Un écart plus grand permet de ralentir tôt au lieu de déclencher un freinage brutal.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000033','C3d',
 $pg$Sur du verglas, l'ABS peut-il compenser une vitesse trop élevée ?$pg$,
 $pg$["Oui, il recrée de l'adhérence", "Oui, si tu tournes en même temps", "Non, il évite le blocage mais ne fabrique pas d'accroche"]$pg$::jsonb,
 2,
 $pg$L'ABS aide les roues à rester dirigeables, mais il travaille avec l'adhérence disponible. Sur la glace, seule une allure très basse conserve une vraie marge.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000034','C3d',
 $pg$Une bouteille roule près des pédales avant ton départ. Que fais-tu ?$pg$,
 $pg$["Tu la ranges hors du plancher", "Tu la bloques avec ton pied libre", "Tu la laisses car elle est légère"]$pg$::jsonb,
 0,
 $pg$Un objet peut se coincer sous la pédale au moment où tu dois freiner à fond. Un plancher vide garantit toute la course de la commande.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000035','C3d',
 $pg$Les témoins d'usure de tes pneus arrivent au niveau des sculptures avant un trajet pluvieux. Ta décision ?$pg$,
 $pg$["Tu gonfles davantage et tu pars", "Tu fais contrôler ou remplacer les pneus avant le trajet", "Tu roules seulement avec les feux allumés"]$pg$::jsonb,
 1,
 $pg$Les rainures évacuent l'eau sous le pneu. Quand elles disparaissent, le film d'eau s'évacue moins bien et le freinage perd sa réserve d'adhérence.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000036','C3d',
 $pg$Après une zone très inondée, la réponse du frein te semble anormale. Que fais-tu ?$pg$,
 $pg$["Tu reprends immédiatement une allure normale", "Tu pompes vite en accélérant", "Tu ralentis, testes doucement en sécurité et t'arrêtes si le défaut reste"]$pg$::jsonb,
 2,
 $pg$De l'eau peut modifier temporairement le contact des freins. Un essai doux à faible allure vérifie leur réponse sans attendre une urgence réelle.$pg$,
 3,'post_validation',null),

('c3a3c3b3-8000-4000-8000-000000000041','C3e',
 $pg$Tu dépasses ta sortie d'autoroute. Comment corriges-tu ton trajet ?$pg$,
 $pg$["Tu continues jusqu'à la prochaine sortie", "Tu recules sur la bande d'arrêt d'urgence", "Tu t'arrêtes pour attendre une ouverture"]$pg$::jsonb,
 0,
 $pg$Une sortie manquée ne justifie jamais un arrêt ni une marche arrière. La prochaine sortie permet de revenir sans surprendre un trafic rapide.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000042','C3e',
 $pg$Ta voiture est immobilisée sur la bande d'arrêt d'urgence. Où te mets-tu après avoir enfilé ton gilet ?$pg$,
 $pg$["Devant la voiture pour être visible", "Derrière la barrière de sécurité en sortant côté passager", "Dans la voiture pour appeler tranquillement"]$pg$::jsonb,
 1,
 $pg$La carrosserie ne protège pas d'un véhicule qui dévie sur l'accotement. Sortir loin du trafic puis passer derrière la barrière éloigne ton corps de la zone de choc.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000043','C3e',
 $pg$Tes paupières deviennent lourdes sur autoroute. Quel arrêt choisis-tu ?$pg$,
 $pg$["La bande d'arrêt d'urgence", "La voie la plus lente avec les feux de détresse", "La prochaine aire pour te reposer avant de repartir"]$pg$::jsonb,
 2,
 $pg$La bande d'arrêt d'urgence répond à une nécessité absolue, pas à une pause prévue. Une aire te met hors du trafic et permet un vrai repos.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000044','C3e',
 $pg$Un conducteur te colle pendant que tu dépasses sur autoroute. Quelle réaction reste sûre ?$pg$,
 $pg$["Tu termines sans dépasser la limite puis te rabats avec une marge", "Tu freines pour lui faire comprendre", "Tu accélères jusqu'à le distancer"]$pg$::jsonb,
 0,
 $pg$Sa pression ne change ni la limitation ni l'espace nécessaire au rabattement. Une manœuvre prévisible évite d'ajouter un conflit à son comportement dangereux.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000045','C3e',
 $pg$Tu approches d'un péage et hésites entre plusieurs voies. Comment choisis-tu ?$pg$,
 $pg$["Tu changes de voie au dernier moment", "Tu ralentis tôt et suis les symboles d'une voie ouverte", "Tu t'arrêtes au milieu pour lire tous les panneaux"]$pg$::jsonb,
 1,
 $pg$Les symboles annoncent le paiement accepté et l'état de la voie. Les lire tôt évite une diagonale brusque entre des véhicules qui ralentissent.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000046','C3e',
 $pg$Une voiture accélère sur la bande d'insertion à ta droite. Comment facilites-tu son arrivée sans te mettre en danger ?$pg$,
 $pg$["Tu t'arrêtes pour la laisser entrer", "Tu changes de voie sans contrôler", "Tu ajustes ton allure ou te décales seulement si l'espace est libre"]$pg$::jsonb,
 2,
 $pg$Le véhicule déjà sur l'autoroute garde sa trajectoire prioritaire, mais une adaptation souple peut ouvrir un espace. Tout déplacement reste soumis aux contrôles.$pg$,
 3,'post_validation',null),

('c3a3c3b3-8000-4000-8000-000000000051','C3f',
 $pg$Tu portes des lunettes de soleil avant d'entrer dans un tunnel. Quand les retires-tu ?$pg$,
 $pg$["Avant l'entrée, avec les feux de croisement déjà allumés", "Au milieu du tunnel", "Après la sortie"]$pg$::jsonb,
 0,
 $pg$Tes yeux ont besoin de temps pour passer du jour à l'obscurité. Préparer la vue et l'éclairage avant l'entrée évite quelques secondes presque aveugles.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000052','C3f',
 $pg$La circulation s'immobilise durablement dans un tunnel. Ton geste ?$pg$,
 $pg$["Tu te rapproches du véhicule devant", "Tu gardes un espace, allumes les feux de détresse et coupes le moteur", "Tu fais demi-tour vers l'entrée"]$pg$::jsonb,
 1,
 $pg$L'espace devant offre une issue si les consignes demandent de bouger. Le moteur coupé limite les fumées dans ce volume fermé.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000053','C3f',
 $pg$De la fumée épaisse apparaît devant toi dans un tunnel. Quelle priorité ?$pg$,
 $pg$["Attendre dans la voiture que le trafic reparte", "Reculer jusqu'à l'entrée", "T'arrêter, couper le moteur et rejoindre rapidement une issue signalée"]$pg$::jsonb,
 2,
 $pg$La fumée peut devenir toxique et supprimer toute visibilité en quelques instants. Une issue balisée mène vers un espace protégé sans traverser le trafic en sens inverse.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000054','C3f',
 $pg$Ton moteur tombe en panne dans un tunnel. Quelle séquence lance l'alerte ?$pg$,
 $pg$["Tu gagnes un emplacement à droite si possible, mets les feux de détresse et utilises une borne de secours", "Tu restes sur ta voie pour appeler avec ton téléphone", "Tu pousses seul la voiture jusqu'à la sortie"]$pg$::jsonb,
 0,
 $pg$La borne indique immédiatement ta position au poste de contrôle. Te placer à droite et signaler la voiture réduit d'abord le risque de collision.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000055','C3f',
 $pg$Dans des travaux, des lignes jaunes contredisent les anciennes lignes blanches. Lesquelles suis-tu ?$pg$,
 $pg$["Les blanches car elles sont permanentes", "Les jaunes car elles organisent le passage temporaire", "Celles de la voie la plus large"]$pg$::jsonb,
 1,
 $pg$Le chantier déplace provisoirement la circulation autour du danger et des ouvriers. Le marquage jaune donne la trajectoire valable pendant les travaux.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000056','C3f',
 $pg$Un panneau de hauteur limitée précède un pont et ton coffre de toit te fait douter. Que fais-tu ?$pg$,
 $pg$["Tu passes lentement pour tester", "Tu suis un véhicule qui paraît aussi haut", "Tu t'arrêtes avant l'obstacle et vérifies la hauteur ou changes d'itinéraire"]$pg$::jsonb,
 2,
 $pg$Le panneau concerne la hauteur totale avec le chargement. Un doute se résout avant le pont, car le contact peut arracher le coffre et bloquer la circulation.$pg$,
 3,'post_validation',null),

('c3a3c3b3-8000-4000-8000-000000000061','C3g',
 $pg$Tu longes des voitures garées et plusieurs conducteurs sont encore à bord. Quelle marge gardes-tu ?$pg$,
 $pg$["De l'espace pour une portière et une allure permettant l'arrêt", "Quelques centimètres pour laisser plus de place à gauche", "Aucune marge si les feux sont éteints"]$pg$::jsonb,
 0,
 $pg$Une main ou une silhouette dans l'habitacle annonce une ouverture possible. L'écart latéral protège même si la portière apparaît sans regard.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000062','C3g',
 $pg$Ton feu est vert mais la file bloque toute la sortie du carrefour. Que fais-tu ?$pg$,
 $pg$["Tu avances pour profiter du vert", "Tu attends avant la ligne jusqu'à pouvoir libérer l'intersection", "Tu entres puis mets les feux de détresse"]$pg$::jsonb,
 1,
 $pg$Le vert autorise le passage sans permettre de bloquer les voies transversales. Attendre garde le carrefour disponible quand leur feu changera.$pg$,
 1,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000063','C3g',
 $pg$À la sortie d'une école, un enfant court entre deux voitures garées. Ton geste ?$pg$,
 $pg$["Tu klaxonnes et gardes l'allure", "Tu te déportes immédiatement à gauche", "Tu ralentis fortement et te prépares à t'arrêter"]$pg$::jsonb,
 2,
 $pg$L'enfant peut surgir sans mesurer ta distance ni ta vitesse. Le pied prêt au frein transforme l'espace masqué en zone où l'arrêt reste possible.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000064','C3g',
 $pg$Dans une file lente, une trottinette remonte près de ta portière droite. Tu veux te décaler. Ton geste ?$pg$,
 $pg$["Tu contrôles le rétroviseur et l'angle mort puis attends un espace libre", "Tu mets le clignotant et te décales tout de suite", "Tu serres à droite pour empêcher son passage"]$pg$::jsonb,
 0,
 $pg$Ce petit usager peut rester invisible très près de la voiture. Le clignotant annonce ton mouvement mais seul le contrôle direct confirme que le côté est libre.$pg$,
 2,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000065','C3g',
 $pg$Un passage piéton est caché par un véhicule haut garé juste avant. Comment approches-tu ?$pg$,
 $pg$["Tu regardes seulement si le feu est vert", "Tu ralentis assez pour t'arrêter avant un piéton masqué", "Tu te décales sur la voie opposée"]$pg$::jsonb,
 1,
 $pg$Le véhicule coupe la vue mais pas la possibilité qu'une personne traverse. Réduire l'allure avant de découvrir le passage conserve ta distance d'arrêt.$pg$,
 3,'post_validation',null),
('c3a3c3b3-8000-4000-8000-000000000066','C3g',
 $pg$Au feu rouge, un sas réservé aux vélos se trouve devant ta ligne d'arrêt. Où immobilises-tu la voiture ?$pg$,
 $pg$["Dans le sas s'il est vide", "Au niveau des vélos déjà présents", "Avant la première ligne pour laisser le sas libre"]$pg$::jsonb,
 2,
 $pg$Le sas place les cyclistes devant les voitures pour qu'ils soient visibles au redémarrage. L'occuper les renvoie dans les angles morts et leur retire cet espace.$pg$,
 3,'post_validation',null)
on conflict (id) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000001','en',
 $pg$You are driving a short distance behind a car on an unlit road. Which lights do you use?$pg$,
 $pg$["Dipped headlights", "Main beam headlights", "Rear fog lights"]$pg$::jsonb,
 $pg$Main beam reflects in its mirrors and distracts the driver. Dipped headlights light your way without filling the other car with glare.$pg$),
('c3a3c3b3-8000-4000-8000-000000000001','ar',
 $pg$تسير على مسافة قصيرة خلف سيارة في طريق غير مضاء. أي أضواء تستخدم؟$pg$,
 $pg$["الأضواء المنخفضة", "الأضواء العالية", "أضواء الضباب الخلفية"]$pg$::jsonb,
 $pg$تنعكس الأضواء العالية في مرايا السيارة وتزعج سائقها. أما الأضواء المنخفضة فتنير طريقك من دون أن تملأ سيارته بالوهج.$pg$),
('c3a3c3b3-8000-4000-8000-000000000002','en',
 $pg$You are approaching the crest of a hill with main beam on. When do you dip your headlights?$pg$,
 $pg$["Only after seeing a vehicle", "Before the crest because another road user may be hidden", "Once you have started going downhill"]$pg$::jsonb,
 $pg$The hill hides the opposite road but not your beam. Dipping before the crest prevents you from dazzling someone as soon as they appear.$pg$),
('c3a3c3b3-8000-4000-8000-000000000002','ar',
 $pg$تقترب من قمة مرتفع وأضواؤك العالية مشغلة. متى تنتقل إلى الأضواء المنخفضة؟$pg$,
 $pg$["بعد رؤية سيارة فقط", "قبل القمة لأن مستخدمًا آخر قد يكون محجوبًا", "بعد بدء النزول"]$pg$::jsonb,
 $pg$يحجب المرتفع الطريق المقابل لكنه لا يحجب شعاع أضوائك. خفضها قبل القمة يمنع إبهار شخص يظهر فجأة.$pg$),
('c3a3c3b3-8000-4000-8000-000000000003','en',
 $pg$An oncoming driver keeps main beam on and dazzles you. How do you hold your line?$pg$,
 $pg$["You answer with your own main beam", "You stare at the headlights to track the car", "You slow down and guide your eyes towards the right edge"]$pg$::jsonb,
 $pg$Staring at the light prolongs the glare. The right edge remains a guide while slowing down reduces the distance travelled with very limited vision.$pg$),
('c3a3c3b3-8000-4000-8000-000000000003','ar',
 $pg$يبقي سائق قادم أضواءه العالية ويبهرك. كيف تحافظ على مسارك؟$pg$,
 $pg$["ترد عليه بأضوائك العالية", "تحدق في أضوائه لتتابع موقعه", "تبطئ وتوجه نظرك نحو الحافة اليمنى"]$pg$::jsonb,
 $pg$التحديق في الضوء يطيل الإبهار. تبقى الحافة اليمنى مرجعًا للمسار، ويقلل التباطؤ المسافة التي تقطعها برؤية شديدة الضعف.$pg$),
('c3a3c3b3-8000-4000-8000-000000000004','en',
 $pg$You stop at night in a safe place away from the carriageway. What do you do with main beam?$pg$,
 $pg$["You switch it off", "You keep it on to light the distance", "You flash it continuously"]$pg$::jsonb,
 $pg$Main beam is for driving and can dazzle people even when the car has stopped. When stationary, use only the signals suited to your situation.$pg$),
('c3a3c3b3-8000-4000-8000-000000000004','ar',
 $pg$تتوقف ليلًا في مكان آمن بعيد عن الطريق. ماذا تفعل بالأضواء العالية؟$pg$,
 $pg$["تطفئها", "تبقيها لتضيء بعيدًا", "تجعلها تومض باستمرار"]$pg$::jsonb,
 $pg$الأضواء العالية مخصصة للسير وقد تبهر الآخرين حتى والسيارة متوقفة. عند التوقف تستخدم إشارات الإضاءة المناسبة لوضعك فقط.$pg$),
('c3a3c3b3-8000-4000-8000-000000000005','en',
 $pg$Your speed no longer lets you stop within the stretch lit ahead. What do you change?$pg$,
 $pg$["You simply look further ahead", "You slow down until you can stop within what you can see", "You move closer to the vehicle ahead"]$pg$::jsonb,
 $pg$At night, an obstacle beyond the beam is hidden. Your stopping distance must fit within the road you can actually see, not the road you assume is clear.$pg$),
('c3a3c3b3-8000-4000-8000-000000000005','ar',
 $pg$لم تعد سرعتك تسمح لك بالتوقف داخل الجزء المضاء أمامك. ماذا تغير؟$pg$,
 $pg$["تنظر إلى مسافة أبعد فقط", "تبطئ حتى تستطيع التوقف داخل الجزء الذي تراه", "تقترب من المركبة أمامك"]$pg$::jsonb,
 $pg$يخفي الليل أي عائق بعد نهاية الشعاع. يجب أن تدخل مسافة توقفك داخل الطريق الذي تراه فعلًا لا الطريق الذي تفترض أنه خال.$pg$),
('c3a3c3b3-8000-4000-8000-000000000006','en',
 $pg$The headlights of a car behind glare strongly in your interior mirror. What do you do?$pg$,
 $pg$["You turn the mirror completely away", "You accelerate to get away", "You use its night setting while still monitoring behind"]$pg$::jsonb,
 $pg$The night setting reduces glare while keeping the vehicle visible. Turning the mirror away would remove useful information instead of reducing only the brightness.$pg$),
('c3a3c3b3-8000-4000-8000-000000000006','ar',
 $pg$تنعكس أضواء سيارة خلفك بقوة في المرآة الداخلية. ماذا تفعل؟$pg$,
 $pg$["تدير المرآة بعيدًا تمامًا", "تسرع للابتعاد", "تستخدم وضعها الليلي مع الاستمرار في مراقبة الخلف"]$pg$::jsonb,
 $pg$يخفف الوضع الليلي الوهج مع إبقاء السيارة ظاهرة. إدارة المرآة بعيدًا تحذف معلومة مفيدة بدل خفض شدة الضوء فقط.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000061','en',
 $pg$You pass parked cars and several drivers are still inside. What margin do you keep?$pg$,
 $pg$["Room for a door and a speed that allows you to stop", "A few centimetres to leave more space on the left", "No margin if their lights are off"]$pg$::jsonb,
 $pg$A hand or a person inside suggests a door may open. Side clearance protects them even if the door appears without a check.$pg$),
('c3a3c3b3-8000-4000-8000-000000000061','ar',
 $pg$تمر بمحاذاة سيارات متوقفة ولا يزال عدة سائقين داخلها. أي هامش تترك؟$pg$,
 $pg$["مساحة لباب وسرعة تسمح لك بالتوقف", "بضعة سنتيمترات لترك مساحة أكبر يسارًا", "لا هامش إذا كانت أضواؤها مطفأة"]$pg$::jsonb,
 $pg$تشير يد أو هيئة داخل السيارة إلى احتمال فتح باب. تحمي المسافة الجانبية حتى لو ظهر الباب من دون فحص.$pg$),
('c3a3c3b3-8000-4000-8000-000000000062','en',
 $pg$Your light is green but the queue blocks the entire exit of the junction. What do you do?$pg$,
 $pg$["Move in to use the green light", "Wait before the line until you can clear the junction", "Enter then switch on the hazard lights"]$pg$::jsonb,
 $pg$Green permits you to pass but not to block crossing traffic. Waiting keeps the junction open when their signal changes.$pg$),
('c3a3c3b3-8000-4000-8000-000000000062','ar',
 $pg$إشارتك خضراء لكن الصف يسد مخرج التقاطع بالكامل. ماذا تفعل؟$pg$,
 $pg$["تدخل للاستفادة من الأخضر", "تنتظر قبل الخط حتى تستطيع إخلاء التقاطع", "تدخل ثم تشغل أضواء التحذير"]$pg$::jsonb,
 $pg$يسمح لك الأخضر بالمرور لكنه لا يسمح بسد الطرق المتقاطعة. يبقي الانتظار التقاطع خاليًا عندما تتغير إشارتهم.$pg$),
('c3a3c3b3-8000-4000-8000-000000000063','en',
 $pg$Outside a school, a child runs between two parked cars. What do you do?$pg$,
 $pg$["Sound the horn and keep your speed", "Move left immediately", "Slow down sharply and prepare to stop"]$pg$::jsonb,
 $pg$The child may appear without judging your distance or speed. Being ready on the brake turns the hidden space into an area where you can still stop.$pg$),
('c3a3c3b3-8000-4000-8000-000000000063','ar',
 $pg$عند مخرج مدرسة يركض طفل بين سيارتين متوقفتين. ماذا تفعل؟$pg$,
 $pg$["تستعمل المنبه وتحافظ على السرعة", "تنحرف فورًا إلى اليسار", "تبطئ كثيرًا وتستعد للتوقف"]$pg$::jsonb,
 $pg$قد يظهر الطفل من دون تقدير مسافتك أو سرعتك. الاستعداد على الفرامل يجعل المنطقة المحجوبة مكانًا ما زال التوقف فيه ممكنًا.$pg$),
('c3a3c3b3-8000-4000-8000-000000000064','en',
 $pg$In slow traffic, an electric scooter is coming up beside your right door. You want to move over. What do you do?$pg$,
 $pg$["Check the mirror and blind spot then wait for a clear space", "Signal and move immediately", "Move right to block its path"]$pg$::jsonb,
 $pg$This small road user can remain hidden very close to the car. The indicator announces your move, but only a direct check confirms that the side is clear.$pg$),
('c3a3c3b3-8000-4000-8000-000000000064','ar',
 $pg$في صف بطيء يتقدم سكوتر كهربائي قرب بابك الأيمن. تريد التحرك جانبًا. ماذا تفعل؟$pg$,
 $pg$["تفحص المرآة والزاوية العمياء ثم تنتظر مساحة خالية", "تشغل الإشارة وتتحرك فورًا", "تتجه يمينًا لمنع مرورها"]$pg$::jsonb,
 $pg$قد يبقى هذا المستخدم الصغير مخفيًا وهو قريب جدًا من السيارة. تعلن الإشارة حركتك لكن الفحص المباشر وحده يؤكد أن الجانب خال.$pg$),
('c3a3c3b3-8000-4000-8000-000000000065','en',
 $pg$A pedestrian crossing is hidden by a tall vehicle parked just before it. How do you approach?$pg$,
 $pg$["Only check whether the light is green", "Slow enough to stop before a hidden pedestrian", "Move into the opposing lane"]$pg$::jsonb,
 $pg$The vehicle blocks your view but not the chance that someone is crossing. Reducing speed before the crossing preserves your stopping distance.$pg$),
('c3a3c3b3-8000-4000-8000-000000000065','ar',
 $pg$تحجب مركبة عالية متوقفة قبل ممر المشاة رؤيتك له. كيف تقترب؟$pg$,
 $pg$["تنظر فقط هل الإشارة خضراء", "تبطئ بما يكفي للتوقف قبل شخص محجوب", "تنتقل إلى المسار المقابل"]$pg$::jsonb,
 $pg$تحجب المركبة رؤيتك لكنها لا تلغي احتمال عبور شخص. يحافظ خفض السرعة قبل الممر على مسافة توقفك.$pg$),
('c3a3c3b3-8000-4000-8000-000000000066','en',
 $pg$At a red light, a cycle waiting box lies beyond your stop line. Where do you stop the car?$pg$,
 $pg$["Inside the box if it is empty", "Level with any cyclists already there", "Before the first line so the box stays clear"]$pg$::jsonb,
 $pg$The box places cyclists ahead of cars so they are visible when traffic starts. Occupying it sends them back into blind spots and removes their space.$pg$),
('c3a3c3b3-8000-4000-8000-000000000066','ar',
 $pg$عند ضوء أحمر توجد منطقة انتظار للدراجات بعد خط توقفك. أين توقف السيارة؟$pg$,
 $pg$["داخل المنطقة إذا كانت فارغة", "بمحاذاة الدراجات الموجودة", "قبل الخط الأول حتى تبقى المنطقة خالية"]$pg$::jsonb,
 $pg$تضع المنطقة راكبي الدراجات أمام السيارات ليظهروا عند الانطلاق. احتلالها يعيدهم إلى الزوايا العمياء ويسلبهم مساحتهم.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000051','en',
 $pg$You are wearing sunglasses before entering a tunnel. When do you remove them?$pg$,
 $pg$["Before the entrance, with dipped headlights already on", "Halfway through the tunnel", "After the exit"]$pg$::jsonb,
 $pg$Your eyes need time to move from daylight to darkness. Preparing your vision and lighting before the entrance avoids a few almost blind seconds.$pg$),
('c3a3c3b3-8000-4000-8000-000000000051','ar',
 $pg$ترتدي نظارة شمسية قبل دخول نفق. متى تنزعها؟$pg$,
 $pg$["قبل المدخل مع تشغيل الأضواء المنخفضة مسبقًا", "في منتصف النفق", "بعد الخروج"]$pg$::jsonb,
 $pg$تحتاج عيناك إلى وقت للانتقال من ضوء النهار إلى الظلام. تجهيز الرؤية والإضاءة قبل الدخول يمنع ثواني تكاد تكون فيها بلا رؤية.$pg$),
('c3a3c3b3-8000-4000-8000-000000000052','en',
 $pg$Traffic remains stationary in a tunnel. What do you do?$pg$,
 $pg$["Move closer to the vehicle ahead", "Keep a space, switch on the hazard lights and turn off the engine", "Turn around towards the entrance"]$pg$::jsonb,
 $pg$The space ahead provides an escape route if instructions require traffic to move. Turning off the engine limits fumes in the enclosed space.$pg$),
('c3a3c3b3-8000-4000-8000-000000000052','ar',
 $pg$تبقى حركة السير متوقفة داخل نفق. ماذا تفعل؟$pg$,
 $pg$["تقترب من المركبة أمامك", "تحافظ على مسافة وتشغل أضواء التحذير وتطفئ المحرك", "تستدير نحو المدخل"]$pg$::jsonb,
 $pg$تمنحك المسافة أمامك مخرجًا إذا طلبت التعليمات التحرك. ويحد إطفاء المحرك من العوادم داخل المكان المغلق.$pg$),
('c3a3c3b3-8000-4000-8000-000000000053','en',
 $pg$Thick smoke appears ahead in a tunnel. What is your priority?$pg$,
 $pg$["Wait in the car for traffic to move", "Reverse towards the entrance", "Stop, switch off the engine and quickly reach a marked exit"]$pg$::jsonb,
 $pg$Smoke can become toxic and remove all visibility within moments. A marked exit leads to a protected space without sending you against traffic.$pg$),
('c3a3c3b3-8000-4000-8000-000000000053','ar',
 $pg$يظهر دخان كثيف أمامك داخل نفق. ما أولويتك؟$pg$,
 $pg$["تنتظر داخل السيارة حتى تتحرك المركبات", "ترجع إلى الخلف نحو المدخل", "تتوقف وتطفئ المحرك وتتجه سريعًا إلى مخرج محدد"]$pg$::jsonb,
 $pg$قد يصبح الدخان سامًا ويلغي الرؤية خلال لحظات. يقودك المخرج المحدد إلى مكان محمي من دون التحرك عكس السير.$pg$),
('c3a3c3b3-8000-4000-8000-000000000054','en',
 $pg$Your engine fails in a tunnel. Which sequence raises the alarm?$pg$,
 $pg$["Reach a place on the right if possible, use the hazard lights and call from an emergency phone", "Remain in your lane and call on your mobile", "Push the car to the exit by yourself"]$pg$::jsonb,
 $pg$The emergency phone immediately gives your position to the control room. Moving right and signalling the car first reduce the collision risk.$pg$),
('c3a3c3b3-8000-4000-8000-000000000054','ar',
 $pg$يتعطل محركك داخل نفق. أي تسلسل يطلق الإنذار؟$pg$,
 $pg$["تصل إلى مكان على اليمين إن أمكن وتشغل أضواء التحذير وتستخدم هاتف الطوارئ", "تبقى في مسارك وتتصل بهاتفك", "تدفع السيارة وحدك حتى المخرج"]$pg$::jsonb,
 $pg$يرسل هاتف الطوارئ موقعك فورًا إلى غرفة المراقبة. يقلل الانتقال إلى اليمين والإشارة إلى السيارة أولًا خطر الاصطدام.$pg$),
('c3a3c3b3-8000-4000-8000-000000000055','en',
 $pg$At roadworks, yellow lines conflict with the old white lines. Which do you follow?$pg$,
 $pg$["The white lines because they are permanent", "The yellow lines because they organise the temporary route", "Whichever marks the widest lane"]$pg$::jsonb,
 $pg$The works temporarily move traffic around the hazard and the workers. Yellow markings show the route that applies during the works.$pg$),
('c3a3c3b3-8000-4000-8000-000000000055','ar',
 $pg$في منطقة أشغال تتعارض خطوط صفراء مع الخطوط البيضاء القديمة. أيها تتبع؟$pg$,
 $pg$["البيضاء لأنها دائمة", "الصفراء لأنها تنظم المسار المؤقت", "التي تحدد المسار الأوسع"]$pg$::jsonb,
 $pg$تغير الأشغال حركة السير مؤقتًا حول الخطر والعمال. يحدد التخطيط الأصفر المسار المطبق أثناء الأشغال.$pg$),
('c3a3c3b3-8000-4000-8000-000000000056','en',
 $pg$A height restriction sign stands before a bridge and your roof box makes you unsure. What do you do?$pg$,
 $pg$["Drive through slowly to test it", "Follow a vehicle that looks just as tall", "Stop before the obstruction and check the height or change route"]$pg$::jsonb,
 $pg$The sign applies to the total height including the load. Resolve any doubt before the bridge because a strike can tear off the box and block traffic.$pg$),
('c3a3c3b3-8000-4000-8000-000000000056','ar',
 $pg$توجد علامة تحديد ارتفاع قبل جسر ويجعلك صندوق السقف غير متأكد. ماذا تفعل؟$pg$,
 $pg$["تمر ببطء لتختبر الارتفاع", "تتبع مركبة تبدو بالارتفاع نفسه", "تتوقف قبل العائق وتتحقق من الارتفاع أو تغير الطريق"]$pg$::jsonb,
 $pg$تشمل العلامة الارتفاع الكامل مع الحمولة. يحسم الشك قبل الجسر لأن الاصطدام قد ينزع الصندوق ويغلق حركة السير.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000041','en',
 $pg$You miss your motorway exit. How do you correct the route?$pg$,
 $pg$["Continue to the next exit", "Reverse along the hard shoulder", "Stop and wait for a gap"]$pg$::jsonb,
 $pg$A missed exit never justifies stopping or reversing. The next exit lets you return without surprising fast traffic.$pg$),
('c3a3c3b3-8000-4000-8000-000000000041','ar',
 $pg$تتجاوز مخرجك على الطريق السريع. كيف تصحح المسار؟$pg$,
 $pg$["تواصل حتى المخرج التالي", "ترجع إلى الخلف على مسار التوقف الطارئ", "تتوقف وتنتظر فرصة"]$pg$::jsonb,
 $pg$لا يبرر تفويت المخرج التوقف أو الرجوع إلى الخلف. يسمح لك المخرج التالي بالعودة من دون مفاجأة السير السريع.$pg$),
('c3a3c3b3-8000-4000-8000-000000000042','en',
 $pg$Your car is stranded on the hard shoulder. Where do you go after putting on your high visibility vest?$pg$,
 $pg$["In front of the car so you can be seen", "Behind the safety barrier after leaving from the passenger side", "Stay in the car to make the call calmly"]$pg$::jsonb,
 $pg$The body of the car will not protect you from a vehicle drifting onto the shoulder. Leaving away from traffic and moving behind the barrier keeps you out of the impact area.$pg$),
('c3a3c3b3-8000-4000-8000-000000000042','ar',
 $pg$تتعطل سيارتك على مسار التوقف الطارئ. أين تذهب بعد ارتداء سترة عالية الوضوح؟$pg$,
 $pg$["أمام السيارة حتى يراك الآخرون", "خلف حاجز الأمان بعد الخروج من جهة الراكب", "تبقى داخل السيارة لإجراء الاتصال بهدوء"]$pg$::jsonb,
 $pg$لن يحميك هيكل السيارة من مركبة تنحرف إلى جانب الطريق. الخروج بعيدًا عن السير والاحتماء خلف الحاجز يبعدانك عن منطقة الاصطدام.$pg$),
('c3a3c3b3-8000-4000-8000-000000000043','en',
 $pg$Your eyelids grow heavy on the motorway. Where do you stop?$pg$,
 $pg$["On the hard shoulder", "In the slow lane with the hazard lights on", "At the next service area to rest before continuing"]$pg$::jsonb,
 $pg$The hard shoulder is for absolute necessity, not a planned break. A service area takes you out of traffic and allows proper rest.$pg$),
('c3a3c3b3-8000-4000-8000-000000000043','ar',
 $pg$تشعر بثقل جفنيك على الطريق السريع. أين تتوقف؟$pg$,
 $pg$["على مسار التوقف الطارئ", "في المسار البطيء مع أضواء التحذير", "في الاستراحة التالية لترتاح قبل المتابعة"]$pg$::jsonb,
 $pg$مسار التوقف الطارئ مخصص للضرورة القصوى لا لاستراحة مخططة. تخرجك الاستراحة من حركة السير وتسمح براحة حقيقية.$pg$),
('c3a3c3b3-8000-4000-8000-000000000044','en',
 $pg$A driver follows too closely while you overtake on the motorway. Which response remains safe?$pg$,
 $pg$["Finish without exceeding the limit then return with enough space", "Brake to make your point", "Accelerate until you leave the driver behind"]$pg$::jsonb,
 $pg$Their pressure changes neither the speed limit nor the space needed to return. A predictable manoeuvre avoids adding another conflict to their dangerous behaviour.$pg$),
('c3a3c3b3-8000-4000-8000-000000000044','ar',
 $pg$يلتصق بك سائق أثناء التجاوز على الطريق السريع. أي رد يبقى آمنًا؟$pg$,
 $pg$["تنهي التجاوز بلا تخطي الحد ثم تعود بهامش كاف", "تفرمل لتلقنه درسًا", "تسرع حتى تبتعد عنه"]$pg$::jsonb,
 $pg$لا يغير ضغطه حد السرعة ولا المسافة اللازمة للعودة. تمنع المناورة المتوقعة إضافة صراع جديد إلى سلوكه الخطر.$pg$),
('c3a3c3b3-8000-4000-8000-000000000045','en',
 $pg$You approach a toll plaza and hesitate between several lanes. How do you choose?$pg$,
 $pg$["Change lane at the last moment", "Slow down early and follow the symbols for an open lane", "Stop in the middle to read every sign"]$pg$::jsonb,
 $pg$The symbols show the accepted payment and whether the lane is open. Reading them early avoids a sudden diagonal move among slowing vehicles.$pg$),
('c3a3c3b3-8000-4000-8000-000000000045','ar',
 $pg$تقترب من محطة رسوم وتتردد بين عدة مسارات. كيف تختار؟$pg$,
 $pg$["تغير المسار في اللحظة الأخيرة", "تبطئ مبكرًا وتتبع رموز مسار مفتوح", "تتوقف في الوسط لقراءة كل اللوحات"]$pg$::jsonb,
 $pg$توضح الرموز وسيلة الدفع المقبولة وحالة المسار. قراءتها مبكرًا تمنع حركة قطرية مفاجئة بين مركبات تتباطأ.$pg$),
('c3a3c3b3-8000-4000-8000-000000000046','en',
 $pg$A car is accelerating along the slip road to your right. How can you help it join without putting yourself at risk?$pg$,
 $pg$["Stop to let it in", "Change lane without checking", "Adjust your speed or move over only if the space is clear"]$pg$::jsonb,
 $pg$The vehicle already on the motorway keeps priority, but a smooth adjustment can open a gap. Any move still requires full checks.$pg$),
('c3a3c3b3-8000-4000-8000-000000000046','ar',
 $pg$تتسارع سيارة على مسار الاندماج إلى يمينك. كيف تسهل دخولها من دون تعريض نفسك للخطر؟$pg$,
 $pg$["تتوقف لتدعها تدخل", "تغير المسار بلا فحص", "تعدل سرعتك أو تنتقل فقط إذا كان المكان خاليًا"]$pg$::jsonb,
 $pg$تبقى الأولوية للمركبة الموجودة على الطريق السريع، لكن تعديلًا سلسًا قد يفتح مساحة. وكل انتقال يبقى مرتبطًا بالفحوص الكاملة.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000031','en',
 $pg$The tyre pressure warning comes on before a dual carriageway. What is your first choice?$pg$,
 $pg$["Check the tyres and their pressure before driving fast", "Accelerate to see whether the warning goes out", "Ignore it until the next service"]$pg$::jsonb,
 $pg$A tyre at the wrong pressure deforms and holds its line less well. Checking it before speed protects the grip that braking relies on.$pg$),
('c3a3c3b3-8000-4000-8000-000000000031','ar',
 $pg$يضيء تحذير ضغط الإطارات قبل طريق سريع. ما أول قرار تتخذه؟$pg$,
 $pg$["تفحص الإطارات وضغطها قبل السير بسرعة", "تسرع لترى هل ينطفئ التحذير", "تتجاهله حتى الصيانة القادمة"]$pg$::jsonb,
 $pg$يتشوه الإطار ذو الضغط غير المناسب ويثبت على المسار بدرجة أقل. فحصه قبل السرعة يحمي التماسك الذي تعتمد عليه الفرملة.$pg$),
('c3a3c3b3-8000-4000-8000-000000000032','en',
 $pg$A long descent begins with a queue ahead. Which margin do you increase?$pg$,
 $pg$["Your speed so you do not have to brake", "The distance from the vehicle ahead", "The engine speed while stationary"]$pg$::jsonb,
 $pg$The slope pushes the car and leaves less margin if the queue stops. A larger gap lets you slow early instead of braking suddenly.$pg$),
('c3a3c3b3-8000-4000-8000-000000000032','ar',
 $pg$يبدأ نزول طويل ويوجد صف من السيارات أمامك. أي هامش تزيده؟$pg$,
 $pg$["السرعة حتى لا تفرمل", "المسافة عن المركبة أمامك", "دوران المحرك أثناء التوقف"]$pg$::jsonb,
 $pg$يدفع المنحدر السيارة ويقل هامشك إذا توقف الصف. تسمح لك المسافة الأكبر بالتباطؤ مبكرًا بدل الفرملة المفاجئة.$pg$),
('c3a3c3b3-8000-4000-8000-000000000033','en',
 $pg$On black ice, can ABS make up for excessive speed?$pg$,
 $pg$["Yes, it creates grip", "Yes, if you steer at the same time", "No, it prevents wheel lock but cannot create grip"]$pg$::jsonb,
 $pg$ABS helps the wheels remain steerable, but it works with the grip available. On ice, only a very low speed preserves a real margin.$pg$),
('c3a3c3b3-8000-4000-8000-000000000033','ar',
 $pg$على الجليد الخفي، هل يستطيع نظام منع انغلاق المكابح تعويض السرعة الزائدة؟$pg$,
 $pg$["نعم، يصنع التماسك", "نعم، إذا وجهت السيارة في الوقت نفسه", "لا، يمنع انغلاق العجلات لكنه لا يصنع التماسك"]$pg$::jsonb,
 $pg$يساعد النظام على بقاء العجلات قابلة للتوجيه لكنه يعمل بالتماسك الموجود. فوق الجليد لا يحفظ هامشًا حقيقيًا إلا السير ببطء شديد.$pg$),
('c3a3c3b3-8000-4000-8000-000000000034','en',
 $pg$A bottle is rolling near the pedals before you set off. What do you do?$pg$,
 $pg$["Store it away from the footwell", "Hold it with your spare foot", "Leave it because it is light"]$pg$::jsonb,
 $pg$An object can lodge under the pedal just when you need full braking. A clear footwell guarantees the full travel of the control.$pg$),
('c3a3c3b3-8000-4000-8000-000000000034','ar',
 $pg$تتدحرج زجاجة قرب الدواسات قبل الانطلاق. ماذا تفعل؟$pg$,
 $pg$["تضعها بعيدًا عن أرضية القدمين", "تثبتها بقدمك الأخرى", "تتركها لأنها خفيفة"]$pg$::jsonb,
 $pg$قد ينحشر جسم تحت الدواسة لحظة حاجتك إلى الفرملة الكاملة. تضمن الأرضية الخالية حركة الدواسة حتى نهايتها.$pg$),
('c3a3c3b3-8000-4000-8000-000000000035','en',
 $pg$The tyre wear bars are level with the tread before a rainy journey. What do you decide?$pg$,
 $pg$["Add more pressure and leave", "Have the tyres checked or replaced before the journey", "Drive only with the lights on"]$pg$::jsonb,
 $pg$The grooves clear water from beneath the tyre. As they disappear, water clears less effectively and braking loses its reserve of grip.$pg$),
('c3a3c3b3-8000-4000-8000-000000000035','ar',
 $pg$وصلت مؤشرات تآكل الإطارات إلى مستوى النقوش قبل رحلة ممطرة. ماذا تقرر؟$pg$,
 $pg$["تزيد الضغط وتنطلق", "تفحص الإطارات أو تستبدلها قبل الرحلة", "تقود مع تشغيل الأضواء فقط"]$pg$::jsonb,
 $pg$تطرد الأخاديد الماء من تحت الإطار. عندما تختفي يقل تصريف الماء وتفقد الفرملة احتياطها من التماسك.$pg$),
('c3a3c3b3-8000-4000-8000-000000000036','en',
 $pg$After a heavily flooded section, the brake response feels unusual. What do you do?$pg$,
 $pg$["Immediately return to normal speed", "Pump the pedal quickly while accelerating", "Slow down, test gently in safety and stop if the fault remains"]$pg$::jsonb,
 $pg$Water can temporarily change contact in the brakes. A gentle test at low speed checks their response without waiting for a real emergency.$pg$),
('c3a3c3b3-8000-4000-8000-000000000036','ar',
 $pg$بعد مقطع مغمور جدًا بالماء تبدو استجابة الفرامل غير طبيعية. ماذا تفعل؟$pg$,
 $pg$["تعود فورًا إلى السرعة العادية", "تضغط الدواسة مرات سريعة مع التسارع", "تبطئ وتختبرها بلطف في أمان وتتوقف إذا بقي الخلل"]$pg$::jsonb,
 $pg$قد يغير الماء تلامس أجزاء الفرامل مؤقتًا. يختبر الضغط اللطيف عند سرعة منخفضة استجابتها من دون انتظار حالة طارئة حقيقية.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000021','en',
 $pg$The first drops fall after several dry days. How do you approach the next roundabout?$pg$,
 $pg$["Slow down beforehand and keep every input smooth", "Brake hard once you are on it", "Keep your speed because the road looks clean"]$pg$::jsonb,
 $pg$Early rain mixes water with dust and residue on the road. Planning before the bend avoids demanding too much grip from the tyres.$pg$),
('c3a3c3b3-8000-4000-8000-000000000021','ar',
 $pg$تسقط أول قطرات المطر بعد عدة أيام جافة. كيف تقترب من الدوار التالي؟$pg$,
 $pg$["تبطئ قبله وتحافظ على حركات سلسة", "تفرمل بقوة بعد دخوله", "تحافظ على السرعة لأن الطريق يبدو نظيفًا"]$pg$::jsonb,
 $pg$يمتزج المطر في بدايته بالغبار والرواسب على الطريق. الاستعداد قبل المنعطف يمنع طلب تماسك يفوق قدرة الإطارات.$pg$),
('c3a3c3b3-8000-4000-8000-000000000022','en',
 $pg$In a large puddle, the steering suddenly feels very light. What is your first move?$pg$,
 $pg$["Brake as hard as possible", "Ease off the accelerator and hold the wheel steady", "Steer quickly towards the edge"]$pg$::jsonb,
 $pg$The tyres may ride on the water and stop guiding the car. Easing off without braking or jerking the wheel lets them regain contact.$pg$),
('c3a3c3b3-8000-4000-8000-000000000022','ar',
 $pg$داخل بركة كبيرة يصبح المقود خفيفًا فجأة. ما أول حركة تقوم بها؟$pg$,
 $pg$["تفرمل بكل قوتك", "ترفع قدمك تدريجيًا عن الوقود وتثبت المقود", "تدير المقود بسرعة نحو الحافة"]$pg$::jsonb,
 $pg$قد تطفو الإطارات فوق الماء فتتوقف عن توجيه السيارة. رفع القدم بلا فرملة أو حركة مفاجئة للمقود يسمح لها باستعادة ملامسة الطريق.$pg$),
('c3a3c3b3-8000-4000-8000-000000000023','en',
 $pg$You must cross wet painted arrows on a bend. Which action do you avoid on them?$pg$,
 $pg$["Looking through the bend", "Holding the wheel with both hands", "Braking or steering sharply"]$pg$::jsonb,
 $pg$Wet paint offers less grip than tarmac. Setting your speed beforehand and steering smoothly preserve the little grip available.$pg$),
('c3a3c3b3-8000-4000-8000-000000000023','ar',
 $pg$يجب أن تمر فوق أسهم مطلية ومبتلة داخل منعطف. أي حركة تتجنبها فوقها؟$pg$,
 $pg$["النظر إلى مخرج المنعطف", "إمساك المقود بكلتا اليدين", "الفرملة أو التوجيه بعنف"]$pg$::jsonb,
 $pg$يكون تماسك الطلاء المبتل أقل من الإسفلت. تحديد السرعة مسبقًا والتوجيه بسلاسة يحافظان على التماسك القليل المتاح.$pg$),
('c3a3c3b3-8000-4000-8000-000000000024','en',
 $pg$A snowy descent starts ahead. What do you set before the slope?$pg$,
 $pg$["A low speed and a large space ahead", "A high speed so you do not get stuck", "Continuous braking for the whole descent"]$pg$::jsonb,
 $pg$Gravity pushes the car downhill while the tyres have little grip. Prepare your margin beforehand with distance and smooth controls.$pg$),
('c3a3c3b3-8000-4000-8000-000000000024','ar',
 $pg$يبدأ أمامك نزول مغطى بالثلج. ماذا تضبط قبل المنحدر؟$pg$,
 $pg$["سرعة منخفضة ومسافة كبيرة أمامك", "سرعة عالية حتى لا تعلق", "فرملة متواصلة طوال النزول"]$pg$::jsonb,
 $pg$تدفع الجاذبية السيارة بينما تملك الإطارات تماسكًا قليلًا. جهز هامشك قبل النزول بالمسافة والحركات التدريجية.$pg$),
('c3a3c3b3-8000-4000-8000-000000000025','en',
 $pg$Loose gravel covers the entrance to a bend. How do you cross it?$pg$,
 $pg$["Brake hard just before each patch", "Slow down beforehand then hold a steady line", "Cut the bend to avoid it"]$pg$::jsonb,
 $pg$Gravel rolls beneath the tyre like tiny balls. Reducing speed before it avoids having to brake or make a large correction on top of it.$pg$),
('c3a3c3b3-8000-4000-8000-000000000025','ar',
 $pg$يغطي الحصى مدخل منعطف. كيف تعبر المنطقة؟$pg$,
 $pg$["تفرمل بقوة قبل كل جزء من الحصى", "تبطئ مسبقًا ثم تحافظ على مسار ثابت", "تقطع المنعطف لتتفاداه"]$pg$::jsonb,
 $pg$يتدحرج الحصى تحت الإطار مثل كرات صغيرة. خفض السرعة قبله يمنع الحاجة إلى الفرملة أو التصحيح القوي فوقه.$pg$),
('c3a3c3b3-8000-4000-8000-000000000026','en',
 $pg$A deep puddle reaches only the right wheels. How do you limit the car being pulled sideways?$pg$,
 $pg$["Let go of the wheel so it can return", "Jerk the wheel to the left", "Slow down beforehand and hold the wheel without a sudden input"]$pg$::jsonb,
 $pg$The water slows one side more and may pull the car. Steady hands hold the line while a low speed reduces the force of the pull.$pg$),
('c3a3c3b3-8000-4000-8000-000000000026','ar',
 $pg$تصل بركة عميقة إلى العجلتين اليمنيين فقط. كيف تحد من انحراف السيارة؟$pg$,
 $pg$["تترك المقود ليعود وحده", "تدير المقود فجأة إلى اليسار", "تبطئ قبلها وتمسك المقود بلا حركة مفاجئة"]$pg$::jsonb,
 $pg$يبطئ الماء جانبًا أكثر من الآخر وقد يجذب السيارة. تثبت اليدان المسار وتقلل السرعة المنخفضة قوة الانحراف.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation)
values
('c3a3c3b3-8000-4000-8000-000000000011','en',
 $pg$You enter a bank of fog. Which lights avoid creating a bright wall in front of you?$pg$,
 $pg$["Dipped headlights", "Main beam headlights", "Position lights only"]$pg$::jsonb,
 $pg$Main beam reflects off the droplets and reduces your view further. Dipped headlights aim lower and make you visible.$pg$),
('c3a3c3b3-8000-4000-8000-000000000011','ar',
 $pg$تدخل كتلة من الضباب. أي أضواء تمنع تكوين جدار مضيء أمامك؟$pg$,
 $pg$["الأضواء المنخفضة", "الأضواء العالية", "أضواء الموضع فقط"]$pg$::jsonb,
 $pg$تنعكس الأضواء العالية على قطرات الضباب فتقلل الرؤية أكثر. تتجه الأضواء المنخفضة إلى أسفل وتجعلك مرئيًا.$pg$),
('c3a3c3b3-8000-4000-8000-000000000012','en',
 $pg$The fog clears and a car is driving behind you. What do you do with the rear fog light?$pg$,
 $pg$["You keep it on until the end of the journey", "You switch it off as soon as it is no longer needed", "You replace it with the hazard lights"]$pg$::jsonb,
 $pg$This very bright light helps others spot you in fog or snow. Once visibility returns, it needlessly dazzles the driver behind.$pg$),
('c3a3c3b3-8000-4000-8000-000000000012','ar',
 $pg$ينقشع الضباب وتسير سيارة خلفك. ماذا تفعل بضوء الضباب الخلفي؟$pg$,
 $pg$["تبقيه حتى نهاية الرحلة", "تطفئه فور زوال الحاجة إليه", "تستبدله بأضواء التحذير"]$pg$::jsonb,
 $pg$يساعد هذا الضوء القوي الآخرين على رؤيتك في الضباب أو الثلج. عندما تتحسن الرؤية فإنه يبهر السائق خلفك بلا داع.$pg$),
('c3a3c3b3-8000-4000-8000-000000000013','en',
 $pg$Heavy rain overwhelms your wipers. What decision do you make?$pg$,
 $pg$["You follow the lights ahead closely", "You keep your speed to leave the downpour quickly", "You slow down smoothly and stop somewhere safe if the view remains inadequate"]$pg$::jsonb,
 $pg$When the wipers can no longer restore a usable view, speed must fall with visibility. A safe stop is better than guessing your path.$pg$),
('c3a3c3b3-8000-4000-8000-000000000013','ar',
 $pg$يتجاوز المطر الغزير قدرة ماسحات الزجاج. ما القرار الذي تتخذه؟$pg$,
 $pg$["تتبع أضواء السيارة أمامك عن قرب", "تحافظ على السرعة للخروج سريعًا من المطر", "تبطئ بسلاسة وتتوقف في مكان آمن إذا بقيت الرؤية غير كافية"]$pg$::jsonb,
 $pg$عندما لا تعيد الماسحات رؤية صالحة للقيادة، يجب أن تنخفض السرعة مع الرؤية. التوقف الآمن أفضل من تخمين المسار.$pg$),
('c3a3c3b3-8000-4000-8000-000000000014','en',
 $pg$Spray from a lorry hides your windscreen before an overtake. How do you regain visibility?$pg$,
 $pg$["First increase the gap and adjust the wipers", "Move closer to shorten the overtake", "Move out before you can see again"]$pg$::jsonb,
 $pg$Further behind the lorry, the water cloud is thinner and your field of view opens up. Start the overtake only when the road is clear to read again.$pg$),
('c3a3c3b3-8000-4000-8000-000000000014','ar',
 $pg$يحجب رذاذ شاحنة زجاجك الأمامي قبل التجاوز. كيف تستعيد الرؤية؟$pg$,
 $pg$["تزيد المسافة أولًا وتضبط الماسحات", "تقترب لتقصير وقت التجاوز", "تخرج للتجاوز قبل أن ترى من جديد"]$pg$::jsonb,
 $pg$يكون رذاذ الماء أخف كلما ابتعدت عن الشاحنة ويتسع مجال رؤيتك. لا تبدأ التجاوز حتى يصبح الطريق واضحًا من جديد.$pg$),
('c3a3c3b3-8000-4000-8000-000000000015','en',
 $pg$Low sun almost hides a traffic light and the people ahead. How do you create a safety margin?$pg$,
 $pg$["You use the car ahead as your guide", "You use the sun visor and slow down until the road is clear", "You switch on main beam"]$pg$::jsonb,
 $pg$The visor blocks the direct light but does not instantly restore every detail. Slowing down gives you time to identify a signal, a pedestrian or a queue.$pg$),
('c3a3c3b3-8000-4000-8000-000000000015','ar',
 $pg$تكاد الشمس المنخفضة تخفي إشارة المرور والأشخاص أمامك. كيف تصنع هامش أمان؟$pg$,
 $pg$["تتبع السيارة أمامك", "تستخدم حاجب الشمس وتبطئ حتى ترى الطريق بوضوح", "تشغل الأضواء العالية"]$pg$::jsonb,
 $pg$يحجب الحاجب الضوء المباشر لكنه لا يعيد كل التفاصيل فورًا. يمنحك التباطؤ وقتًا لتمييز إشارة أو مشاة أو صف متوقف.$pg$),
('c3a3c3b3-8000-4000-8000-000000000016','en',
 $pg$In fog, the car you were following disappears into the distance. How do you choose your speed?$pg$,
 $pg$["You accelerate to find its lights", "You keep its last known speed", "You rely on your own visible distance and keep a large gap"]$pg$::jsonb,
 $pg$Another vehicle's lights do not prove that the space between you is clear. Only your visibility and ability to stop should determine your speed.$pg$),
('c3a3c3b3-8000-4000-8000-000000000016','ar',
 $pg$في الضباب تختفي السيارة التي كنت تتبعها بعيدًا. كيف تختار سرعتك؟$pg$,
 $pg$["تسرع للعثور على أضوائها", "تحافظ على آخر سرعة عرفت أنها تسير بها", "تعتمد على مسافة رؤيتك أنت وتحافظ على فارق كبير"]$pg$::jsonb,
 $pg$لا تثبت أضواء سيارة أخرى أن المسافة بينكما خالية. رؤيتك وقدرتك على التوقف هما وحدهما ما يحدد سرعتك.$pg$)
on conflict (question_id, lang) do nothing;
