-- Banque de certification, lot 2.
-- C2a à C2h passent de 6 à 12 questions jouables pour chaque boîte.
-- Les 48 questions ajoutées portent sur des gestes communs aux deux boîtes.

insert into public.questions_competence
  (id, competence_id, question, options, correct_index, explanation, difficulty, type, boite)
values
('c2a2c2b2-8000-4000-8000-000000000001','C2a',
 $pg$Un bus arrêté te cache une partie du trottoir. Que cherches-tu avant de le longer ?$pg$,
 $pg$["Des pieds ou une silhouette qui pourraient surgir devant le bus", "Seulement le clignotant du bus pour savoir s'il va repartir", "Uniquement la chaussée loin devant pour anticiper le trafic"]$pg$::jsonb,
 0,
 $pg$Un piéton masqué apparaît d'abord par petits indices sous ou autour du véhicule. Lever le pied dès ces indices te rend du temps pour t'arrêter.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000002','C2a',
 $pg$Une voiture garée a ses roues tournées et quelqu'un est au volant. Quelle information en tires-tu ?$pg$,
 $pg$["Elle restera forcément immobile puisque ses feux sont éteints", "Elle peut quitter sa place, tu prépares ta réaction", "Elle va ouvrir son coffre pour sortir quelque chose"]$pg$::jsonb,
 1,
 $pg$Les roues et la présence du conducteur annoncent un mouvement possible avant même le clignotant. Tu gardes une marge et surveilles la portière.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000003','C2a',
 $pg$Le feu est vert mais plusieurs feux stop s'allument loin devant. Quelle information compte le plus ?$pg$,
 $pg$["Le feu vert garantit que tout le monde continuera d'avancer", "Les voitures proches de toi suffisent pour décider", "Le ralentissement se propage, tu lèves le pied tôt"]$pg$::jsonb,
 2,
 $pg$Le feu autorise le passage, il ne garantit pas un trafic fluide. Lire les feux stop loin devant évite de découvrir la file au dernier moment.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000004','C2a',
 $pg$Tu vas ralentir fortement. Pourquoi jeter un regard au rétroviseur intérieur avant ?$pg$,
 $pg$["Pour savoir qui te suit et annoncer ton ralentissement assez tôt", "Pour remplacer le contrôle de ce qui se passe devant pendant ton freinage", "Pour vérifier seulement la voie de gauche avant de ralentir"]$pg$::jsonb,
 0,
 $pg$Voir un véhicule très proche derrière ne supprime pas ton freinage, mais t'incite à agir tôt et progressivement pour lui laisser le temps de réagir.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000005','C2a',
 $pg$Des branches cachent une partie d'un panneau. Comment évites-tu de deviner sa consigne ?$pg$,
 $pg$["Tu copies la vitesse de la voiture devant en supposant qu'elle a compris", "Tu ralentis et croises sa forme avec le marquage et la situation", "Tu l'ignores car il est mal visible et tu gardes ton allure"]$pg$::jsonb,
 1,
 $pg$La forme, le marquage au sol et l'organisation de la route donnent des indices concordants. Ralentir te laisse le temps de confirmer avant d'agir.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000006','C2a',
 $pg$Une camionnette masque la droite d'une intersection. Comment récupères-tu l'information manquante ?$pg$,
 $pg$["Tu t'engages vite pour voir avant qu'un autre véhicule n'arrive", "Tu regardes seulement à gauche car c'est le côté le plus proche", "Tu ralentis, avances par petites étapes et bouges la tête pour voir autour"]$pg$::jsonb,
 2,
 $pg$Quand la vue est coupée, ta position doit changer sans exposer toute la voiture. Chaque petite avancée ouvre un nouvel angle de vision.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000011','C2b',
 $pg$Le soleil rasant t'éblouit et tu distingues mal le passage piéton. Ton geste ?$pg$,
 $pg$["Tu ralentis jusqu'à retrouver une vision sûre", "Tu gardes l'allure car le feu est vert", "Tu suis les feux de la voiture devant"]$pg$::jsonb,
 0,
 $pg$Une zone que tu ne vois pas est une zone où tu ne peux pas garantir l'arrêt. Réduire l'allure transforme la distance visible en distance utile.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000012','C2b',
 $pg$Tu suis une grande camionnette qui te cache toute la route. Comment retrouves-tu de l'anticipation ?$pg$,
 $pg$["Tu te rapproches pour voir sur le côté malgré la faible distance", "Tu augmentes l'écart pour voir plus loin autour d'elle", "Tu roules sur la gauche de ta voie pour dégager ton regard"]$pg$::jsonb,
 1,
 $pg$Plus tu recules, plus ton champ de vision s'ouvre autour du véhicule haut. Cette marge ajoute aussi du temps s'il freine brusquement.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000013','C2b',
 $pg$Des feuilles mouillées couvrent l'entrée d'un virage. Quand adaptes-tu ton allure ?$pg$,
 $pg$["Après avoir senti la voiture glisser sous tes roues", "Au milieu du virage en freinant légèrement", "Avant les feuilles, avec des gestes doux"]$pg$::jsonb,
 2,
 $pg$Les feuilles mouillées réduisent l'adhérence comme une pellicule glissante. Ralentir avant permet de traverser la zone sans frein ni volant brusque.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000014','C2b',
 $pg$La chaussée se rétrécit et un véhicule arrive en face. Ton premier geste ?$pg$,
 $pg$["Tu ralentis avant le passage étroit et évalues qui peut passer", "Tu accélères pour arriver le premier et imposer ton passage", "Tu gardes la même allure jusqu'au face-à-face puis tu décides"]$pg$::jsonb,
 0,
 $pg$Décider avant l'étranglement évite de devoir freiner nez à nez. À faible allure, chacun peut ajuster sa place ou s'arrêter sans surprise.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000015','C2b',
 $pg$Un marché longe la rue et des piétons regardent les stands plutôt que la circulation. Quelle allure choisis-tu ?$pg$,
 $pg$["La limitation exacte sans ralentir puisque la voie reste ouverte", "Une allure qui te permet de t'arrêter dès qu'un piéton bouge", "La même allure que la voiture derrière pour ne pas la gêner"]$pg$::jsonb,
 1,
 $pg$L'attention des piétons est tournée ailleurs, donc leur trajectoire peut changer sans regard. Ton allure doit absorber cette surprise.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000016','C2b',
 $pg$La file accélère puis freine tous les quelques mètres. Comment éviter la conduite en accordéon ?$pg$,
 $pg$["Tu colles pour ne laisser entrer personne", "Tu reproduis chaque accélération immédiatement", "Tu gardes plus d'espace et une allure régulière"]$pg$::jsonb,
 2,
 $pg$L'espace devant absorbe les petites variations de la file. Tu peux souvent laisser rouler la voiture sans alterner accélérations et freinages.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000021','C2c',
 $pg$Le marquage de ta voie est presque effacé. Comment gardes-tu une trajectoire stable ?$pg$,
 $pg$["Tu regardes loin et utilises les deux bords de la chaussée", "Tu fixes le bord droit juste devant le capot pour guider la voiture", "Tu suis exactement la voiture devant pour copier toute sa trajectoire"]$pg$::jsonb,
 0,
 $pg$Des repères éloignés lissent ta trajectoire même quand une ligne disparaît. Les deux bords t'aident à reconstruire le centre de ton espace.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000022','C2c',
 $pg$Des voitures sont garées des deux côtés d'une rue étroite. Où places-tu la tienne ?$pg$,
 $pg$["Tout contre les voitures de droite", "Au centre de l'espace libre, à faible allure", "Tout contre les voitures de gauche"]$pg$::jsonb,
 1,
 $pg$Le centre de l'espace disponible garde une marge des deux côtés. La faible allure te permet de t'arrêter si une portière s'ouvre.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000023','C2c',
 $pg$Un camion arrive en face sur une route étroite. Comment te places-tu ?$pg$,
 $pg$["Tu plonges dans le bas-côté pour laisser toute la chaussée au camion", "Tu gardes le milieu pour obliger le camion à ralentir avant toi", "Tu ralentis et gardes une marge sûre à droite sans quitter la chaussée"]$pg$::jsonb,
 2,
 $pg$Ralentir réduit l'espace dont chaque véhicule a besoin. Le bord reste une limite à surveiller, pas un endroit où envoyer les roues par peur.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000024','C2c',
 $pg$Un trou profond occupe le bord droit de ta voie. Comment l'évites-tu ?$pg$,
 $pg$["Tu contrôles derrière et en face avant de t'écarter légèrement", "Tu donnes un coup de volant sans regarder pour éviter le trou au dernier moment", "Tu serres encore à droite pour passer doucement dans le trou"]$pg$::jsonb,
 0,
 $pg$Éviter un défaut de chaussée reste un changement de trajectoire. Les contrôles confirment que l'espace voisin est libre avant ton déplacement.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000025','C2c',
 $pg$Dans un virage à gauche, ta roue avant gauche approche la ligne centrale. Que corriges-tu ?$pg$,
 $pg$["Tu coupes davantage le virage pour éloigner ta roue de la ligne", "Tu restes dans ta voie et ajustes doucement ta trajectoire", "Tu accélères pour sortir plus vite et retrouver ta position ensuite"]$pg$::jsonb,
 1,
 $pg$Couper le virage expose l'avant de ta voiture à celui qui arrive en face. Une correction douce garde toute la voiture dans son couloir.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000026','C2c',
 $pg$Après un dépassement, la voie de droite est libre sur une longue distance. Où roules-tu ?$pg$,
 $pg$["Tu restes à gauche pour conserver une meilleure vue sur la route", "Tu te rabats dès que ton pare-chocs dépasse le véhicule doublé", "Tu reviens à droite après contrôles et avec une marge suffisante"]$pg$::jsonb,
 2,
 $pg$La voie de gauche sert au dépassement. Revenir à droite libère la circulation, mais seulement quand tu ne coupes pas la route du véhicule dépassé.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000031','C2d',
 $pg$Tu approches d'un virage sans voir ce qu'il y a derrière. Quelle vitesse d'entrée ?$pg$,
 $pg$["Une vitesse qui te permet de t'arrêter dans la partie visible", "La limitation maximale affichée même si la sortie reste cachée", "La vitesse de la voiture qui te suit pour ne pas la ralentir"]$pg$::jsonb,
 0,
 $pg$La sortie cachée peut contenir un bouchon, un vélo ou un obstacle. Ta distance d'arrêt doit tenir dans la route que tes yeux voient vraiment.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000032','C2d',
 $pg$La route est mouillée avant un virage. Que changes-tu ?$pg$,
 $pg$["Tu freines une fois dans la courbe pour ajuster ta vitesse exacte", "Tu ralentis davantage avant et tournes sans geste brusque", "Tu prends plus d'élan avant la courbe pour éviter de glisser"]$pg$::jsonb,
 1,
 $pg$Moins d'adhérence laisse moins de place aux corrections. Une vitesse réglée en ligne droite permet aux pneus de se consacrer à tourner.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000033','C2d',
 $pg$Le virage se resserre plus que prévu. Comment réagis-tu ?$pg$,
 $pg$["Tu fixes le bord extérieur pour mesurer précisément le virage", "Tu freines et braques d'un coup pour revenir immédiatement dans l'axe", "Tu lèves le pied, regardes la sortie et augmentes doucement le braquage"]$pg$::jsonb,
 2,
 $pg$Le regard donne la direction et le pied levé évite d'élargir encore la trajectoire. Un geste progressif conserve l'adhérence disponible.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000034','C2d',
 $pg$Deux virages s'enchaînent en sens opposés. Où se déplace ton regard ?$pg$,
 $pg$["Vers la sortie du premier puis vers celle du second", "Sur la ligne entre les deux pour garder un repère fixe", "Dans le rétroviseur pendant tout l'enchaînement des virages"]$pg$::jsonb,
 0,
 $pg$Chaque sortie devient l'entrée visuelle du virage suivant. Déplacer le regard à temps évite de finir le premier virage en retard.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000035','C2d',
 $pg$Une voiture en face mord légèrement ta voie dans un virage. Ton geste ?$pg$,
 $pg$["Tu maintiens l'allure pour défendre ta place et montrer ta trajectoire", "Tu lèves le pied, gardes une marge à droite et te prépares à t'arrêter", "Tu fixes ses phares pour surveiller précisément chacun de ses mouvements"]$pg$::jsonb,
 1,
 $pg$Réduire la vitesse crée du temps et diminue la largeur nécessaire au croisement. Regarder ton espace libre t'aide à y conduire la voiture.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000036','C2d',
 $pg$Tu suis un camion qui te cache toute la sortie d'un virage. Comment abordes-tu la courbe ?$pg$,
 $pg$["Tu le suis de près pour copier sa trajectoire et son allure dans la courbe", "Tu te décales sur la ligne centrale pour voir autour de sa cabine", "Tu augmentes l'écart et choisis ta vitesse avec ta propre visibilité"]$pg$::jsonb,
 2,
 $pg$Le camion peut passer au-dessus d'un obstacle que tu ne peux pas éviter. Une marge plus grande te rend une vue et une distance d'arrêt personnelles.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000041','C2e',
 $pg$Une voiture arrive en face alors qu'un véhicule garé bloque ton côté. Qui facilite le croisement ?$pg$,
 $pg$["Tu ralentis et laisses passer avant de contourner l'obstacle", "L'autre doit toujours reculer pour te laisser contourner", "Tu contournes vite pour finir avant son arrivée"]$pg$::jsonb,
 0,
 $pg$L'obstacle t'oblige à quitter ta trajectoire normale. Attendre avant de le contourner évite de transformer le croisement en face-à-face.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000042','C2e',
 $pg$Tu prépares un dépassement et le véhicule devant met son clignotant à gauche. Que fais-tu ?$pg$,
 $pg$["Tu dépasses avant qu'il tourne", "Tu renonces et gardes ta distance", "Tu klaxonnes pour réserver ta place"]$pg$::jsonb,
 1,
 $pg$Son clignotant annonce une trajectoire qui peut couper la tienne. Renoncer enlève le conflit au lieu de parier sur le moment où il tournera.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000043','C2e',
 $pg$Après le véhicule lent, aucune place ne permet de te rabattre dans la file. Tu dépasses ?$pg$,
 $pg$["Oui, la file te laissera forcément entrer au moment du retour", "Oui, si tu accélères assez pour revenir avant le véhicule en face", "Non, tu attends d'avoir une place de retour visible"]$pg$::jsonb,
 2,
 $pg$Un dépassement se décide avec sa sortie déjà prévue. Sans espace pour revenir, tu risques de rester dans la voie d'en face.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000044','C2e',
 $pg$Le conducteur que tu dépasses accélère soudain. Comment réagis-tu ?$pg$,
 $pg$["Tu abandonnes et te replaces derrière dès que c'est sûr", "Tu dépasses la limitation pour gagner le duel avant son accélération", "Tu restes à sa hauteur jusqu'à ce qu'il ralentisse de lui-même"]$pg$::jsonb,
 0,
 $pg$Un duel de vitesse prolonge le temps passé à gauche. Renoncer tôt rend de l'espace et remet chaque véhicule dans sa voie.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000045','C2e',
 $pg$Tu dépasses un cavalier sur une route de campagne. Quelle approche ?$pg$,
 $pg$["Tu klaxonnes longtemps pour prévenir le cavalier avant de passer", "Tu ralentis et laisses un large écart sans bruit brusque", "Tu passes vite au plus près pour rester moins longtemps à côté"]$pg$::jsonb,
 1,
 $pg$Un cheval peut réagir au bruit et faire un écart soudain. La faible allure et la distance protègent le cavalier même si l'animal bouge.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000046','C2e',
 $pg$Un cycliste devant toi contourne des trous et sa trajectoire bouge. Quand le dépasses-tu ?$pg$,
 $pg$["Dès qu'il revient une fois à droite après avoir évité un trou", "En le frôlant pour réduire le temps passé sur la voie opposée", "Quand tu peux prévoir son écart et laisser une vraie marge latérale"]$pg$::jsonb,
 2,
 $pg$Le cycliste choisit parfois entre un trou et un écart. Attendre une zone large évite de lui retirer cette seule porte de sortie.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000051','C2f',
 $pg$Au STOP, la ligne est trop loin pour voir la route transversale. Comment procèdes-tu ?$pg$,
 $pg$["Tu marques l'arrêt à la ligne puis avances lentement pour observer", "Tu dépasses la ligne sans t'arrêter afin de voir la route transversale", "Tu t'arrêtes seulement après être engagé dans le carrefour"]$pg$::jsonb,
 0,
 $pg$Le premier arrêt respecte la limite. L'avancée suivante sert uniquement à gagner de la vue, en restant prêt à céder le passage.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000052','C2f',
 $pg$Tu tournes à gauche au feu vert et une voiture arrive en face tout droit. Qui passe ?$pg$,
 $pg$["Toi, car ton clignotant annonce déjà ton passage vers la gauche", "La voiture d'en face passe, tu attends une ouverture sûre", "Celui qui accélère le premier pour occuper le carrefour"]$pg$::jsonb,
 1,
 $pg$Tourner à gauche coupe la trajectoire du véhicule opposé. Le feu vert vous autorise tous les deux à avancer, il ne te donne pas la priorité sur lui.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000053','C2f',
 $pg$Tu tournes à droite en coupant une piste cyclable. Un vélo continue tout droit à ta droite. Ton geste ?$pg$,
 $pg$["Tu tournes avant qu'il arrive pour libérer rapidement la piste", "Tu serres la piste pour obliger le cycliste à ralentir derrière toi", "Tu contrôles soigneusement l'angle mort et le laisses passer"]$pg$::jsonb,
 2,
 $pg$Ta trajectoire traverse la sienne. Le vélo peut être caché dans l'angle mort jusqu'au dernier moment, donc tu cèdes avant de couper la piste.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000054','C2f',
 $pg$Les feux d'une intersection sont éteints. Comment décides-tu ?$pg$,
 $pg$["Tu ralentis et appliques les panneaux, sinon la priorité à droite", "Tu passes car personne n'a de feu vert et le carrefour devient libre", "Tu suis la voiture devant sans contrôler les autres directions"]$pg$::jsonb,
 0,
 $pg$Un feu hors service ne supprime pas les règles du carrefour. La signalisation présente reprend son rôle. Sans panneau, c'est la priorité à droite qui décide.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000055','C2f',
 $pg$Le feu passe à l'orange fixe alors que tu peux t'arrêter sans danger. Que fais-tu ?$pg$,
 $pg$["Tu accélères avant le rouge pour franchir la ligne sans attendre", "Tu t'arrêtes avant la ligne puisque tu peux le faire sans danger", "Tu continues à la même vitesse car le rouge n'est pas encore allumé"]$pg$::jsonb,
 1,
 $pg$L'orange fixe annonce l'arrêt. L'exception sert seulement quand freiner créerait un danger, pas quand quelques secondes peuvent être gagnées.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000056','C2f',
 $pg$Une voiture de police arrive avec ses feux bleus et sa sirène pendant que ton feu est vert. Ton geste ?$pg$,
 $pg$["Tu gardes ton passage grâce au vert et poursuis dans le carrefour", "Tu t'arrêtes immédiatement même si tu bloques complètement sa voie", "Tu facilites son passage sans créer un nouveau danger"]$pg$::jsonb,
 2,
 $pg$Le vert ne doit pas t'envoyer sur la trajectoire du véhicule prioritaire. Tu observes d'où il vient et libères un passage de façon prévisible.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000061','C2g',
 $pg$Tu as mis ton clignotant pour changer de voie. Les autres doivent-ils te laisser passer ?$pg$,
 $pg$["Non, tu attends toujours un espace réellement libre", "Oui, le clignotant donne la priorité dès qu'il est allumé", "Oui, après trois secondes même si la voie reste occupée"]$pg$::jsonb,
 0,
 $pg$Le clignotant annonce une intention, il ne réserve pas une place. Le changement commence seulement quand tes contrôles confirment une marge sûre.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000062','C2g',
 $pg$La voiture devant garde son clignotant à gauche depuis longtemps mais continue tout droit. Tu dépasses ?$pg$,
 $pg$["Oui, son clignotant ne compte plus puisqu'il semble oublié", "Non, tu attends que sa trajectoire soit claire", "Oui, par la gauche rapidement avant que la voiture ne tourne"]$pg$::jsonb,
 1,
 $pg$Un signal oublié reste une information incertaine. Attendre le mouvement réel évite de te placer du côté où la voiture peut finalement tourner.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000063','C2g',
 $pg$Une file arrêtée apparaît soudain devant toi sur voie rapide. Comment avertis-tu derrière ?$pg$,
 $pg$["Tu klaxonnes sans arrêter pour prévenir toute la file devant toi", "Tu fais des appels de phare vers l'avant pour demander un passage", "Tu freines et allumes les feux de détresse le temps d'être repéré"]$pg$::jsonb,
 2,
 $pg$Les feux de détresse signalent un ralentissement inhabituel à ceux qui arrivent vite. Tu peux les couper quand la file derrière a compris et ralenti.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000064','C2g',
 $pg$À côté d'un camion, tu ne vois pas le visage du conducteur dans son rétroviseur. Qu'en déduis-tu ?$pg$,
 $pg$["Il ne te voit probablement pas, tu quittes son angle mort", "Il te voit grâce à ses capteurs même loin de ses rétroviseurs", "Il va forcément rester droit tant que son clignotant reste éteint"]$pg$::jsonb,
 0,
 $pg$Si tu ne peux pas voir le conducteur ou son miroir, rien ne confirme qu'il connaît ta présence. Rester en retrait évite sa zone de changement de voie.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000065','C2g',
 $pg$Un conducteur te fait signe de traverser devant lui. Que vérifies-tu encore ?$pg$,
 $pg$["Rien, son geste remplace les règles de priorité pour tout le carrefour", "Les autres voies, les vélos et les piétons avant d'avancer", "Seulement son clignotant pour confirmer qu'il restera immobile"]$pg$::jsonb,
 1,
 $pg$Son geste parle seulement de sa propre voiture. Un autre usager peut continuer à côté de lui sans avoir vu votre échange.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000066','C2g',
 $pg$Un cycliste regarde derrière lui puis tend le bras gauche. Quelle information te donne-t-il ?$pg$,
 $pg$["Il t'invite à le dépasser immédiatement avant son changement de direction", "Il te montre seulement un danger sur la gauche de la chaussée", "Il peut se déporter à gauche devant toi, tu ralentis et attends"]$pg$::jsonb,
 2,
 $pg$Le regard et le bras annoncent une intention de changer de direction. Lire ce message avant le mouvement évite de commencer un dépassement conflictuel.$pg$,
 3,'post_validation',null),

('c2a2c2b2-8000-4000-8000-000000000071','C2h',
 $pg$Le GPS te demande de tourner dans une rue interdite. Quelle consigne suis-tu ?$pg$,
 $pg$["La signalisation, puis tu laisses le GPS recalculer", "Le GPS, car il connaît ton trajet mieux que les panneaux présents", "Le passager qui paraît le plus sûr de lui sur cette route"]$pg$::jsonb,
 0,
 $pg$L'écran propose un itinéraire, la signalisation commande la circulation réelle. Continuer légalement permet au guidage de construire une autre route.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000072','C2h',
 $pg$Ton passager dit « vas-y » mais un véhicule te masque la vue. Que fais-tu ?$pg$,
 $pg$["Tu pars car il regarde pour toi et te préviendra du moindre danger", "Tu attends d'avoir ta propre visibilité avant de prendre la décision", "Tu avances très lentement en suivant seulement ses consignes"]$pg$::jsonb,
 1,
 $pg$C'est toi qui commandes la voiture et assumes la décision. Une information extérieure peut aider, mais elle ne remplace jamais ce que tu dois voir.$pg$,
 1,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000073','C2h',
 $pg$Une voiture de police avec sa sirène se rapproche derrière toi dans une rue chargée. Comment facilites-tu le passage ?$pg$,
 $pg$["Tu montes immédiatement sur le trottoir sans vérifier les usagers présents", "Tu accélères jusqu'au prochain feu rouge pour libérer la rue derrière toi", "Tu contrôles, ralentis et libères un espace sûr sans geste brusque"]$pg$::jsonb,
 2,
 $pg$Le véhicule prioritaire a besoin d'un passage prévisible, pas d'un nouvel obstacle. Observer avant de te déplacer protège aussi les vélos et piétons autour.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000074','C2h',
 $pg$Le guidage devient silencieux juste avant une intersection complexe. Ton réflexe ?$pg$,
 $pg$["Tu gardes une direction autorisée et le laisses recalculer", "Tu t'arrêtes au milieu du carrefour pour attendre une nouvelle consigne", "Tu changes de voie au dernier moment pour retrouver la bonne direction"]$pg$::jsonb,
 0,
 $pg$Une erreur d'itinéraire se corrige plus loin. Rester lisible et légal évite de transformer une hésitation en danger immédiat.$pg$,
 2,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000075','C2h',
 $pg$Ta destination est à gauche mais aucun passage sûr ne s'ouvre dans le trafic. Que décides-tu ?$pg$,
 $pg$["Tu traverses rapidement plusieurs voies en force", "Tu continues et cherches un itinéraire plus simple", "Tu bloques ta voie en attendant longtemps"]$pg$::jsonb,
 1,
 $pg$Atteindre une adresse ne justifie jamais une trajectoire forcée. Quelques minutes de détour coûtent moins qu'un conflit avec plusieurs voies.$pg$,
 3,'post_validation',null),
('c2a2c2b2-8000-4000-8000-000000000076','C2h',
 $pg$Les panneaux et les voies d'un grand carrefour t'embrouillent. Quelle décision te rend de la marge ?$pg$,
 $pg$["Tu suis au hasard la voiture devant en supposant qu'elle connaît la bonne sortie", "Tu freines au milieu pour réfléchir et lire chaque panneau sans avancer", "Tu gardes ta voie, choisis une direction autorisée et te réorganises plus loin"]$pg$::jsonb,
 2,
 $pg$L'autonomie n'exige pas de choisir l'itinéraire parfait du premier coup. Elle exige une décision sûre, compréhensible et corrigeable.$pg$,
 3,'post_validation',null)
on conflict (id) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c2a2c2b2-8000-4000-8000-000000000001','en',
 $pg$A stopped bus hides part of the pavement. What do you look for before passing it?$pg$,
 $pg$["Feet or a silhouette that could emerge in front of the bus", "Only the bus indicator to know whether it will pull away", "Only the road far ahead to anticipate moving traffic"]$pg$::jsonb,
 $pg$A hidden pedestrian first appears through small clues under or around the vehicle. Lifting off as soon as you see them gives you time to stop.$pg$),
('c2a2c2b2-8000-4000-8000-000000000001','ar',
 $pg$تحجب حافلة متوقفة جزءًا من الرصيف. عمّ تبحث قبل المرور بجانبها؟$pg$,
 $pg$["قدمين أو هيئة شخص قد يظهر أمام الحافلة", "غمّاز الحافلة فقط لمعرفة هل ستتحرك", "الطريق البعيد أمامك فقط لتوقع حركة السير"]$pg$::jsonb,
 $pg$يظهر المشاة المحجوب أولًا عبر إشارات صغيرة تحت المركبة أو حولها. رفع القدم عند رؤية هذه الإشارات يمنحك وقتًا للتوقّف.$pg$),
('c2a2c2b2-8000-4000-8000-000000000002','en',
 $pg$A parked car has its wheels turned and someone is at the wheel. What does that tell you?$pg$,
 $pg$["It will definitely stay still because its lights are off", "It may pull out of its space, so you prepare your response", "Its boot is about to open so someone can take something out"]$pg$::jsonb,
 $pg$The wheels and the driver announce a possible movement even before an indicator. Keep a margin and watch the door.$pg$),
('c2a2c2b2-8000-4000-8000-000000000002','ar',
 $pg$عجلات سيارة مركونة مائلة ويوجد شخص خلف مقودها. ماذا تفهم من ذلك؟$pg$,
 $pg$["ستبقى ثابتة بالتأكيد لأن أضواءها مطفأة", "قد تغادر مكانها، فتستعد للتصرف", "سيفتح صندوقها الخلفي لإخراج شيء منه"]$pg$::jsonb,
 $pg$تعلن العجلات ووجود السائق عن حركة محتملة حتى قبل الغمّاز. اترك هامشًا وراقب الباب.$pg$),
('c2a2c2b2-8000-4000-8000-000000000003','en',
 $pg$The light is green, but several brake lights come on far ahead. Which information matters most?$pg$,
 $pg$["The green light guarantees that everyone will keep moving", "The cars close to you provide enough information to decide", "The slowing traffic is spreading, so lift off early"]$pg$::jsonb,
 $pg$The light allows you through but does not guarantee flowing traffic. Reading distant brake lights stops you discovering the queue at the last moment.$pg$),
('c2a2c2b2-8000-4000-8000-000000000003','ar',
 $pg$الإشارة خضراء لكن أضواء فرامل عدة سيارات تضيء بعيدًا أمامك. أي معلومة أهم؟$pg$,
 $pg$["الضوء الأخضر يضمن أن الجميع سيواصل التحرك", "السيارات القريبة منك تعطي معلومات كافية للقرار", "التباطؤ ينتقل نحوك، فترفع قدمك مبكرًا"]$pg$::jsonb,
 $pg$تسمح الإشارة بالمرور لكنها لا تضمن انسياب الحركة. قراءة أضواء الفرامل البعيدة تمنع اكتشاف الصف في اللحظة الأخيرة.$pg$),
('c2a2c2b2-8000-4000-8000-000000000004','en',
 $pg$You are about to slow down sharply. Why check the interior mirror first?$pg$,
 $pg$["To know who is following and show your slowing early enough", "To replace checking what is happening ahead while you brake", "To check only the left lane before you begin slowing"]$pg$::jsonb,
 $pg$A vehicle very close behind does not stop you braking, but it encourages you to act early and progressively so its driver has time to react.$pg$),
('c2a2c2b2-8000-4000-8000-000000000004','ar',
 $pg$ستبطئ كثيرًا. لماذا تنظر أولًا إلى المرآة الداخلية؟$pg$,
 $pg$["لتعرف من يتبعك وتُظهر تباطؤك مبكرًا", "لتستغني عن مراقبة ما يحدث أمامك أثناء الفرملة", "لفحص المسار الأيسر فقط قبل بدء التباطؤ"]$pg$::jsonb,
 $pg$وجود مركبة قريبة خلفك لا يمنع الفرملة، لكنه يدفعك إلى التصرف مبكرًا وتدريجيًا ليملك سائقها وقتًا للرد.$pg$),
('c2a2c2b2-8000-4000-8000-000000000005','en',
 $pg$Branches hide part of a sign. How do you avoid guessing its instruction?$pg$,
 $pg$["Copy the speed of the car ahead and assume its driver understood", "Slow down and compare its shape with the road markings and situation", "Ignore it because it is hard to see and keep your current speed"]$pg$::jsonb,
 $pg$The shape, road markings and layout provide clues that support one another. Slowing down gives you time to confirm before acting.$pg$),
('c2a2c2b2-8000-4000-8000-000000000005','ar',
 $pg$تحجب الأغصان جزءًا من لافتة. كيف تتجنب تخمين تعليماتها؟$pg$,
 $pg$["تقلد سرعة السيارة أمامك وتفترض أن سائقها فهمها", "تبطئ وتقارن شكلها بعلامات الطريق والوضع", "تتجاهلها لأنها غير واضحة وتحافظ على سرعتك"]$pg$::jsonb,
 $pg$يوفّر الشكل وعلامات الطريق وتنظيمه إشارات تؤكد بعضها. يمنحك التباطؤ وقتًا للتأكد قبل التصرف.$pg$),
('c2a2c2b2-8000-4000-8000-000000000006','en',
 $pg$A van blocks your view to the right at a junction. How do you recover the missing information?$pg$,
 $pg$["Move out quickly so you can see before another vehicle arrives", "Look only to the left because it is the nearest side of the junction", "Slow down, move forward in small stages and move your head to see around it"]$pg$::jsonb,
 $pg$When your view is blocked, change your position without exposing the whole car. Each small move opens a new viewing angle.$pg$),
('c2a2c2b2-8000-4000-8000-000000000006','ar',
 $pg$تحجب شاحنة صغيرة رؤيتك إلى اليمين عند تقاطع. كيف تستعيد المعلومة الناقصة؟$pg$,
 $pg$["تدخل بسرعة لكي ترى هناك قبل وصول مركبة أخرى", "تنظر إلى اليسار فقط لأنه الجانب الأقرب إليك", "تبطئ وتتقدم على مراحل صغيرة وتحرك رأسك للرؤية حولها"]$pg$::jsonb,
 $pg$عندما تنقطع الرؤية، غيّر موقعك دون كشف السيارة كلها. تفتح كل خطوة صغيرة زاوية رؤية جديدة.$pg$),

('c2a2c2b2-8000-4000-8000-000000000011','en',
 $pg$Low sunlight dazzles you and the pedestrian crossing is hard to see. What do you do?$pg$,
 $pg$["Slow down until you can see safely again", "Keep your speed because the light is green", "Follow the lights of the car ahead"]$pg$::jsonb,
 $pg$If you cannot see an area, you cannot guarantee that you can stop within it. Reducing speed turns the visible distance into useful stopping room.$pg$),
('c2a2c2b2-8000-4000-8000-000000000011','ar',
 $pg$تبهرك الشمس المنخفضة ويصعب عليك رؤية ممر المشاة. ماذا تفعل؟$pg$,
 $pg$["تبطئ حتى تستعيد رؤية آمنة", "تحافظ على سرعتك لأن الإشارة خضراء", "تتبع أضواء السيارة التي أمامك فقط"]$pg$::jsonb,
 $pg$المنطقة التي لا تراها لا يمكنك ضمان التوقّف داخلها. خفض السرعة يحول المسافة المرئية إلى مساحة مفيدة للتوقّف.$pg$),
('c2a2c2b2-8000-4000-8000-000000000012','en',
 $pg$You are following a large van that hides the entire road ahead. How do you regain anticipation?$pg$,
 $pg$["Move closer to see around its side despite the short gap", "Increase the gap so you can see farther around it", "Drive on the left of your lane to open up your view"]$pg$::jsonb,
 $pg$The farther back you are, the more your view opens around the tall vehicle. That margin also adds time if it brakes suddenly.$pg$),
('c2a2c2b2-8000-4000-8000-000000000012','ar',
 $pg$تتبع شاحنة صغيرة مرتفعة تحجب الطريق كله أمامك. كيف تستعيد القدرة على الاستباق؟$pg$,
 $pg$["تقترب لترى من جانبها رغم قصر المسافة", "تزيد مسافة الأمان لترى أبعد حولها", "تسير في يسار مسارك حتى توسع مجال رؤيتك"]$pg$::jsonb,
 $pg$كلما ابتعدت انفتح مجال رؤيتك حول المركبة المرتفعة. ويمنحك هذا الهامش وقتًا إضافيًا إذا فرملت فجأة.$pg$),
('c2a2c2b2-8000-4000-8000-000000000013','en',
 $pg$Wet leaves cover the entrance to a bend. When do you adjust your speed?$pg$,
 $pg$["After you feel the car slide beneath you", "In the middle of the bend while braking lightly", "Before the leaves, using gentle inputs"]$pg$::jsonb,
 $pg$Wet leaves reduce grip like a slippery film. Slowing before them lets you cross the area without sudden braking or steering.$pg$),
('c2a2c2b2-8000-4000-8000-000000000013','ar',
 $pg$تغطي أوراق مبللة مدخل منعطف. متى تعدّل سرعتك؟$pg$,
 $pg$["بعد أن تشعر بانزلاق السيارة تحتك", "في وسط المنعطف مع فرملة خفيفة", "قبل الأوراق مع حركات لطيفة"]$pg$::jsonb,
 $pg$تقلل الأوراق المبللة التماسك مثل طبقة زلقة. التباطؤ قبلها يسمح بعبور المنطقة دون فرملة أو توجيه مفاجئ.$pg$),
('c2a2c2b2-8000-4000-8000-000000000014','en',
 $pg$The road narrows and a vehicle is coming towards you. What do you do first?$pg$,
 $pg$["Slow before the narrow section and assess who can pass", "Accelerate to arrive first and claim the passage", "Keep the same speed until you meet face to face then decide"]$pg$::jsonb,
 $pg$Deciding before the narrow section avoids braking nose to nose. At low speed, each driver can adjust position or stop without surprise.$pg$),
('c2a2c2b2-8000-4000-8000-000000000014','ar',
 $pg$يضيق الطريق وتأتي مركبة في الاتجاه المعاكس. ما أول تصرّف؟$pg$,
 $pg$["تبطئ قبل الممر الضيق وتقيّم من يستطيع المرور", "تسرّع لتصل قبل المركبة الأخرى وتفرض مرورك", "تحافظ على السرعة حتى تصبحا وجهًا لوجه ثم تقرر"]$pg$::jsonb,
 $pg$اتخاذ القرار قبل الممر يمنع الفرملة وجهًا لوجه. عند السرعة المنخفضة يستطيع كل سائق تعديل موقعه أو التوقّف دون مفاجأة.$pg$),
('c2a2c2b2-8000-4000-8000-000000000015','en',
 $pg$A market runs along the street and pedestrians are watching the stalls rather than traffic. What speed do you choose?$pg$,
 $pg$["Exactly the speed limit without slowing because the lane is open", "A speed that lets you stop as soon as a pedestrian moves", "The same speed as the car behind so you do not hold it up"]$pg$::jsonb,
 $pg$The pedestrians' attention is elsewhere, so their path may change without a look. Your speed must absorb that surprise.$pg$),
('c2a2c2b2-8000-4000-8000-000000000015','ar',
 $pg$يمتد سوق على طول الشارع وينظر المشاة إلى البسطات بدل حركة السير. أي سرعة تختار؟$pg$,
 $pg$["حد السرعة بالضبط دون تباطؤ لأن المسار مفتوح", "سرعة تسمح لك بالتوقّف بمجرد تحرك أحد المشاة", "سرعة السيارة خلفك نفسها حتى لا تعطلها"]$pg$::jsonb,
 $pg$انتباه المشاة موجّه إلى مكان آخر، لذلك قد يتغير مسارهم دون نظرة. يجب أن تستوعب سرعتك هذه المفاجأة.$pg$),
('c2a2c2b2-8000-4000-8000-000000000016','en',
 $pg$The queue accelerates and brakes every few metres. How do you avoid accordion driving?$pg$,
 $pg$["Follow closely so nobody can move in", "Copy every acceleration immediately", "Keep more space and a steady speed"]$pg$::jsonb,
 $pg$The space ahead absorbs small changes in the queue. You can often let the car roll without alternating between acceleration and braking.$pg$),
('c2a2c2b2-8000-4000-8000-000000000016','ar',
 $pg$يتسارع الصف ويفرمل كل بضعة أمتار. كيف تتجنب القيادة المتقطعة؟$pg$,
 $pg$["تقترب كثيرًا حتى لا يدخل أحد أمامك في الصف", "تقلد كل تسارع فورًا حتى تبقى مع السيارة أمامك", "تترك مساحة أكبر وتحافظ على سرعة منتظمة"]$pg$::jsonb,
 $pg$تمتص المساحة أمامك التغيّرات الصغيرة في الصف. وغالبًا يمكنك ترك السيارة تسير دون التناوب بين التسارع والفرملة.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c2a2c2b2-8000-4000-8000-000000000021','en',
 $pg$Your lane markings are almost worn away. How do you keep a steady path?$pg$,
 $pg$["Look far ahead and use both edges of the road as guides", "Fix your eyes on the right edge beyond the bonnet to guide the car", "Follow the car ahead exactly and copy its entire path"]$pg$::jsonb,
 $pg$Distant reference points smooth your path even when a line disappears. Both edges help you rebuild the centre of your space.$pg$),
('c2a2c2b2-8000-4000-8000-000000000021','ar',
 $pg$تكاد علامات مسارك تختفي. كيف تحافظ على مسار ثابت؟$pg$,
 $pg$["تنظر بعيدًا وتستعمل جانبي الطريق كاملين", "تثبت نظرك على الحافة اليمنى أمام غطاء المحرك", "تتبع السيارة أمامك حرفيًا وتنسخ مسارها كله"]$pg$::jsonb,
 $pg$تجعل العلامات البعيدة مسارك سلسًا حتى عند اختفاء الخط. ويساعدك جانبا الطريق على تحديد وسط مساحتك.$pg$),
('c2a2c2b2-8000-4000-8000-000000000022','en',
 $pg$Cars are parked on both sides of a narrow street. Where do you place yours?$pg$,
 $pg$["Right beside the parked cars on the right", "In the centre of the free space, at low speed", "Right beside the parked cars on the left"]$pg$::jsonb,
 $pg$The centre of the available space leaves a margin on both sides. Low speed lets you stop if a door opens.$pg$),
('c2a2c2b2-8000-4000-8000-000000000022','ar',
 $pg$سيارات مركونة على جانبي شارع ضيق. أين تضع سيارتك؟$pg$,
 $pg$["ملاصقة للسيارات المتوقفة على اليمين", "في وسط المساحة الحرة وبسرعة منخفضة", "ملاصقة للسيارات المتوقفة على اليسار"]$pg$::jsonb,
 $pg$يترك وسط المساحة المتاحة هامشًا على الجانبين. وتسمح السرعة المنخفضة بالتوقّف إذا فُتح باب.$pg$),
('c2a2c2b2-8000-4000-8000-000000000023','en',
 $pg$A lorry is coming towards you on a narrow road. How do you position your car?$pg$,
 $pg$["Dive onto the verge to leave the whole road to the lorry", "Hold the middle to force the lorry to slow before you", "Slow down and keep a safe margin on the right without leaving the road"]$pg$::jsonb,
 $pg$Slowing down reduces the space each vehicle needs. The edge remains a limit to watch, not somewhere to send the wheels out of fear.$pg$),
('c2a2c2b2-8000-4000-8000-000000000023','ar',
 $pg$تأتي شاحنة في الاتجاه المعاكس على طريق ضيق. كيف تضع سيارتك؟$pg$,
 $pg$["تنزل فجأة إلى حافة الطريق لتترك الطريق كله للشاحنة", "تبقى في الوسط لتجبر الشاحنة على التباطؤ قبلك", "تبطئ وتحافظ على هامش آمن يمينًا دون مغادرة الطريق"]$pg$::jsonb,
 $pg$يقلل التباطؤ المساحة التي تحتاجها كل مركبة. تبقى الحافة حدًا تراقبه، وليست مكانًا تدفع إليه العجلات بسبب الخوف.$pg$),
('c2a2c2b2-8000-4000-8000-000000000024','en',
 $pg$A deep pothole fills the right edge of your lane. How do you avoid it?$pg$,
 $pg$["Check behind and ahead before moving slightly away safely", "Jerk the wheel without looking to avoid the hole at the last moment", "Move even farther right so you can cross the hole slowly"]$pg$::jsonb,
 $pg$Avoiding a road defect is still a change of path. Your checks confirm that the neighbouring space is clear before you move.$pg$),
('c2a2c2b2-8000-4000-8000-000000000024','ar',
 $pg$حفرة عميقة تشغل الحافة اليمنى من مسارك. كيف تتجنبها؟$pg$,
 $pg$["تراقب خلفك وأمامك قبل الابتعاد قليلًا بأمان", "تدير المقود فجأة دون نظر لتفادي الحفرة في آخر لحظة", "تلتزم أكثر باليمين لتمر ببطء داخل الحفرة"]$pg$::jsonb,
 $pg$تجنب عيب في الطريق يظل تغييرًا للمسار. تؤكد المراقبة أن المساحة المجاورة خالية قبل انتقالك.$pg$),
('c2a2c2b2-8000-4000-8000-000000000025','en',
 $pg$On a left bend, your front left wheel approaches the centre line. What do you correct?$pg$,
 $pg$["Cut the bend more to move your wheel away from the line", "Stay in your lane and adjust your path gently away from the line", "Accelerate to leave faster and recover your position afterwards"]$pg$::jsonb,
 $pg$Cutting the bend exposes the front of your car to oncoming traffic. A gentle correction keeps the whole car in its corridor.$pg$),
('c2a2c2b2-8000-4000-8000-000000000025','ar',
 $pg$في منعطف إلى اليسار تقترب عجلتك الأمامية اليسرى من الخط الوسطي. ماذا تصحح؟$pg$,
 $pg$["تقطع المنعطف أكثر لإبعاد عجلتك عن الخط", "تبقى في مسارك وتعدّل المسار بلطف", "تسرّع للخروج أسرع ثم تستعيد موقعك بعد ذلك"]$pg$::jsonb,
 $pg$قطع المنعطف يعرّض مقدمة سيارتك للقادم في الاتجاه المعاكس. يبقي التصحيح اللطيف السيارة كلها داخل ممرها.$pg$),
('c2a2c2b2-8000-4000-8000-000000000026','en',
 $pg$After overtaking, the right lane is clear for a long distance. Where do you drive?$pg$,
 $pg$["Stay on the left to keep a better view of the road ahead", "Move back as soon as your front bumper passes the vehicle", "Return to the right after checking and leaving enough room"]$pg$::jsonb,
 $pg$The left lane is for overtaking. Returning right frees traffic, but only when you do not cut across the vehicle you passed.$pg$),
('c2a2c2b2-8000-4000-8000-000000000026','ar',
 $pg$بعد التجاوز يكون المسار الأيمن خاليًا لمسافة طويلة. أين تسير؟$pg$,
 $pg$["تبقى يسارًا لتحافظ على رؤية أفضل للطريق أمامك", "تعود بمجرد أن تتقدم مقدمة سيارتك على المركبة", "تعود يمينًا بعد المراقبة وترك مسافة كافية"]$pg$::jsonb,
 $pg$المسار الأيسر للتجاوز. العودة يمينًا تحرر الحركة، لكن فقط عندما لا تقطع طريق المركبة التي تجاوزتها.$pg$),

('c2a2c2b2-8000-4000-8000-000000000031','en',
 $pg$You approach a bend and cannot see what is beyond it. What entry speed do you choose?$pg$,
 $pg$["A speed that lets you stop within the visible section", "The posted maximum speed even though the exit remains hidden", "The speed of the car behind so you do not slow it down"]$pg$::jsonb,
 $pg$The hidden exit may contain a queue, bicycle or obstacle. Your stopping distance must fit inside the road your eyes can actually see.$pg$),
('c2a2c2b2-8000-4000-8000-000000000031','ar',
 $pg$تقترب من منعطف ولا ترى ما بعده. أي سرعة دخول تختار؟$pg$,
 $pg$["سرعة مناسبة تسمح بالتوقّف داخل الجزء المرئي", "السرعة القصوى المكتوبة حتى لو بقي المخرج محجوبًا", "سرعة السيارة خلفك حتى لا تسبب لها التباطؤ"]$pg$::jsonb,
 $pg$قد يخفي مخرج المنعطف صفًا أو دراجة أو عائقًا. يجب أن تبقى مسافة توقّفك داخل الطريق الذي تراه عيناك فعلًا.$pg$),
('c2a2c2b2-8000-4000-8000-000000000032','en',
 $pg$The road is wet before a bend. What do you change?$pg$,
 $pg$["Brake once you are in the curve to set your exact speed", "Slow down more before it and steer without sudden inputs", "Build up more speed before the curve so you do not slide"]$pg$::jsonb,
 $pg$Less grip leaves less room for correction. Setting your speed in a straight line lets the tyres focus on turning.$pg$),
('c2a2c2b2-8000-4000-8000-000000000032','ar',
 $pg$الطريق مبلل قبل منعطف. ماذا تغيّر؟$pg$,
 $pg$["تفرمل بعد دخول المنعطف لتضبط سرعتك بدقة", "تبطئ أكثر قبله وتوجّه دون حركة مفاجئة", "تزيد السرعة قبل المنعطف حتى لا تنزلق"]$pg$::jsonb,
 $pg$يترك التماسك الأقل مجالًا أقل للتصحيح. ضبط السرعة في خط مستقيم يسمح للإطارات بالتركيز على الانعطاف.$pg$),
('c2a2c2b2-8000-4000-8000-000000000033','en',
 $pg$The bend tightens more than expected. How do you react?$pg$,
 $pg$["Fix your eyes on the outside edge to judge the bend precisely", "Brake and steer suddenly to return to the correct line immediately", "Lift off, look towards the exit and add steering gently"]$pg$::jsonb,
 $pg$Your eyes give the direction and lifting off prevents the path opening farther. A progressive input preserves the available grip.$pg$),
('c2a2c2b2-8000-4000-8000-000000000033','ar',
 $pg$يضيق المنعطف أكثر مما توقعت. كيف تتصرف؟$pg$,
 $pg$["تثبت نظرك على الحافة الخارجية لتقيس المنعطف بدقة", "تفرمل وتدير المقود فجأة لتعود إلى المسار فورًا", "ترفع قدمك وتنظر إلى المخرج وتزيد التوجيه بلطف"]$pg$::jsonb,
 $pg$يعطي النظر الاتجاه ويمنع رفع القدم اتساع المسار أكثر. وتحافظ الحركة التدريجية على التماسك المتاح.$pg$),
('c2a2c2b2-8000-4000-8000-000000000034','en',
 $pg$Two bends follow one another in opposite directions. Where does your gaze move?$pg$,
 $pg$["To the exit of the first, then the exit of the second", "To the line between them so you keep one fixed reference", "Into the mirror throughout the whole sequence of bends"]$pg$::jsonb,
 $pg$Each exit becomes the visual entrance to the next bend. Moving your gaze in time stops you finishing the first bend too late.$pg$),
('c2a2c2b2-8000-4000-8000-000000000034','ar',
 $pg$يتتابع منعطفان في اتجاهين متعاكسين. أين ينتقل نظرك؟$pg$,
 $pg$["إلى مخرج الأول ثم مخرج الثاني", "إلى الخط بينهما حتى تحتفظ بمرجع ثابت", "إلى المرآة طوال تسلسل المنعطفات كله"]$pg$::jsonb,
 $pg$يصبح كل مخرج مدخلًا بصريًا للمنعطف التالي. نقل النظر في الوقت المناسب يمنع إنهاء المنعطف الأول متأخرًا.$pg$),
('c2a2c2b2-8000-4000-8000-000000000035','en',
 $pg$An oncoming car moves slightly into your lane on a bend. What do you do?$pg$,
 $pg$["Keep your speed to defend your place and show your intended line", "Lift off, keep room on the right and prepare to stop", "Stare at its headlights to monitor every movement precisely"]$pg$::jsonb,
 $pg$Reducing speed creates time and reduces the width needed to pass. Looking at your free space helps you steer the car into it.$pg$),
('c2a2c2b2-8000-4000-8000-000000000035','ar',
 $pg$تدخل سيارة مقابلة قليلًا في مسارك داخل منعطف. ماذا تفعل؟$pg$,
 $pg$["تحافظ على السرعة للدفاع عن مكانك وإظهار مسارك", "ترفع قدمك وتترك هامشًا يمينًا وتستعد للتوقّف", "تثبت نظرك على أضوائها لمراقبة كل حركة بدقة"]$pg$::jsonb,
 $pg$يخلق خفض السرعة وقتًا ويقلل العرض اللازم للمرور. والنظر إلى مساحتك الحرة يساعدك على توجيه السيارة إليها.$pg$),
('c2a2c2b2-8000-4000-8000-000000000036','en',
 $pg$You follow a lorry that hides the whole exit of a bend. How do you approach the curve?$pg$,
 $pg$["Follow closely and copy its path and speed through the bend", "Move onto the centre line so you can see around its cab", "Increase the gap and choose your speed using your own visibility"]$pg$::jsonb,
 $pg$The lorry may pass over an obstacle that you cannot avoid. A larger margin restores your own view and stopping distance.$pg$),
('c2a2c2b2-8000-4000-8000-000000000036','ar',
 $pg$تتبع شاحنة تحجب مخرج المنعطف كله. كيف تدخل المنحنى؟$pg$,
 $pg$["تتبعها عن قرب وتقلد مسارها وسرعتها داخل المنعطف", "تقترب من الخط الوسطي حتى ترى حول مقصورة الشاحنة", "تزيد المسافة وتختار سرعتك حسب رؤيتك أنت"]$pg$::jsonb,
 $pg$قد تمر الشاحنة فوق عائق لا تستطيع أنت تجنبه. يعيد الهامش الأكبر رؤيتك ومسافة توقّف خاصة بك.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c2a2c2b2-8000-4000-8000-000000000041','en',
 $pg$An oncoming car approaches while a parked vehicle blocks your side. Who makes the crossing easier?$pg$,
 $pg$["You slow down and let it pass before going around the obstacle", "The other driver must always reverse to let you go around", "You go around quickly so you finish before it arrives"]$pg$::jsonb,
 $pg$The obstacle forces you away from your normal path. Waiting before going around prevents the crossing becoming face to face.$pg$),
('c2a2c2b2-8000-4000-8000-000000000041','ar',
 $pg$تقترب سيارة مقابلة بينما تعيق مركبة مركونة جانبك. من يسهّل التقابل؟$pg$,
 $pg$["تبطئ مبكرًا وتتركها تمر قبل تجاوز العائق", "يجب على الآخر أن يرجع دائمًا ليتركك تتجاوز العائق", "تتجاوز العائق بسرعة حتى تنتهي قبل وصولها"]$pg$::jsonb,
 $pg$يجبرك العائق على مغادرة مسارك الطبيعي. الانتظار قبل تجاوزه يمنع تحوّل التقابل إلى مواجهة مباشرة.$pg$),
('c2a2c2b2-8000-4000-8000-000000000042','en',
 $pg$You prepare to overtake and the vehicle ahead indicates left. What do you do?$pg$,
 $pg$["Overtake quickly before it has time to begin turning", "Abandon the overtake and keep your distance behind it", "Sound the horn repeatedly to reserve your place in advance"]$pg$::jsonb,
 $pg$Its indicator announces a path that may cross yours. Abandoning removes the conflict instead of gambling on when it will turn.$pg$),
('c2a2c2b2-8000-4000-8000-000000000042','ar',
 $pg$تستعد للتجاوز وتشغّل المركبة أمامك غمّازها الأيسر. ماذا تفعل؟$pg$,
 $pg$["تتجاوز بسرعة قبل أن تبدأ المركبة انعطافها", "تلغي التجاوز وتحافظ على المسافة", "تستعمل المنبّه مرارًا لحجز مكانك مسبقًا"]$pg$::jsonb,
 $pg$يعلن غمّازها عن مسار قد يقطع مسارك. إلغاء التجاوز يزيل التعارض بدل المراهنة على لحظة انعطافها.$pg$),
('c2a2c2b2-8000-4000-8000-000000000043','en',
 $pg$Beyond the slow vehicle, there is no gap for you to return to the queue. Do you overtake?$pg$,
 $pg$["Yes, the queue will definitely let you back in when needed", "Yes, if you accelerate enough to return before oncoming traffic", "No, wait until a visible return space is available"]$pg$::jsonb,
 $pg$An overtake is decided with its exit already planned. Without room to return, you may be left in the oncoming lane.$pg$),
('c2a2c2b2-8000-4000-8000-000000000043','ar',
 $pg$لا توجد بعد المركبة البطيئة مساحة تعود منها إلى الصف. هل تتجاوز؟$pg$,
 $pg$["نعم، سيسمح لك الصف حتمًا بالعودة عند الحاجة", "نعم، إذا سرعت بما يكفي لتعود قبل المركبة المقابلة", "لا، تنتظر حتى ترى مساحة واضحة وآمنة للعودة"]$pg$::jsonb,
 $pg$يُتخذ قرار التجاوز بعد تخطيط مخرجه مسبقًا. من دون مكان للعودة قد تبقى في مسار الاتجاه المعاكس.$pg$),
('c2a2c2b2-8000-4000-8000-000000000044','en',
 $pg$The driver you are overtaking suddenly accelerates. How do you react?$pg$,
 $pg$["Abandon the overtake and move safely back behind the vehicle", "Break the speed limit to win the duel before it accelerates again", "Stay alongside until the other driver slows down without help"]$pg$::jsonb,
 $pg$A speed contest extends your time on the left. Abandoning early restores space and puts each vehicle back in its lane.$pg$),
('c2a2c2b2-8000-4000-8000-000000000044','ar',
 $pg$يسرّع فجأة السائق الذي تتجاوزه. كيف تتصرف؟$pg$,
 $pg$["تلغي التجاوز وتعود خلفه عندما يصبح ذلك آمنًا", "تتجاوز حد السرعة للفوز قبل أن يسرع من جديد", "تبقى بمحاذاته حتى يبطئ السائق الآخر من تلقاء نفسه"]$pg$::jsonb,
 $pg$تطيل منافسة السرعة الوقت الذي تقضيه يسارًا. يعيد الإلغاء المبكر المساحة ويضع كل مركبة في مسارها.$pg$),
('c2a2c2b2-8000-4000-8000-000000000045','en',
 $pg$You overtake a horse rider on a country road. What is the right approach?$pg$,
 $pg$["Sound the horn for a long time to warn the rider before passing", "Slow down and leave a wide gap without sudden noise", "Pass quickly and closely to spend less time beside the horse"]$pg$::jsonb,
 $pg$A horse may react to noise and move sideways suddenly. Low speed and distance protect the rider even if the animal moves.$pg$),
('c2a2c2b2-8000-4000-8000-000000000045','ar',
 $pg$تتجاوز فارسًا على طريق ريفي. ما الطريقة الصحيحة؟$pg$,
 $pg$["تستعمل المنبّه طويلًا لتحذير الفارس قبل المرور", "تبطئ وتترك مسافة واسعة وكبيرة دون صوت مفاجئ", "تمر بسرعة وعن قرب حتى تبقى وقتًا أقل بجانب الحصان"]$pg$::jsonb,
 $pg$قد يتفاعل الحصان مع الصوت وينحرف فجأة. تحمي السرعة المنخفضة والمسافة الفارس حتى لو تحرك الحيوان.$pg$),
('c2a2c2b2-8000-4000-8000-000000000046','en',
 $pg$A cyclist ahead moves around potholes and their path varies. When do you overtake?$pg$,
 $pg$["As soon as they move right once after avoiding a pothole", "By passing close to reduce the time spent in the opposing lane", "When you can allow for their movement and leave a real side gap"]$pg$::jsonb,
 $pg$The cyclist sometimes has to choose between a pothole and moving sideways. Waiting for a wide area avoids taking away their only escape route.$pg$),
('c2a2c2b2-8000-4000-8000-000000000046','ar',
 $pg$يتجنب درّاج أمامك الحفر ويتغيّر مساره. متى تتجاوزه؟$pg$,
 $pg$["بمجرد أن يعود يمينًا مرة بعد تفادي حفرة", "بالمرور قريبًا لتقليل الوقت في المسار المقابل", "عندما تتوقع انحرافه وتترك هامشًا جانبيًا حقيقيًا"]$pg$::jsonb,
 $pg$يختار الدرّاج أحيانًا بين حفرة وانحراف جانبي. انتظار منطقة واسعة يمنع سلبه مخرج النجاة الوحيد.$pg$),

('c2a2c2b2-8000-4000-8000-000000000051','en',
 $pg$At a STOP sign, the line is too far back to see the crossing road. What do you do?$pg$,
 $pg$["Stop at the line, then move forward slowly to observe", "Cross the line without stopping so you can see the crossing road", "Stop only after your car has entered the junction"]$pg$::jsonb,
 $pg$The first stop respects the limit. The next movement is only to gain a view, while remaining ready to give way.$pg$),
('c2a2c2b2-8000-4000-8000-000000000051','ar',
 $pg$عند إشارة التوقّف يكون الخط بعيدًا ولا ترى الطريق المتقاطع. كيف تتصرف؟$pg$,
 $pg$["تتوقّف عند الخط ثم تتقدم ببطء للمراقبة", "تتجاوز الخط دون توقّف حتى ترى الطريق المتقاطع", "تتوقّف فقط بعد دخول سيارتك في التقاطع"]$pg$::jsonb,
 $pg$يحترم التوقّف الأول الحد. أما التقدم التالي فهدفه كسب الرؤية فقط مع البقاء مستعدًا لإفساح الطريق.$pg$),
('c2a2c2b2-8000-4000-8000-000000000052','en',
 $pg$You turn left on a green light while an oncoming car goes straight ahead. Who goes first?$pg$,
 $pg$["You, because your indicator already announces your move to the left", "The oncoming car goes first, so you wait for a safe gap", "Whoever accelerates first to occupy the junction before the other driver"]$pg$::jsonb,
 $pg$Turning left crosses the oncoming vehicle's path. Green allows both of you to move, but it does not give you priority over that vehicle.$pg$),
('c2a2c2b2-8000-4000-8000-000000000052','ar',
 $pg$تنعطف يسارًا عند ضوء أخضر وتأتي سيارة مقابلة مستقيمة. من يمر أولًا؟$pg$,
 $pg$["أنت لأن غمّازك يعلن مسبقًا انتقالك إلى اليسار", "السيارة المقابلة تمر أولًا، فتنتظر فتحة آمنة", "من يسرّع أولًا حتى يحتل التقاطع قبل السائق الآخر"]$pg$::jsonb,
 $pg$يقطع الانعطاف يسارًا مسار المركبة المقابلة. يسمح الأخضر لكليكما بالحركة لكنه لا يمنحك الأولوية عليها.$pg$),
('c2a2c2b2-8000-4000-8000-000000000053','en',
 $pg$You turn right across a cycle lane. A bicycle continues straight on your right. What do you do?$pg$,
 $pg$["Turn before it arrives so the cycle lane is cleared quickly", "Move into the lane to force the cyclist to slow behind you", "Check the blind spot carefully and let the cyclist pass"]$pg$::jsonb,
 $pg$Your path crosses the bicycle's. It may remain hidden in your blind spot until the last moment, so give way before crossing the lane.$pg$),
('c2a2c2b2-8000-4000-8000-000000000053','ar',
 $pg$تنعطف يمينًا عبر مسار للدراجات وتواصل دراجة السير مستقيمة إلى يمينك. ماذا تفعل؟$pg$,
 $pg$["تنعطف قبل وصولها حتى تحرر مسار الدراجات بسرعة", "تدخل مسارها لإجبار راكب الدراجة على التباطؤ خلفك", "تفحص الزاوية الميتة جيدًا وتترك الدراجة تمر"]$pg$::jsonb,
 $pg$يقطع مسارك مسار الدراجة. قد تبقى مخفية في الزاوية الميتة حتى اللحظة الأخيرة، لذلك تفسح لها قبل قطع المسار.$pg$),
('c2a2c2b2-8000-4000-8000-000000000054','en',
 $pg$The traffic lights at a junction are out. How do you decide?$pg$,
 $pg$["Slow down and apply the signs, otherwise priority to the right", "Go because nobody has a green light and the junction is now free", "Follow the car ahead without checking the other directions"]$pg$::jsonb,
 $pg$A failed light does not remove the junction rules. Existing signs take over. With no sign, priority to the right decides.$pg$),
('c2a2c2b2-8000-4000-8000-000000000054','ar',
 $pg$إشارات تقاطع لا تعمل. كيف تقرر؟$pg$,
 $pg$["تبطئ وتطبق اللافتات، وإلا فالأولوية لليمين", "تمر لأن لا أحد لديه ضوء أخضر وأصبح التقاطع خاليًا", "تتبع السيارة أمامك دون مراقبة الاتجاهات الأخرى"]$pg$::jsonb,
 $pg$تعطل الإشارة لا يلغي قواعد التقاطع. تستعيد اللافتات الموجودة دورها. وبدون لافتة تقرر الأولوية لليمين.$pg$),
('c2a2c2b2-8000-4000-8000-000000000055','en',
 $pg$The light turns steady amber while you can stop safely. What do you do?$pg$,
 $pg$["Accelerate before red so you can cross the line without waiting", "Stop before the line because you can do so without danger", "Continue at the same speed because the red light is not on yet"]$pg$::jsonb,
 $pg$Steady amber means stop. The exception only applies when braking would create danger, not when you can save a few seconds.$pg$),
('c2a2c2b2-8000-4000-8000-000000000055','ar',
 $pg$يتحول الضوء إلى البرتقالي الثابت ويمكنك التوقّف بأمان. ماذا تفعل؟$pg$,
 $pg$["تسرّع قبل الأحمر حتى تعبر الخط دون انتظار", "تتوقّف قبل الخط لأنك تستطيع ذلك دون خطر", "تتابع بالسرعة نفسها لأن الضوء الأحمر لم يشتعل بعد"]$pg$::jsonb,
 $pg$يعني البرتقالي الثابت التوقّف. لا يُستثنى إلا الوضع الذي تخلق فيه الفرملة خطرًا، لا ربح بضع ثوان.$pg$),
('c2a2c2b2-8000-4000-8000-000000000056','en',
 $pg$A police car approaches with blue lights and a siren while your light is green. What do you do?$pg$,
 $pg$["Keep going because of the green light and enter the junction", "Stop immediately even if you completely block its path", "Help it pass safely without creating another danger"]$pg$::jsonb,
 $pg$Green must not send you across the priority vehicle's path. See where it is coming from and clear a path predictably.$pg$),
('c2a2c2b2-8000-4000-8000-000000000056','ar',
 $pg$تقترب سيارة شرطة بأضواء زرقاء وصفارة بينما إشارتك خضراء. ماذا تفعل؟$pg$,
 $pg$["تتابع المرور بسبب الأخضر وتدخل التقاطع", "تتوقّف فورًا حتى لو أغلقت طريقها بالكامل", "تسهّل مرورها بأمان دون خلق خطر جديد"]$pg$::jsonb,
 $pg$لا يجب أن يدفعك الأخضر إلى مسار المركبة ذات الأولوية. راقب جهة قدومها وافتح ممرًا بطريقة متوقعة.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c2a2c2b2-8000-4000-8000-000000000061','en',
 $pg$You are indicating to change lane. Must the other drivers let you move over?$pg$,
 $pg$["No, you always wait until a genuinely clear space is available", "Yes, the indicator gives you priority as soon as it is on", "Yes, after three seconds even if the lane is still occupied"]$pg$::jsonb,
 $pg$The indicator announces an intention but does not reserve a space. The move starts only when your checks confirm a safe margin.$pg$),
('c2a2c2b2-8000-4000-8000-000000000061','ar',
 $pg$شغّلت الغمّاز لتغيير المسار. هل يجب على الآخرين تركك تمر؟$pg$,
 $pg$["لا، تنتظر دائمًا حتى تتوفر مساحة خالية فعلًا", "نعم، يمنحك الغمّاز الأولوية بمجرد تشغيله", "نعم، بعد ثلاث ثوان حتى لو بقي المسار مشغولًا"]$pg$::jsonb,
 $pg$يعلن الغمّاز نية ولا يحجز مكانًا. لا يبدأ الانتقال إلا عندما تؤكد مراقبتك وجود هامش آمن.$pg$),
('c2a2c2b2-8000-4000-8000-000000000062','en',
 $pg$The car ahead has indicated left for a long time but keeps going straight. Do you overtake?$pg$,
 $pg$["Yes, its indicator no longer matters because it seems forgotten", "No, wait until the vehicle's actual path is completely clear", "Yes, quickly on the left before the car begins to turn"]$pg$::jsonb,
 $pg$A forgotten signal remains uncertain information. Waiting for the actual movement avoids placing yourself where the car may finally turn.$pg$),
('c2a2c2b2-8000-4000-8000-000000000062','ar',
 $pg$تبقي السيارة أمامك غمّازها الأيسر طويلًا لكنها تواصل مستقيمة. هل تتجاوز؟$pg$,
 $pg$["نعم، لم يعد غمّازها مهمًا لأنه يبدو منسيًا", "لا، تنتظر حتى يتضح مسار المركبة الحقيقي تمامًا", "نعم، بسرعة من اليسار قبل أن تبدأ السيارة بالانعطاف"]$pg$::jsonb,
 $pg$تبقى الإشارة المنسية معلومة غير مؤكدة. انتظار الحركة الفعلية يمنعك من الوقوف في الجهة التي قد تنعطف إليها السيارة.$pg$),
('c2a2c2b2-8000-4000-8000-000000000063','en',
 $pg$A stopped queue suddenly appears ahead on a fast road. How do you warn traffic behind?$pg$,
 $pg$["Sound the horn without stopping to warn the whole queue ahead", "Flash your headlights forward to ask for a clear path", "Brake and use the hazard lights until you have been seen"]$pg$::jsonb,
 $pg$Hazard lights warn fast approaching traffic of an unusual slowdown. You can switch them off once the queue behind has understood and slowed.$pg$),
('c2a2c2b2-8000-4000-8000-000000000063','ar',
 $pg$يظهر فجأة صف متوقّف أمامك على طريق سريع. كيف تحذر من خلفك؟$pg$,
 $pg$["تستعمل المنبّه دون توقّف لتحذير الصف كله أمامك", "تومض بأضوائك نحو الأمام لتطلب فتح الطريق", "تفرمل وتشغّل أضواء الخطر حتى يراك القادمون"]$pg$::jsonb,
 $pg$تحذر أضواء الخطر القادمين بسرعة من تباطؤ غير معتاد. ويمكنك إطفاؤها بعد أن يفهم الصف خلفك ويبطئ.$pg$),
('c2a2c2b2-8000-4000-8000-000000000064','en',
 $pg$Beside a lorry, you cannot see the driver's face in its mirror. What do you conclude?$pg$,
 $pg$["The driver probably cannot see you, so leave the blind spot", "The driver sees you through sensors even away from the mirrors", "The lorry will stay straight while its indicator remains off"]$pg$::jsonb,
 $pg$If you cannot see the driver or the mirror, nothing confirms that your presence is known. Staying back keeps you out of the lane change zone.$pg$),
('c2a2c2b2-8000-4000-8000-000000000064','ar',
 $pg$بجانب شاحنة لا ترى وجه السائق في مرآتها. ماذا تستنتج؟$pg$,
 $pg$["غالبًا لا يراك، فتغادر زاويته الميتة", "يراك بفضل الحساسات حتى بعيدًا عن المرايا", "ستبقى الشاحنة مستقيمة ما دام غمّازها مطفأ"]$pg$::jsonb,
 $pg$إذا لم تر السائق أو مرآته فلا شيء يؤكد معرفته بوجودك. البقاء خلفه يبعدك عن منطقة تغيير مساره.$pg$),
('c2a2c2b2-8000-4000-8000-000000000065','en',
 $pg$A driver waves you across in front of them. What do you still check?$pg$,
 $pg$["Nothing, the gesture replaces the priority rules for the whole junction", "Other lanes, bicycles and pedestrians must all be checked before moving", "Only that driver's indicator to confirm the car will remain still"]$pg$::jsonb,
 $pg$The gesture only speaks for that one car. Another road user may continue beside it without seeing your exchange.$pg$),
('c2a2c2b2-8000-4000-8000-000000000065','ar',
 $pg$يشير إليك سائق بالعبور أمامه. ماذا تراقب أيضًا؟$pg$,
 $pg$["لا شيء، تحل إشارته مكان قواعد الأولوية في التقاطع كله", "المسارات الأخرى والدراجات والمشاة قبل التقدم", "غمّاز ذلك السائق فقط للتأكد من بقاء سيارته ثابتة"]$pg$::jsonb,
 $pg$تتحدث إشارته عن سيارته وحدها. قد يواصل مستخدم آخر السير بجانبه دون أن يرى التفاهم بينكما.$pg$),
('c2a2c2b2-8000-4000-8000-000000000066','en',
 $pg$A cyclist looks behind and then extends their left arm. What does that tell you?$pg$,
 $pg$["They invite you to overtake immediately before changing direction", "They are only pointing out a danger on the left side of the road", "They may move left in front of you, so slow down and wait"]$pg$::jsonb,
 $pg$The look and arm announce an intention to change direction. Reading that message before the movement prevents a conflicting overtake.$pg$),
('c2a2c2b2-8000-4000-8000-000000000066','ar',
 $pg$ينظر درّاج خلفه ثم يمد ذراعه اليسرى. ما المعلومة التي يعطيك إياها؟$pg$,
 $pg$["يدعوك إلى تجاوزه فورًا قبل أن يغير اتجاهه", "يشير فقط إلى خطر على الجانب الأيسر من الطريق", "قد ينحرف يسارًا أمامك، فتبطئ وتنتظر"]$pg$::jsonb,
 $pg$تعلن النظرة والذراع نية تغيير الاتجاه. قراءة الرسالة قبل الحركة تمنع بدء تجاوز متعارض.$pg$),

('c2a2c2b2-8000-4000-8000-000000000071','en',
 $pg$The satnav tells you to turn into a prohibited street. Which instruction do you follow?$pg$,
 $pg$["Follow the road signs first, then let the satnav recalculate your route", "The satnav because it knows your route better than the road signs", "The passenger who sounds most confident about this road"]$pg$::jsonb,
 $pg$The screen suggests a route, while the signs control the real road. Continuing legally allows the guidance to build another route.$pg$),
('c2a2c2b2-8000-4000-8000-000000000071','ar',
 $pg$يطلب منك نظام الملاحة الانعطاف إلى شارع ممنوع. أي تعليمات تتبع؟$pg$,
 $pg$["تتبع لافتات الطريق أولًا ثم تترك النظام يعيد حساب مسارك", "نظام الملاحة لأنه يعرف مسارك أفضل من اللافتات الموجودة", "الراكب الذي يبدو أكثر ثقة بشأن هذا الطريق نفسه"]$pg$::jsonb,
 $pg$تقترح الشاشة طريقًا بينما تحكم اللافتات الطريق الحقيقي. يتيح الاستمرار بشكل قانوني للنظام بناء مسار آخر.$pg$),
('c2a2c2b2-8000-4000-8000-000000000072','en',
 $pg$Your passenger says to go, but a vehicle blocks your view. What do you do?$pg$,
 $pg$["Go because they checked for you and will warn you of any danger", "Wait until you have your own clear view before making the decision", "Move very slowly by following only their instructions"]$pg$::jsonb,
 $pg$You control the car and own the decision. Outside information can help but never replaces what you need to see yourself.$pg$),
('c2a2c2b2-8000-4000-8000-000000000072','ar',
 $pg$يقول لك الراكب « انطلق » لكن مركبة تحجب رؤيتك. ماذا تفعل؟$pg$,
 $pg$["تنطلق لأنه يراقب بدلًا منك وسيحذرك من أي خطر", "تنتظر حتى تملك رؤيتك الواضحة قبل اتخاذ القرار", "تتقدم ببطء شديد باتباع تعليماته وحدها"]$pg$::jsonb,
 $pg$أنت تتحكم في السيارة وتتحمل القرار. قد تساعدك معلومة خارجية لكنها لا تعوّض أبدًا ما يجب أن تراه بنفسك.$pg$),
('c2a2c2b2-8000-4000-8000-000000000073','en',
 $pg$A police car with its siren approaches behind you in a busy street. How do you make room?$pg$,
 $pg$["Mount the pavement immediately without checking for other road users", "Accelerate as far as the next red light to clear the street behind", "Check, slow down and clear safe space without a sudden move"]$pg$::jsonb,
 $pg$The priority vehicle needs a predictable path, not a new obstacle. Looking before moving also protects bicycles and pedestrians around you.$pg$),
('c2a2c2b2-8000-4000-8000-000000000073','ar',
 $pg$تقترب سيارة شرطة بصفارتها خلفك في شارع مزدحم. كيف تفتح الطريق؟$pg$,
 $pg$["تصعد فورًا على الرصيف دون فحص المستخدمين الموجودين عليه", "تسرّع حتى الإشارة الحمراء التالية لتفرغ الشارع خلفك", "تراقب وتبطئ وتفتح مساحة آمنة دون حركة مفاجئة"]$pg$::jsonb,
 $pg$تحتاج المركبة ذات الأولوية إلى ممر متوقّع لا إلى عائق جديد. وتحمي المراقبة قبل التحرك الدراجات والمشاة حولك.$pg$),
('c2a2c2b2-8000-4000-8000-000000000074','en',
 $pg$The guidance goes silent just before a complex junction. What is your response?$pg$,
 $pg$["Keep to a permitted direction and let it recalculate", "Stop in the middle of the junction to wait for a new instruction", "Change lane at the last moment to recover the correct direction"]$pg$::jsonb,
 $pg$A route mistake can be corrected later. Staying predictable and legal stops hesitation becoming an immediate danger.$pg$),
('c2a2c2b2-8000-4000-8000-000000000074','ar',
 $pg$يصمت نظام التوجيه قبل تقاطع معقد مباشرة. ما رد فعلك؟$pg$,
 $pg$["تحافظ بأمان على اتجاه مسموح وتترك النظام يعيد حساب المسار", "تتوقّف في وسط التقاطع لانتظار تعليمات جديدة", "تغيّر المسار في اللحظة الأخيرة لاستعادة الاتجاه الصحيح"]$pg$::jsonb,
 $pg$يمكن تصحيح خطأ الطريق لاحقًا. البقاء واضحًا وقانونيًا يمنع التردد من التحول إلى خطر فوري.$pg$),
('c2a2c2b2-8000-4000-8000-000000000075','en',
 $pg$Your destination is on the left but no safe gap opens in the traffic. What do you decide?$pg$,
 $pg$["Force your way quickly across several lanes", "Carry on and find a simpler route", "Block your lane while waiting a long time"]$pg$::jsonb,
 $pg$Reaching an address never justifies a forced path. A few minutes of detour cost less than a conflict across several lanes.$pg$),
('c2a2c2b2-8000-4000-8000-000000000075','ar',
 $pg$وجهتك إلى اليسار لكن لا تظهر فتحة آمنة في حركة السير. ماذا تقرر؟$pg$,
 $pg$["تعبر بسرعة عدة مسارات بالقوة", "تتابع وتبحث عن طريق أبسط", "تغلق مسارك وأنت تنتظر طويلًا"]$pg$::jsonb,
 $pg$الوصول إلى عنوان لا يبرر أبدًا مسارًا بالقوة. تكلف دقائق الالتفاف أقل من تعارض مع عدة مسارات.$pg$),
('c2a2c2b2-8000-4000-8000-000000000076','en',
 $pg$The signs and lanes at a large junction overwhelm you. Which decision gives you room?$pg$,
 $pg$["Follow the car ahead at random and assume it knows the correct exit", "Brake in the middle to think and read every sign without moving", "Keep your lane, choose a permitted direction and reorganise later"]$pg$::jsonb,
 $pg$Independence does not require the perfect route first time. It requires a safe, understandable decision that can be corrected.$pg$),
('c2a2c2b2-8000-4000-8000-000000000076','ar',
 $pg$تربكك اللافتات والمسارات في تقاطع كبير. أي قرار يمنحك هامشًا؟$pg$,
 $pg$["تتبع السيارة أمامك عشوائيًا وتفترض أنها تعرف المخرج الصحيح", "تفرمل في الوسط للتفكير وقراءة كل لافتة دون تقدم", "تبقى في مسارك وتختار اتجاهًا مسموحًا ثم تعيد التنظيم لاحقًا"]$pg$::jsonb,
 $pg$لا تتطلب الاستقلالية اختيار الطريق المثالي من المرة الأولى. بل تتطلب قرارًا آمنًا ومفهومًا وقابلًا للتصحيح.$pg$)
on conflict (question_id, lang) do nothing;
