-- Banque de certification, lot 1.
-- C1d à C1i passent de 6 à 12 questions jouables pour chaque boîte.
-- Les 36 questions ajoutées portent sur des gestes communs aux deux boîtes.

insert into public.questions_competence
  (id, competence_id, question, options, correct_index, explanation, difficulty, type, boite)
values
('c1d1c1e1-8000-4000-8000-000000000001','C1d',
 $pg$Tu veux quitter le bord du trottoir. Juste avant de bouger, tu contrôles quoi ?$pg$,
 $pg$["Les rétroviseurs puis l'angle mort du côté où tu pars", "Seulement le compteur", "Uniquement la voiture devant"]$pg$::jsonb,
 0,
 $pg$Un vélo ou une trottinette peut être caché à côté de la voiture. Le dernier regard direct couvre la zone que les rétroviseurs ne montrent pas.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000002','C1d',
 $pg$Tu es prêt à repartir après un arrêt. Quand enlèves-tu le frein à main ?$pg$,
 $pg$["Dès que le moteur tourne", "Quand la direction est choisie et que la voie est libre", "Après avoir accéléré fort"]$pg$::jsonb,
 1,
 $pg$Le frein à main reste ton verrou jusqu'au dernier moment. Tu le retires seulement quand la voiture est prête et que tes contrôles sont terminés.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000003','C1d',
 $pg$En côte, la voiture commence à reculer avant ton départ. Ton bon réflexe ?$pg$,
 $pg$["Appuyer beaucoup plus sur l'accélérateur", "La retenir seulement avec l'accélérateur", "Reprendre le frein ou le frein à main puis préparer le départ"]$pg$::jsonb,
 2,
 $pg$Le frein retient la voiture sans user la transmission. Une fois le départ préparé, tu libères le frein au moment où la voiture peut avancer.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000004','C1d',
 $pg$Tu approches du repère précis où tu dois t'arrêter. Comment finis-tu le freinage ?$pg$,
 $pg$["Tu freines progressivement puis tu allèges la pression sans la lâcher", "Tu gardes la même force jusqu'au blocage", "Tu relâches le frein dans le dernier mètre"]$pg$::jsonb,
 0,
 $pg$Alléger la pression absorbe le dernier mouvement de la voiture. Relâcher complètement la pédale la laisserait avancer au moment où tu cherches la précision.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000005','C1d',
 $pg$Tu restes immobilisé plus longtemps que prévu. Comment reposes-tu tes jambes sans laisser partir la voiture ?$pg$,
 $pg$["Tu gardes un peu d'accélérateur", "Tu serres le frein à main et places la boîte dans une position sûre", "Tu lâches toutes les commandes"]$pg$::jsonb,
 1,
 $pg$Pour un arrêt qui dure, la voiture doit tenir sans dépendre de tes pieds. Le frein à main et la position adaptée à ta boîte assurent cette immobilisation.$pg$,
 3,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000006','C1d',
 $pg$Au démarrage, la voiture fait un mouvement que tu n'attendais pas. Ton premier geste ?$pg$,
 $pg$["Tu accélères pour reprendre le contrôle", "Tu braques rapidement", "Tu maintiens le frein et immobilises la voiture avant de vérifier la boîte"]$pg$::jsonb,
 2,
 $pg$Un mouvement inattendu se coupe d'abord avec le frein. Une fois la voiture immobile, tu peux vérifier calmement le rapport ou la position sélectionnée.$pg$,
 3,'post_validation',null),

('c1d1c1e1-8000-4000-8000-000000000011','C1e',
 $pg$La tête de ton passager part en avant au moment où tu t'arrêtes. Que corriges-tu au prochain arrêt ?$pg$,
 $pg$["Tu allèges doucement le frein sur les derniers mètres", "Tu relâches la pédale d'un coup", "Tu freines plus tard et plus fort"]$pg$::jsonb,
 0,
 $pg$Le dernier à-coup vient souvent d'une pression trop forte jusqu'à l'immobilisation. Tu allèges progressivement tout en gardant assez de frein pour arrêter la voiture.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000012','C1e',
 $pg$Ta vitesse monte puis baisse sans arrêt sur une route plate. Comment la stabiliser ?$pg$,
 $pg$["Tu alternes accélérateur et frein", "Tu regardes loin et fais de petits mouvements avec le pied droit", "Tu bloques la cheville et appuies plus fort"]$pg$::jsonb,
 1,
 $pg$Un regard lointain évite de réagir à chaque petit changement. De faibles corrections du pied suffisent pour garder une allure régulière.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000013','C1e',
 $pg$Dans une descente, la voiture accélère alors que tu as levé le pied. Ton geste ?$pg$,
 $pg$["Tu passes au point mort", "Tu attends le bas de la pente", "Tu gardes la boîte engagée et freines progressivement"]$pg$::jsonb,
 2,
 $pg$La pente pousse la voiture même sans accélérateur. Une boîte engagée garde du frein moteur et une pression progressive sur le frein maîtrise l'allure.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000014','C1e',
 $pg$Un enfant surgit devant la voiture. Quel freinage ?$pg$,
 $pg$["Tu appuies franchement et tu maintiens le frein", "Tu commences par une pression très légère", "Tu pompes rapidement sur la pédale"]$pg$::jsonb,
 0,
 $pg$Le freinage doux sert aux arrêts anticipés. Face à un danger immédiat, chaque mètre compte : tu freines fort et tu gardes la pression.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000015','C1e',
 $pg$Tu dois passer rapidement de l'accélérateur au frein. Comment fait ton pied droit ?$pg$,
 $pg$["Il garde les deux pédales enfoncées", "Il quitte complètement l'accélérateur puis se déplace sur le frein", "Il reste entre les deux pédales"]$pg$::jsonb,
 1,
 $pg$Une seule pédale se commande à la fois avec le pied droit. Lever franchement le pied avant de le déplacer évite d'accélérer pendant le freinage.$pg$,
 3,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000016','C1e',
 $pg$La chaussée est mouillée et la voiture est chargée. Tu doses comme sur route sèche et voiture vide ?$pg$,
 $pg$["Oui, les pédales réagissent toujours pareil", "Oui, si les pneus sont récents", "Non, tu anticipes davantage et rends chaque pression plus progressive"]$pg$::jsonb,
 2,
 $pg$Le poids et le manque d'adhérence allongent la réponse de la voiture. Agir plus tôt laisse le temps de ralentir sans geste brutal.$pg$,
 3,'post_validation',null),

('c1d1c1e1-8000-4000-8000-000000000021','C1f',
 $pg$Pendant un demi-tour, tu veux passer de la marche arrière à la marche avant. Quand touches-tu à la boîte ?$pg$,
 $pg$["Quand la voiture est complètement immobile et le frein maintenu", "Pendant qu'elle roule encore doucement", "Dès que le volant est droit"]$pg$::jsonb,
 0,
 $pg$Changer de sens alors que les roues tournent encore force sur la transmission. L'arrêt complet protège la boîte et évite un départ dans la mauvaise direction.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000022','C1f',
 $pg$Tu descends une pente et veux passer au point mort pour laisser rouler la voiture. Bonne idée ?$pg$,
 $pg$["Oui, la voiture consomme toujours moins", "Non, tu gardes la boîte engagée pour conserver le frein moteur", "Oui, si la route est droite"]$pg$::jsonb,
 1,
 $pg$Au point mort, le moteur ne retient plus la voiture et les freins travaillent seuls. Garder un rapport ou une position de conduite aide à maîtriser la vitesse.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000023','C1f',
 $pg$Tu viens de choisir un rapport ou une position. Où va ta main ensuite ?$pg$,
 $pg$["Elle reste posée sur la commande", "Elle cherche le rapport suivant", "Elle revient sur le volant"]$pg$::jsonb,
 2,
 $pg$La commande n'a pas besoin d'être tenue. Les deux mains sur le volant donnent plus de précision et permettent de réagir immédiatement.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000024','C1f',
 $pg$Tu n'es plus certain de la direction sélectionnée. Que fais-tu avant de relâcher le frein ?$pg$,
 $pg$["Tu vérifies la position de la boîte pendant que la voiture reste immobile", "Tu accélères un peu pour tester", "Tu demandes à ton passager de deviner"]$pg$::jsonb,
 0,
 $pg$Une vérification à l'arrêt coûte une seconde. Tester avec l'accélérateur peut envoyer la voiture du mauvais côté sans te laisser le temps de corriger.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000025','C1f',
 $pg$La commande de boîte résiste au moment de sélectionner. Ton geste ?$pg$,
 $pg$["Tu forces jusqu'à ce qu'elle passe", "Tu gardes le frein, reviens à une position sûre et recommences sans forcer", "Tu accélères pour débloquer la boîte"]$pg$::jsonb,
 1,
 $pg$Une commande qui résiste signale souvent que la voiture ou une pédale n'est pas dans la bonne condition. Repartir d'une position sûre évite d'abîmer le mécanisme.$pg$,
 3,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000026','C1f',
 $pg$Un voyant de boîte s'allume et la voiture donne de gros à-coups. Tu fais quoi ?$pg$,
 $pg$["Tu continues jusqu'à ce que le voyant s'éteigne", "Tu changes plusieurs fois de position en roulant", "Tu t'arrêtes en sécurité et fais contrôler la voiture"]$pg$::jsonb,
 2,
 $pg$Un voyant accompagné d'à-coups peut annoncer un défaut de transmission. Insister risque d'aggraver la panne et de rendre la réaction de la voiture imprévisible.$pg$,
 3,'post_validation',null),

('c1d1c1e1-8000-4000-8000-000000000031','C1g',
 $pg$Tu vois une bosse sur le flanc d'un pneu avant de partir. Ton geste ?$pg$,
 $pg$["Tu ne pars pas et tu fais contrôler le pneu", "Tu roules doucement jusqu'au prochain plein", "Tu ajoutes beaucoup d'air"]$pg$::jsonb,
 0,
 $pg$Une bosse peut cacher des fibres internes abîmées. Le pneu risque de se déformer davantage ou d'éclater sous l'effet de la vitesse.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000032','C1g',
 $pg$Tu veux connaître la bonne pression des pneus. Où la cherches-tu ?$pg$,
 $pg$["Sur le pneu de la voiture voisine", "Sur l'étiquette du véhicule ou dans son manuel", "Sur le ticket de carburant"]$pg$::jsonb,
 1,
 $pg$La pression dépend du véhicule et de sa charge. Le constructeur l'indique souvent dans l'encadrement de porte, la trappe à carburant ou le manuel.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000033','C1g',
 $pg$Les feux et la plaque arrière sont couverts de boue. Tu pars quand même de jour ?$pg$,
 $pg$["Oui, la pluie les nettoiera", "Oui, les feux servent seulement la nuit", "Non, tu les nettoies avant de rouler"]$pg$::jsonb,
 2,
 $pg$Des feux sales se voient moins quand tu freines ou changes de direction. Une plaque propre reste lisible et évite de masquer l'identité du véhicule.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000034','C1g',
 $pg$Tu dois vérifier le liquide de refroidissement. Dans quelles conditions ?$pg$,
 $pg$["Moteur froid, en lisant le niveau entre les repères", "Juste après un long trajet, bouchon ouvert", "Moteur chaud, bouchon ouvert"]$pg$::jsonb,
 0,
 $pg$À chaud, le circuit est sous pression et peut projeter du liquide brûlant. Moteur froid, le niveau se lit sans danger entre les marques du réservoir.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000035','C1g',
 $pg$Tu es seul et veux vérifier tes feux stop. Quelle solution utile ?$pg$,
 $pg$["Tu regardes le tableau de bord", "Tu utilises leur reflet sur un mur ou une vitrine", "Tu allumes les feux de détresse"]$pg$::jsonb,
 1,
 $pg$Le reflet permet de voir si les feux réagissent quand tu appuies sur le frein. Avec une autre personne, le contrôle direct reste encore plus simple.$pg$,
 3,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000036','C1g',
 $pg$Une flaque inhabituelle apparaît sous la voiture avant ton départ. Que fais-tu ?$pg$,
 $pg$["Tu démarres pour voir si elle disparaît", "Tu la recouvres avec de l'eau", "Tu cherches son origine et signales la fuite avant de rouler"]$pg$::jsonb,
 2,
 $pg$Une fuite peut concerner le refroidissement, l'huile ou le freinage. L'identifier avant de partir évite de découvrir une perte dangereuse en circulation.$pg$,
 3,'post_validation',null),

('c1d1c1e1-8000-4000-8000-000000000041','C1h',
 $pg$La caméra de recul montre une image nette. Tu peux manœuvrer en regardant seulement l'écran ?$pg$,
 $pg$["Non, tu alternes vision directe, rétroviseurs et écran", "Oui, l'écran montre tout", "Oui, si la voiture émet des bips"]$pg$::jsonb,
 0,
 $pg$La caméra ne montre ni tous les côtés ni ce qui arrive hors de son cadre. Elle complète tes contrôles, elle ne remplace jamais le regard autour de la voiture.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000042','C1h',
 $pg$Tu recules en braquant à droite. Quelle partie de la voiture peut balayer vers la gauche ?$pg$,
 $pg$["Seulement la roue arrière droite", "L'avant de la voiture", "Aucune partie"]$pg$::jsonb,
 1,
 $pg$Quand l'arrière tourne d'un côté, l'avant se déporte de l'autre. Contrôler ce coin évite de toucher un mur, un poteau ou une voiture voisine.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000043','C1h',
 $pg$Un piéton s'approche derrière toi pendant une marche arrière. Ton geste ?$pg$,
 $pg$["Tu continues car tes feux de recul sont allumés", "Tu klaxonnes et poursuis", "Tu t'arrêtes, tu le laisses passer puis tu contrôles de nouveau"]$pg$::jsonb,
 2,
 $pg$Un piéton peut changer de direction ou ne pas entendre la voiture. L'arrêt supprime le risque, puis un nouveau contrôle confirme que la zone est libre.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000044','C1h',
 $pg$La rue est trop étroite pour finir ton demi-tour en trois mouvements. Que fais-tu ?$pg$,
 $pg$["Tu ajoutes des mouvements en contrôlant à chaque fois", "Tu montes sur le trottoir pour gagner de la place", "Tu accélères pour braquer plus vite"]$pg$::jsonb,
 0,
 $pg$Le nombre de mouvements dépend de l'espace disponible. Une étape de plus est normale si elle garde la voiture loin des obstacles et des autres usagers.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000045','C1h',
 $pg$Tu entres de travers dans une place en bataille et il reste de l'espace. Ton meilleur choix ?$pg$,
 $pg$["Tu termines vite en espérant être dans les lignes", "Tu t'arrêtes, te replaces et reprends avec de nouveaux contrôles", "Tu regardes seulement la voiture de gauche"]$pg$::jsonb,
 1,
 $pg$Une correction lente vaut mieux qu'une trajectoire forcée. Chaque changement de sens commence par un arrêt et un nouveau tour du regard.$pg$,
 3,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000046','C1h',
 $pg$Tu as vu un enfant près de la voiture puis tu ne le vois plus pendant la manœuvre. Que fais-tu ?$pg$,
 $pg$["Tu continues au pas", "Tu te fies aux capteurs", "Tu t'arrêtes jusqu'à savoir exactement où il est"]$pg$::jsonb,
 2,
 $pg$Perdre de vue un usager vulnérable signifie perdre la certitude que la zone est libre. La voiture reste immobile tant que sa position n'est pas connue.$pg$,
 3,'post_validation',null),

('c1d1c1e1-8000-4000-8000-000000000051','C1i',
 $pg$La place paraît à peine plus longue que ta voiture. Quel choix montre le plus d'autonomie ?$pg$,
 $pg$["Chercher une place avec une marge suffisante", "Essayer quand même pour prouver ton niveau", "Attendre que quelqu'un te guide"]$pg$::jsonb,
 0,
 $pg$Être autonome, c'est aussi renoncer à une solution fragile. Une marge devant et derrière permet de manœuvrer sans toucher les autres véhicules.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000052','C1i',
 $pg$On te demande de te garer dès que possible. Qui choisit l'emplacement et prépare la manœuvre ?$pg$,
 $pg$["La voiture derrière toi", "Toi, après avoir vérifié que la place est autorisée et adaptée", "Ton passager, geste par geste"]$pg$::jsonb,
 1,
 $pg$Une consigne générale te laisse la décision. Tu lis la signalisation, évalues l'espace puis annonces ton intention avant de ralentir.$pg$,
 1,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000053','C1i',
 $pg$Ta voiture est garée mais mal alignée alors qu'une correction reste possible en sécurité. Que fais-tu ?$pg$,
 $pg$["Tu la laisses ainsi pour ne pas montrer ton erreur", "Tu demandes qu'on tourne le volant pour toi", "Tu contrôles autour puis tu corriges lentement"]$pg$::jsonb,
 2,
 $pg$Détecter un mauvais alignement et le corriger fait partie de l'autonomie. Le nouveau mouvement demande les mêmes contrôles que le premier.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000054','C1i',
 $pg$Un véhicule arrive pendant que tu décides de ta correction. Que fais-tu ?$pg$,
 $pg$["Tu restes immobile, tu le laisses passer puis tu réévalues la situation", "Tu commences vite avant qu'il approche", "Tu lui fais signe de contourner"]$pg$::jsonb,
 0,
 $pg$Une situation qui change demande une nouvelle décision. Laisser passer libère l'espace et t'évite de poursuivre un plan devenu dangereux.$pg$,
 2,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000055','C1i',
 $pg$Tu viens de dépasser l'entrée où tu voulais manœuvrer. Ton choix autonome ?$pg$,
 $pg$["Tu recules aussitôt sur la chaussée", "Tu continues et cherches un endroit sûr pour revenir", "Tu t'arrêtes au milieu de la voie"]$pg$::jsonb,
 1,
 $pg$Rater une entrée n'est pas un danger. Une marche arrière improvisée peut l'être, alors tu poursuis calmement et reconstruis un trajet sûr.$pg$,
 3,'post_validation',null),
('c1d1c1e1-8000-4000-8000-000000000056','C1i',
 $pg$Tu penses avoir fini ta manœuvre. Quel dernier geste confirme que tu peux quitter les commandes ?$pg$,
 $pg$["Tu coupes le moteur en roulant encore", "Tu ouvres la porte pour vérifier les lignes", "Tu immobilises la voiture, la sécurises puis contrôles qu'elle ne gêne personne"]$pg$::jsonb,
 2,
 $pg$Une manœuvre se termine avec une voiture stable et correctement placée. La sécuriser évite tout départ involontaire après avoir relâché les pédales.$pg$,
 3,'post_validation',null)
on conflict (id) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c1d1c1e1-8000-4000-8000-000000000001','en',
 $pg$You are about to pull away from the kerb. What do you check just before moving?$pg$,
 $pg$["The mirrors, then the blind spot on the side you are moving into", "Only the speedometer", "Only the car ahead"]$pg$::jsonb,
 $pg$A bicycle or scooter can be hidden beside the car. The final direct look covers the area that the mirrors do not show.$pg$),
('c1d1c1e1-8000-4000-8000-000000000001','ar',
 $pg$تريد مغادرة جانب الرصيف. ماذا تراقب قبل أن تتحرّك مباشرة؟$pg$,
 $pg$["المرايا ثم الزاوية الميتة في جهة انطلاقك", "عدّاد السرعة فقط", "السيارة أمامك فقط"]$pg$::jsonb,
 $pg$قد تختبئ دراجة أو سكوتر بجانب السيارة. النظرة المباشرة الأخيرة تغطي المنطقة التي لا تظهرها المرايا.$pg$),
('c1d1c1e1-8000-4000-8000-000000000002','en',
 $pg$You are ready to move off after stopping. When do you release the handbrake?$pg$,
 $pg$["As soon as the engine is running", "When the direction is selected and the road is clear", "After accelerating hard"]$pg$::jsonb,
 $pg$The handbrake remains your lock until the last moment. You release it only when the car is ready and your checks are complete.$pg$),
('c1d1c1e1-8000-4000-8000-000000000002','ar',
 $pg$أنت جاهز للانطلاق بعد توقّف. متى تحرّر فرامل اليد؟$pg$,
 $pg$["بمجرد أن يعمل المحرك", "عندما تختار الاتجاه ويصبح الطريق خاليًا", "بعد الضغط بقوة على دواسة الوقود"]$pg$::jsonb,
 $pg$تبقى فرامل اليد قفل الأمان حتى اللحظة الأخيرة. لا تحرّرها إلا عندما تصبح السيارة جاهزة وتنتهي من المراقبة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000003','en',
 $pg$On a hill, the car starts to roll back before you move off. What is the right response?$pg$,
 $pg$["Press the accelerator much harder", "Hold it only with the accelerator", "Apply the brake or handbrake again, then prepare to move off"]$pg$::jsonb,
 $pg$The brake holds the car without wearing the transmission. Once you are ready to move, release the brake when the car can go forward.$pg$),
('c1d1c1e1-8000-4000-8000-000000000003','ar',
 $pg$على طريق صاعد، تبدأ السيارة بالرجوع قبل انطلاقك. ما التصرّف الصحيح؟$pg$,
 $pg$["تضغط دواسة الوقود بقوة أكبر", "تثبتها بدواسة الوقود فقط", "تستعمل الفرامل أو فرامل اليد من جديد ثم تجهّز الانطلاق"]$pg$::jsonb,
 $pg$تثبت الفرامل السيارة دون إهلاك ناقل الحركة. وبعد تجهيز الانطلاق، تحرّر الفرامل عندما تصبح السيارة قادرة على التقدّم.$pg$),
('c1d1c1e1-8000-4000-8000-000000000004','en',
 $pg$You are approaching the exact marker where you must stop. How do you finish braking?$pg$,
 $pg$["Brake progressively, then ease the pressure without letting go", "Keep the same force until the car jolts", "Release the brake over the last metre"]$pg$::jsonb,
 $pg$Easing the pressure absorbs the car's final movement. Releasing the pedal completely would let it move just when you need precision.$pg$),
('c1d1c1e1-8000-4000-8000-000000000004','ar',
 $pg$تقترب من العلامة الدقيقة التي يجب أن تتوقّف عندها. كيف تنهي الفرملة؟$pg$,
 $pg$["تفرمل تدريجيًا ثم تخفّف الضغط دون أن ترفع قدمك", "تبقي القوة نفسها حتى تهتز السيارة", "تحرّر الفرامل في المتر الأخير"]$pg$::jsonb,
 $pg$تخفيف الضغط يمتص الحركة الأخيرة للسيارة. أما رفع القدم تمامًا فيجعلها تتقدّم في اللحظة التي تحتاج فيها إلى الدقة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000005','en',
 $pg$You remain stopped longer than expected. How do you rest your legs without letting the car move?$pg$,
 $pg$["Keep a little accelerator on", "Apply the handbrake and put the gearbox in a safe position", "Release every control"]$pg$::jsonb,
 $pg$For a longer stop, the car must stay still without relying on your feet. The handbrake and the position suited to your gearbox secure it.$pg$),
('c1d1c1e1-8000-4000-8000-000000000005','ar',
 $pg$تبقى متوقّفًا مدة أطول من المتوقع. كيف تريح ساقيك دون أن تتحرّك السيارة؟$pg$,
 $pg$["تبقي قليلًا من الضغط على دواسة الوقود", "تشدّ فرامل اليد وتضع ناقل الحركة في وضع آمن", "تترك كل أدوات التحكم"]$pg$::jsonb,
 $pg$في التوقّف الطويل، يجب أن تبقى السيارة ثابتة دون الاعتماد على قدميك. فرامل اليد والوضع المناسب لناقل الحركة يضمنان ثباتها.$pg$),
('c1d1c1e1-8000-4000-8000-000000000006','en',
 $pg$As you start, the car moves in a way you did not expect. What do you do first?$pg$,
 $pg$["Accelerate to regain control", "Turn the wheel quickly", "Keep the brake on and stop the car before checking the gearbox"]$pg$::jsonb,
 $pg$The brake stops an unexpected movement first. Once the car is still, you can calmly check the selected gear or position.$pg$),
('c1d1c1e1-8000-4000-8000-000000000006','ar',
 $pg$عند الانطلاق، تتحرّك السيارة بطريقة لم تتوقعها. ما أول تصرّف؟$pg$,
 $pg$["تسرّع لاستعادة التحكم", "تدير المقود بسرعة", "تبقي الفرامل مضغوطة وتوقف السيارة قبل فحص ناقل الحركة"]$pg$::jsonb,
 $pg$الفرامل توقف الحركة غير المتوقعة أولًا. وبعد ثبات السيارة يمكنك فحص السرعة أو الوضع المختار بهدوء.$pg$),

('c1d1c1e1-8000-4000-8000-000000000011','en',
 $pg$Your passenger's head tips forward as you stop. What do you change at the next stop?$pg$,
 $pg$["Ease the brake gently over the final metres", "Release the pedal suddenly", "Brake later and harder"]$pg$::jsonb,
 $pg$The final jolt often comes from keeping too much pressure until the car stops. Ease it progressively while keeping enough brake to stop the car.$pg$),
('c1d1c1e1-8000-4000-8000-000000000011','ar',
 $pg$يميل رأس الراكب إلى الأمام لحظة توقّفك. ماذا تصحّح في التوقّف التالي؟$pg$,
 $pg$["تخفّف الفرامل بلطف في الأمتار الأخيرة", "ترفع قدمك فجأة عن الدواسة", "تفرمل متأخرًا وبقوة أكبر"]$pg$::jsonb,
 $pg$تأتي الهزّة الأخيرة غالبًا من ضغط قوي حتى توقّف السيارة. خفّف الضغط تدريجيًا مع إبقاء قوة كافية لإيقافها.$pg$),
('c1d1c1e1-8000-4000-8000-000000000012','en',
 $pg$Your speed keeps rising and falling on a level road. How do you steady it?$pg$,
 $pg$["Alternate between accelerator and brake", "Look far ahead and make small movements with your right foot", "Lock your ankle and press harder"]$pg$::jsonb,
 $pg$Looking far ahead stops you reacting to every small change. Tiny corrections with your foot are enough to keep a steady speed.$pg$),
('c1d1c1e1-8000-4000-8000-000000000012','ar',
 $pg$ترتفع سرعتك وتنخفض باستمرار على طريق مستوٍ. كيف تثبّتها؟$pg$,
 $pg$["تنتقل بالتناوب بين الوقود والفرامل", "تنظر بعيدًا وتحرك قدمك اليمنى حركات صغيرة", "تثبت كاحلك وتضغط بقوة أكبر"]$pg$::jsonb,
 $pg$النظر بعيدًا يمنعك من التفاعل مع كل تغيّر صغير. تكفي تعديلات خفيفة بالقدم للحفاظ على سرعة ثابتة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000013','en',
 $pg$On a descent, the car speeds up even though you have lifted off. What do you do?$pg$,
 $pg$["Shift to neutral", "Wait until the bottom of the hill", "Keep the gearbox engaged and brake progressively"]$pg$::jsonb,
 $pg$The slope pushes the car even without the accelerator. An engaged gearbox provides engine braking, and progressive brake pressure controls the speed.$pg$),
('c1d1c1e1-8000-4000-8000-000000000013','ar',
 $pg$في نزول، تزداد سرعة السيارة رغم رفع قدمك عن دواسة الوقود. ماذا تفعل؟$pg$,
 $pg$["تضع ناقل الحركة في الوضع المحايد", "تنتظر حتى نهاية النزول", "تبقي ناقل الحركة موصولًا وتفرمل تدريجيًا"]$pg$::jsonb,
 $pg$يدفع المنحدر السيارة حتى دون ضغط الوقود. إبقاء ناقل الحركة موصولًا يوفر فرملة المحرك، والضغط التدريجي على الفرامل يضبط السرعة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000014','en',
 $pg$A child runs out in front of the car. How do you brake?$pg$,
 $pg$["Press firmly and keep the brake applied", "Start with very light pressure", "Pump the pedal quickly"]$pg$::jsonb,
 $pg$Gentle braking is for anticipated stops. With an immediate danger, every metre matters: brake hard and keep the pressure on.$pg$),
('c1d1c1e1-8000-4000-8000-000000000014','ar',
 $pg$يظهر طفل فجأة أمام السيارة. كيف تفرمل؟$pg$,
 $pg$["تضغط بقوة وتبقي الفرامل مضغوطة", "تبدأ بضغط خفيف جدًا", "تضغط الدواسة وترفعها بسرعة متكررة"]$pg$::jsonb,
 $pg$الفرملة اللطيفة للتوقّفات المتوقعة. أمام خطر فوري، لكل متر أهميته: افرمل بقوة وحافظ على الضغط.$pg$),
('c1d1c1e1-8000-4000-8000-000000000015','en',
 $pg$You need to move quickly from the accelerator to the brake. How does your right foot do it?$pg$,
 $pg$["It keeps both pedals pressed", "It comes fully off the accelerator, then moves to the brake", "It stays between both pedals"]$pg$::jsonb,
 $pg$Your right foot operates one pedal at a time. Lifting it fully before moving across prevents you from accelerating while braking.$pg$),
('c1d1c1e1-8000-4000-8000-000000000015','ar',
 $pg$تحتاج إلى الانتقال بسرعة من دواسة الوقود إلى الفرامل. كيف تتحرّك قدمك اليمنى؟$pg$,
 $pg$["تبقي الدواستين مضغوطتين", "ترتفع تمامًا عن دواسة الوقود ثم تنتقل إلى الفرامل", "تبقى بين الدواستين"]$pg$::jsonb,
 $pg$تتحكم قدمك اليمنى في دواسة واحدة كل مرة. رفعها تمامًا قبل نقلها يمنع التسارع أثناء الفرملة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000016','en',
 $pg$The road is wet and the car is loaded. Do you use the pedals as if the road were dry and the car empty?$pg$,
 $pg$["Yes, the pedals always react the same way", "Yes, if the tyres are recent", "No, act earlier and make every press more progressive"]$pg$::jsonb,
 $pg$Extra weight and less grip make the car respond more slowly. Acting earlier gives it time to slow down without a sudden input.$pg$),
('c1d1c1e1-8000-4000-8000-000000000016','ar',
 $pg$الطريق مبلل والسيارة محمّلة. هل تستعمل الدواسات كما لو كان الطريق جافًا والسيارة فارغة؟$pg$,
 $pg$["نعم، تستجيب الدواسات بالطريقة نفسها دائمًا", "نعم، إذا كانت الإطارات حديثة", "لا، تتصرف أبكر وتجعل كل ضغط أكثر تدرّجًا"]$pg$::jsonb,
 $pg$يزيد الوزن وتقلّ قوة التماسك فتستجيب السيارة ببطء أكبر. التصرف المبكر يمنحها وقتًا للتباطؤ دون حركة مفاجئة.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c1d1c1e1-8000-4000-8000-000000000021','en',
 $pg$During a U turn, you want to switch from reverse to forward. When do you operate the gearbox?$pg$,
 $pg$["When the car is completely still and the brake is held", "While it is still rolling slowly", "As soon as the wheel is straight"]$pg$::jsonb,
 $pg$Changing direction while the wheels are still turning strains the transmission. A complete stop protects the gearbox and prevents a move in the wrong direction.$pg$),
('c1d1c1e1-8000-4000-8000-000000000021','ar',
 $pg$أثناء الدوران للعودة، تريد الانتقال من الرجوع إلى التقدّم. متى تستعمل ناقل الحركة؟$pg$,
 $pg$["عندما تتوقف السيارة تمامًا وتبقي الفرامل مضغوطة", "بينما لا تزال تتحرّك ببطء", "بمجرد أن يصبح المقود مستقيمًا"]$pg$::jsonb,
 $pg$تغيير الاتجاه والعجلات لا تزال تدور يضغط على ناقل الحركة. التوقّف التام يحميه ويمنع حركة في الاتجاه الخطأ.$pg$),
('c1d1c1e1-8000-4000-8000-000000000022','en',
 $pg$You are going downhill and want to select neutral so the car can coast. Good idea?$pg$,
 $pg$["Yes, the car always uses less fuel", "No, keep the gearbox engaged to retain engine braking", "Yes, if the road is straight"]$pg$::jsonb,
 $pg$In neutral, the engine no longer holds the car back and the brakes work alone. Keeping a gear or drive position selected helps control the speed.$pg$),
('c1d1c1e1-8000-4000-8000-000000000022','ar',
 $pg$تنزل منحدرًا وتريد وضع ناقل الحركة في الحياد لتترك السيارة تسير وحدها. هل هذه فكرة جيدة؟$pg$,
 $pg$["نعم، تستهلك السيارة وقودًا أقل دائمًا", "لا، تبقي ناقل الحركة موصولًا للاستفادة من فرملة المحرك", "نعم، إذا كان الطريق مستقيمًا"]$pg$::jsonb,
 $pg$في الوضع المحايد، لا يعود المحرك يخفف سرعة السيارة وتعمل الفرامل وحدها. إبقاء سرعة أو وضع السير مختارًا يساعدك على التحكم في السرعة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000023','en',
 $pg$You have just selected a gear or position. Where does your hand go next?$pg$,
 $pg$["It stays on the control", "It looks for the next gear", "It returns to the steering wheel"]$pg$::jsonb,
 $pg$The control does not need to be held. Two hands on the wheel give you more precision and let you react immediately.$pg$),
('c1d1c1e1-8000-4000-8000-000000000023','ar',
 $pg$اخترت للتو سرعة أو وضعًا في ناقل الحركة. أين تضع يدك بعد ذلك؟$pg$,
 $pg$["تبقى على أداة التحكم", "تبحث عن السرعة التالية", "تعود إلى المقود"]$pg$::jsonb,
 $pg$لا تحتاج أداة التحكم إلى أن تبقى ممسوكة. وضع اليدين على المقود يمنحك دقة أكبر ويسمح برد فعل فوري.$pg$),
('c1d1c1e1-8000-4000-8000-000000000024','en',
 $pg$You are no longer sure which direction is selected. What do you do before releasing the brake?$pg$,
 $pg$["Check the gearbox position while the car remains still", "Accelerate a little to test it", "Ask your passenger to guess"]$pg$::jsonb,
 $pg$A check while stopped takes one second. Testing with the accelerator can send the car the wrong way before you have time to correct.$pg$),
('c1d1c1e1-8000-4000-8000-000000000024','ar',
 $pg$لم تعد متأكدًا من الاتجاه المختار. ماذا تفعل قبل تحرير الفرامل؟$pg$,
 $pg$["تفحص وضع ناقل الحركة والسيارة ثابتة", "تسرّع قليلًا لتجرب", "تطلب من الراكب أن يخمّن"]$pg$::jsonb,
 $pg$يستغرق الفحص أثناء التوقّف ثانية واحدة. أما التجربة بدواسة الوقود فقد تدفع السيارة في الاتجاه الخطأ قبل أن تتمكن من التصحيح.$pg$),
('c1d1c1e1-8000-4000-8000-000000000025','en',
 $pg$The gearbox control resists when you try to select. What do you do?$pg$,
 $pg$["Force it until it engages", "Hold the brake, return to a safe position and try again without force", "Accelerate to release the gearbox"]$pg$::jsonb,
 $pg$A resistant control often means that the car or a pedal is not in the right condition. Starting again from a safe position avoids damaging the mechanism.$pg$),
('c1d1c1e1-8000-4000-8000-000000000025','ar',
 $pg$تقاوم أداة ناقل الحركة عند محاولة الاختيار. ماذا تفعل؟$pg$,
 $pg$["تجبرها حتى تستجيب", "تبقي الفرامل وتعود إلى وضع آمن ثم تحاول دون قوة", "تسرّع لتحرير ناقل الحركة"]$pg$::jsonb,
 $pg$مقاومة الأداة تعني غالبًا أن السيارة أو إحدى الدواسات ليست في الوضع المناسب. البدء من وضع آمن يمنع إتلاف الآلية.$pg$),
('c1d1c1e1-8000-4000-8000-000000000026','en',
 $pg$A gearbox warning light comes on and the car starts jolting badly. What do you do?$pg$,
 $pg$["Carry on until the light goes out", "Change position several times while driving", "Stop safely and have the car checked"]$pg$::jsonb,
 $pg$A warning light with jolts can indicate a transmission fault. Carrying on may worsen the fault and make the car's response unpredictable.$pg$),
('c1d1c1e1-8000-4000-8000-000000000026','ar',
 $pg$يضيء تحذير ناقل الحركة وتبدأ السيارة بالاهتزاز بقوة. ماذا تفعل؟$pg$,
 $pg$["تتابع حتى ينطفئ التحذير", "تغيّر الوضع عدة مرات أثناء السير", "تتوقّف بأمان وتطلب فحص السيارة"]$pg$::jsonb,
 $pg$قد يدل التحذير المصحوب بهزّات على عطل في ناقل الحركة. الاستمرار قد يزيد العطل ويجعل استجابة السيارة غير متوقعة.$pg$),

('c1d1c1e1-8000-4000-8000-000000000031','en',
 $pg$You see a bulge on a tyre sidewall before setting off. What do you do?$pg$,
 $pg$["Do not set off and have the tyre checked", "Drive slowly until the next fuel stop", "Add a lot of air"]$pg$::jsonb,
 $pg$A bulge can hide damaged internal cords. The tyre may deform further or burst under the effects of speed.$pg$),
('c1d1c1e1-8000-4000-8000-000000000031','ar',
 $pg$ترى انتفاخًا على جانب إطار قبل الانطلاق. ماذا تفعل؟$pg$,
 $pg$["لا تنطلق وتطلب فحص الإطار", "تقود ببطء حتى محطة الوقود التالية", "تضيف كمية كبيرة من الهواء"]$pg$::jsonb,
 $pg$قد يخفي الانتفاخ تلفًا في الألياف الداخلية. ويمكن أن يتشوّه الإطار أكثر أو ينفجر بفعل السرعة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000032','en',
 $pg$You want to find the correct tyre pressure. Where do you look?$pg$,
 $pg$["On the car next to you", "On the vehicle label or in its handbook", "On the fuel receipt"]$pg$::jsonb,
 $pg$Pressure depends on the vehicle and its load. The manufacturer often lists it in the door frame, inside the fuel flap or in the handbook.$pg$),
('c1d1c1e1-8000-4000-8000-000000000032','ar',
 $pg$تريد معرفة ضغط الإطارات الصحيح. أين تبحث عنه؟$pg$,
 $pg$["على إطار السيارة المجاورة", "على ملصق السيارة أو في دليلها", "على إيصال الوقود"]$pg$::jsonb,
 $pg$يعتمد الضغط على السيارة وحمولتها. تضع الشركة المصنّعة القيمة غالبًا على إطار الباب أو داخل غطاء الوقود أو في الدليل.$pg$),
('c1d1c1e1-8000-4000-8000-000000000033','en',
 $pg$The rear lights and number plate are covered in mud. Do you set off anyway in daylight?$pg$,
 $pg$["Yes, the rain will clean them", "Yes, lights are only used at night", "No, clean them before driving"]$pg$::jsonb,
 $pg$Dirty lights are harder to see when you brake or change direction. A clean plate remains readable and does not hide the vehicle's identity.$pg$),
('c1d1c1e1-8000-4000-8000-000000000033','ar',
 $pg$الأضواء الخلفية ولوحة التسجيل مغطّاة بالطين. هل تنطلق رغم ذلك نهارًا؟$pg$,
 $pg$["نعم، سيغسلها المطر", "نعم، لا تستعمل الأضواء إلا ليلًا", "لا، تنظفها قبل القيادة"]$pg$::jsonb,
 $pg$تقلّ رؤية الأضواء المتسخة عند الفرملة أو تغيير الاتجاه. وتبقى اللوحة النظيفة مقروءة ولا تخفي هوية السيارة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000034','en',
 $pg$You need to check the coolant. In what conditions?$pg$,
 $pg$["With the engine cold, reading the level between the marks", "Just after a long drive, with the cap open", "With the engine hot and the cap open"]$pg$::jsonb,
 $pg$When hot, the system is pressurised and can spray scalding liquid. With the engine cold, you can safely read the level between the reservoir marks.$pg$),
('c1d1c1e1-8000-4000-8000-000000000034','ar',
 $pg$تحتاج إلى فحص سائل التبريد. في أي ظروف تفعل ذلك؟$pg$,
 $pg$["عندما يكون المحرك باردًا مع قراءة المستوى بين العلامتين", "بعد رحلة طويلة مباشرة مع فتح السدادة", "عندما يكون المحرك ساخنًا والسدادة مفتوحة"]$pg$::jsonb,
 $pg$تكون الدارة مضغوطة وهي ساخنة وقد تقذف سائلًا حارقًا. والمحرك بارد، تقرأ المستوى بأمان بين علامتي الخزان.$pg$),
('c1d1c1e1-8000-4000-8000-000000000035','en',
 $pg$You are alone and want to check your brake lights. What is a useful solution?$pg$,
 $pg$["Look at the dashboard", "Use their reflection on a wall or shop window", "Switch on the hazard lights"]$pg$::jsonb,
 $pg$The reflection shows whether the lights respond when you press the brake. With another person, a direct check is even simpler.$pg$),
('c1d1c1e1-8000-4000-8000-000000000035','ar',
 $pg$أنت وحدك وتريد فحص أضواء الفرامل. ما الحل المفيد؟$pg$,
 $pg$["تنظر إلى لوحة القيادة", "تستعمل انعكاسها على جدار أو واجهة متجر", "تشغّل أضواء الخطر"]$pg$::jsonb,
 $pg$يُظهر الانعكاس إن كانت الأضواء تستجيب عند ضغط الفرامل. ومع شخص آخر يكون الفحص المباشر أبسط.$pg$),
('c1d1c1e1-8000-4000-8000-000000000036','en',
 $pg$An unusual puddle appears under the car before you set off. What do you do?$pg$,
 $pg$["Start the engine to see if it disappears", "Cover it with water", "Find its source and report the leak before driving"]$pg$::jsonb,
 $pg$A leak may involve coolant, oil or the brakes. Identifying it before setting off prevents a dangerous loss from appearing in traffic.$pg$),
('c1d1c1e1-8000-4000-8000-000000000036','ar',
 $pg$تظهر بقعة سائل غير معتادة تحت السيارة قبل انطلاقك. ماذا تفعل؟$pg$,
 $pg$["تشغّل المحرك لترى إن كانت ستختفي", "تغطيها بالماء", "تبحث عن مصدرها وتبلّغ عن التسرّب قبل القيادة"]$pg$::jsonb,
 $pg$قد يكون التسرّب من سائل التبريد أو الزيت أو الفرامل. اكتشافه قبل الانطلاق يمنع حدوث فقدان خطير أثناء السير.$pg$)
on conflict (question_id, lang) do nothing;

insert into public.question_translations
  (question_id, lang, question, options, explanation)
values
('c1d1c1e1-8000-4000-8000-000000000041','en',
 $pg$The reversing camera shows a clear image. Can you manoeuvre by looking only at the screen?$pg$,
 $pg$["No, alternate between direct vision, mirrors and the screen", "Yes, the screen shows everything", "Yes, if the car beeps"]$pg$::jsonb,
 $pg$The camera shows neither every side nor anything approaching outside its frame. It adds to your checks but never replaces looking around the car.$pg$),
('c1d1c1e1-8000-4000-8000-000000000041','ar',
 $pg$تعرض كاميرا الرجوع صورة واضحة. هل يمكنك المناورة بالنظر إلى الشاشة فقط؟$pg$,
 $pg$["لا، تتناوب بين الرؤية المباشرة والمرايا والشاشة", "نعم، تعرض الشاشة كل شيء", "نعم، إذا أصدرت السيارة صفيرًا"]$pg$::jsonb,
 $pg$لا تعرض الكاميرا كل الجوانب ولا ما يقترب من خارج إطارها. إنها تكمل مراقبتك ولا تعوّض أبدًا النظر حول السيارة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000042','en',
 $pg$You reverse while steering to the right. Which part of the car can swing to the left?$pg$,
 $pg$["Only the right rear wheel", "The front of the car", "No part of it"]$pg$::jsonb,
 $pg$When the rear turns one way, the front swings the other way. Checking that corner prevents contact with a wall, post or nearby car.$pg$),
('c1d1c1e1-8000-4000-8000-000000000042','ar',
 $pg$ترجع للخلف مع إدارة المقود إلى اليمين. أي جزء من السيارة قد ينحرف إلى اليسار؟$pg$,
 $pg$["العجلة الخلفية اليمنى فقط", "مقدمة السيارة", "لا ينحرف أي جزء"]$pg$::jsonb,
 $pg$عندما يدور الخلف إلى جهة، تنحرف المقدمة إلى الجهة الأخرى. مراقبة هذه الزاوية تمنع لمس جدار أو عمود أو سيارة مجاورة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000043','en',
 $pg$A pedestrian approaches behind you while you are reversing. What do you do?$pg$,
 $pg$["Carry on because your reversing lights are on", "Sound the horn and continue", "Stop, let them pass, then check again"]$pg$::jsonb,
 $pg$A pedestrian may change direction or fail to hear the car. Stopping removes the risk, then a fresh check confirms that the area is clear.$pg$),
('c1d1c1e1-8000-4000-8000-000000000043','ar',
 $pg$يقترب أحد المشاة خلفك أثناء الرجوع. ماذا تفعل؟$pg$,
 $pg$["تتابع لأن أضواء الرجوع مضاءة", "تستعمل المنبّه وتتابع", "تتوقّف وتتركه يمر ثم تراقب من جديد"]$pg$::jsonb,
 $pg$قد يغيّر المشاة اتجاهه أو لا يسمع السيارة. التوقّف يزيل الخطر، ثم تؤكد مراقبة جديدة أن المنطقة أصبحت خالية.$pg$),
('c1d1c1e1-8000-4000-8000-000000000044','en',
 $pg$The street is too narrow to finish your U turn in three moves. What do you do?$pg$,
 $pg$["Add more moves and check each time", "Mount the kerb to gain space", "Accelerate to steer faster"]$pg$::jsonb,
 $pg$The number of moves depends on the available space. One more step is normal if it keeps the car clear of obstacles and other road users.$pg$),
('c1d1c1e1-8000-4000-8000-000000000044','ar',
 $pg$الشارع ضيّق جدًا لإنهاء الدوران في ثلاث حركات. ماذا تفعل؟$pg$,
 $pg$["تضيف حركات أخرى مع المراقبة في كل مرة", "تصعد على الرصيف لكسب مساحة", "تسرّع لتدير المقود أسرع"]$pg$::jsonb,
 $pg$يعتمد عدد الحركات على المساحة المتاحة. إضافة حركة أمر طبيعي إذا أبقت السيارة بعيدة عن العوائق وعن مستخدمي الطريق.$pg$),
('c1d1c1e1-8000-4000-8000-000000000045','en',
 $pg$You enter a parking bay at an angle and still have room to correct. What is the best choice?$pg$,
 $pg$["Finish quickly and hope you are inside the lines", "Stop, reposition and start again with fresh checks", "Look only at the car on the left"]$pg$::jsonb,
 $pg$A slow correction is better than a forced path. Every change of direction starts with a stop and a new look around.$pg$),
('c1d1c1e1-8000-4000-8000-000000000045','ar',
 $pg$تدخل خانة ركن بشكل مائل وما زالت لديك مساحة للتصحيح. ما أفضل خيار؟$pg$,
 $pg$["تنهي بسرعة وتأمل أن تكون داخل الخطوط", "تتوقّف وتعيد التموضع وتبدأ بعد مراقبة جديدة", "تنظر إلى السيارة اليسرى فقط"]$pg$::jsonb,
 $pg$التصحيح البطيء أفضل من فرض مسار سيئ. كل تغيير للاتجاه يبدأ بالتوقّف وبنظرة جديدة حول السيارة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000046','en',
 $pg$You saw a child near the car, then lost sight of them during the manoeuvre. What do you do?$pg$,
 $pg$["Carry on at walking pace", "Rely on the sensors", "Stop until you know exactly where the child is"]$pg$::jsonb,
 $pg$Losing sight of a vulnerable road user means losing certainty that the area is clear. The car stays still until their position is known.$pg$),
('c1d1c1e1-8000-4000-8000-000000000046','ar',
 $pg$رأيت طفلًا قرب السيارة ثم غاب عن نظرك أثناء المناورة. ماذا تفعل؟$pg$,
 $pg$["تتابع بسرعة المشي", "تعتمد على الحساسات", "تتوقّف حتى تعرف مكان الطفل بدقة"]$pg$::jsonb,
 $pg$غياب مستخدم ضعيف عن نظرك يعني أنك لم تعد متأكدًا من خلو المنطقة. تبقى السيارة ثابتة حتى تعرف موقعه.$pg$),

('c1d1c1e1-8000-4000-8000-000000000051','en',
 $pg$The space looks barely longer than your car. Which choice shows the most independence?$pg$,
 $pg$["Find a space with enough room", "Try anyway to prove your skill", "Wait for someone to guide you"]$pg$::jsonb,
 $pg$Being independent also means rejecting a weak solution. Room in front and behind lets you manoeuvre without touching other vehicles.$pg$),
('c1d1c1e1-8000-4000-8000-000000000051','ar',
 $pg$تبدو المساحة أطول بقليل فقط من سيارتك. أي خيار يُظهر أكبر قدر من الاستقلالية؟$pg$,
 $pg$["تبحث عن مكان فيه مساحة كافية", "تحاول رغم ذلك لإثبات مهارتك", "تنتظر من يوجّهك"]$pg$::jsonb,
 $pg$الاستقلالية تعني أيضًا رفض حل غير مضمون. وجود مساحة أمام السيارة وخلفها يسمح بالمناورة دون لمس المركبات الأخرى.$pg$),
('c1d1c1e1-8000-4000-8000-000000000052','en',
 $pg$You are asked to park as soon as possible. Who chooses the space and prepares the manoeuvre?$pg$,
 $pg$["The car behind you", "You, after checking that the space is allowed and suitable", "Your passenger, one move at a time"]$pg$::jsonb,
 $pg$A general instruction leaves the decision to you. Read the signs, assess the space, then signal your intention before slowing down.$pg$),
('c1d1c1e1-8000-4000-8000-000000000052','ar',
 $pg$يُطلب منك الركن عندما يصبح ذلك ممكنًا. من يختار المكان ويحضّر المناورة؟$pg$,
 $pg$["السيارة خلفك", "أنت، بعد التأكد من أن المكان مسموح ومناسب", "الراكب معك، حركة بعد حركة"]$pg$::jsonb,
 $pg$تترك لك التعليمات العامة القرار. تقرأ الإشارات وتقيّم المساحة ثم تعلن نيتك قبل التباطؤ.$pg$),
('c1d1c1e1-8000-4000-8000-000000000053','en',
 $pg$Your car is parked but badly aligned, and a safe correction is still possible. What do you do?$pg$,
 $pg$["Leave it to avoid showing your mistake", "Ask someone to turn the wheel for you", "Check around, then correct slowly"]$pg$::jsonb,
 $pg$Spotting poor alignment and correcting it is part of independence. The new movement needs the same checks as the first one.$pg$),
('c1d1c1e1-8000-4000-8000-000000000053','ar',
 $pg$ركنت السيارة لكنها غير مستقيمة وما زال التصحيح ممكنًا بأمان. ماذا تفعل؟$pg$,
 $pg$["تتركها حتى لا تُظهر خطأك", "تطلب من شخص آخر إدارة المقود", "تراقب حولك ثم تصحّح ببطء"]$pg$::jsonb,
 $pg$اكتشاف عدم الاستقامة وتصحيحه جزء من الاستقلالية. وتحتاج الحركة الجديدة إلى المراقبة نفسها التي احتاجتها الحركة الأولى.$pg$),
('c1d1c1e1-8000-4000-8000-000000000054','en',
 $pg$Another vehicle arrives while you are deciding how to correct. What do you do?$pg$,
 $pg$["Stay still, let it pass, then assess the situation again", "Start quickly before it gets closer", "Signal for it to go around you"]$pg$::jsonb,
 $pg$A changing situation requires a new decision. Letting it pass clears the space and stops you following a plan that has become unsafe.$pg$),
('c1d1c1e1-8000-4000-8000-000000000054','ar',
 $pg$تصل مركبة أخرى وأنت تقرر طريقة التصحيح. ماذا تفعل؟$pg$,
 $pg$["تبقى ثابتًا وتتركها تمر ثم تعيد تقييم الوضع", "تبدأ بسرعة قبل أن تقترب", "تطلب منها بالإشارة أن تتجاوزك"]$pg$::jsonb,
 $pg$تغيّر الوضع يحتاج إلى قرار جديد. تركها تمر يحرر المساحة ويمنعك من متابعة خطة أصبحت خطرة.$pg$),
('c1d1c1e1-8000-4000-8000-000000000055','en',
 $pg$You have just passed the entrance where you wanted to manoeuvre. What is the independent choice?$pg$,
 $pg$["Reverse immediately on the road", "Carry on and find a safe place to come back", "Stop in the middle of the lane"]$pg$::jsonb,
 $pg$Missing an entrance is not dangerous. An improvised reverse can be, so carry on calmly and build a safe route back.$pg$),
('c1d1c1e1-8000-4000-8000-000000000055','ar',
 $pg$تجاوزت للتو المدخل الذي أردت المناورة عنده. ما القرار المستقل؟$pg$,
 $pg$["ترجع فورًا على الطريق", "تتابع وتبحث عن مكان آمن للعودة", "تتوقّف في وسط المسار"]$pg$::jsonb,
 $pg$تجاوز المدخل ليس خطرًا. أما الرجوع المفاجئ فقد يكون خطرًا، لذا تتابع بهدوء وتبني طريق عودة آمنًا.$pg$),
('c1d1c1e1-8000-4000-8000-000000000056','en',
 $pg$You think you have finished the manoeuvre. What final action confirms that you can leave the controls?$pg$,
 $pg$["Switch off while the car is still moving", "Open the door to check the lines", "Stop the car, secure it, then check that it obstructs nobody"]$pg$::jsonb,
 $pg$A manoeuvre ends with a stable, correctly placed car. Securing it prevents any unexpected movement after you release the pedals.$pg$),
('c1d1c1e1-8000-4000-8000-000000000056','ar',
 $pg$تعتقد أنك أنهيت المناورة. ما آخر إجراء يؤكد أنك تستطيع ترك أدوات التحكم؟$pg$,
 $pg$["تطفئ المحرك والسيارة لا تزال تتحرّك", "تفتح الباب لفحص الخطوط", "توقف السيارة وتؤمّنها ثم تتأكد من أنها لا تعيق أحدًا"]$pg$::jsonb,
 $pg$تنتهي المناورة بسيارة ثابتة وفي مكان صحيح. تأمينها يمنع أي حركة مفاجئة بعد ترك الدواسات.$pg$)
on conflict (question_id, lang) do nothing;
