-- ═══════════════════════════════════════════════════════════════
-- 1. Rater puis retenter ne doit pas rejouer le même quiz.
--
-- Il n'y avait que 6 questions de certification par compétence, et le quiz
-- en tire 5 : un élève qui rate et clique « Relire la fiche et retenter »
-- retombait sur cinq des six mêmes. Au deuxième essai il ne réapprenait pas
-- le geste, il se souvenait de la case (audit du 01/08/2026).
--
-- 18 questions de plus sur les trois compétences que tout le monde traverse
-- en premier, et qui sont aussi les seules ouvertes au compte gratuit :
-- C1a, C1b, C1c passent de 6 à 12 ou 13. Elles valent pour les deux boîtes
-- (colonne `boite` à NULL).
--
-- Reste à faire : les 28 autres compétences.
--
-- 2. Les tirets longs oubliés en base.
--
-- Le balayage du 31/07 (« zéro tiret ») n'a nettoyé que le dépôt. La banque
-- de questions vit en base : 9 questions et 22 traductions portaient encore
-- un « — ». La base est une surface publique de plus, au même titre que les
-- pages hors `src/`.
-- ═══════════════════════════════════════════════════════════════

insert into public.questions_competence (id, competence_id, question, options, correct_index, explanation, difficulty, type, boite) values
('c1a70000-0000-4000-8000-000000000001','C1a',$pg$Tu roules de nuit en pleins phares et une voiture arrive en face. Ton geste ?$pg$,$pg$["Tu passes en feux de croisement", "Tu gardes les pleins phares", "Tu éteins tout"]$pg$::jsonb,0,$pg$Les pleins phares éblouissent celui d'en face pendant plusieurs secondes. On repasse en croisement dès qu'on voit arriver quelqu'un, devant ou derrière.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000002','C1a',$pg$Le témoin de température du moteur passe au rouge. Tu fais quoi ?$pg$,$pg$["Tu t'arrêtes dès que c'est sûr et tu coupes le moteur", "Tu continues, ça va redescendre", "Tu ouvres le capot tout de suite"]$pg$::jsonb,0,$pg$Rouge, c'est arrêt. Un moteur qui chauffe peut se détruire en quelques minutes. Et on n'ouvre jamais un bouchon de circuit brûlant.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000003','C1a',$pg$À quoi servent les feux de détresse ?$pg$,$pg$["À signaler un danger ou un arrêt imprévu", "À se garer où on veut", "À rouler dans le brouillard"]$pg$::jsonb,0,$pg$Ils préviennent les autres d'un danger : bouchon soudain, panne, arrêt d'urgence. Ils n'autorisent aucun stationnement.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000004','C1a',$pg$L'aiguille de carburant touche la réserve. Il te reste quoi, en gros ?$pg$,$pg$["De quoi rouler encore quelques dizaines de kilomètres", "Rien, la voiture va s'arrêter", "La moitié du réservoir"]$pg$::jsonb,0,$pg$La réserve laisse de la marge, souvent une cinquantaine de kilomètres. Ce n'est pas une raison pour attendre : rouler à sec abîme la pompe.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000005','C1a',$pg$Ta lunette arrière est couverte de buée. Quelle commande ?$pg$,$pg$["Le dégivrage arrière, le bouton au rectangle traversé de vagues", "Les essuie-glaces avant", "Le klaxon"]$pg$::jsonb,0,$pg$Ce bouton chauffe la vitre arrière. Partir avec une lunette opaque, c'est conduire sans rétroviseur intérieur.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000006','C1a',$pg$Ta portière n'est pas bien claquée. Comment tu le sais avant de partir ?$pg$,$pg$["Un témoin de porte s'allume au tableau de bord", "La voiture refuse de démarrer", "Rien ne le montre"]$pg$::jsonb,0,$pg$Une petite voiture aux portes ouvertes s'allume au tableau de bord. On reclaque à l'arrêt, jamais en roulant.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000011','C1b',$pg$Tu règles ton appui-tête. Où doit arriver son bord haut ?$pg$,$pg$["Au niveau du haut de ton crâne", "Au niveau de ta nuque", "Le plus bas possible"]$pg$::jsonb,0,$pg$Un appui-tête trop bas fait levier sur la nuque en cas de choc arrière. Son haut se règle à la hauteur du sommet du crâne.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000012','C1b',$pg$Ta ceinture passe où, sur le haut du corps ?$pg$,$pg$["Au milieu de l'épaule, jamais sur le cou", "Sous le bras", "Tout au bord de l'épaule"]$pg$::jsonb,0,$pg$Au milieu de l'épaule, et à plat sur le bassin. Sous le bras ou sur le cou, elle blesse au lieu de retenir.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000013','C1b',$pg$Tu règles le rétroviseur intérieur. Tu dois voir quoi dedans ?$pg$,$pg$["Toute la lunette arrière, sans bouger la tête", "Ton visage", "Le côté droit de la voiture"]$pg$::jsonb,0,$pg$Toute la lunette arrière, la tête droite. Si tu dois te pencher pour voir, il est mal réglé.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000014','C1b',$pg$Dans un rétroviseur extérieur, combien de ta carrosserie dois-tu voir ?$pg$,$pg$["Un petit bout, juste pour te situer", "La moitié du miroir", "Rien du tout"]$pg$::jsonb,0,$pg$Un petit bout seulement, comme repère. Trop de carrosserie et tu regardes ta voiture au lieu de la route.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000015','C1b',$pg$Dans quel ordre tu règles ton poste de conduite ?$pg$,$pg$["Siège, appui-tête, volant, puis rétroviseurs", "Les rétroviseurs d'abord", "Le volant puis le siège"]$pg$::jsonb,0,$pg$Chaque réglage déplace le suivant. Un rétroviseur réglé avant le siège est à refaire dès que tu bouges.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000016','C1b',$pg$Tu es bien installé au volant. Tes bras sont comment ?$pg$,$pg$["Légèrement pliés, poignets qui atteignent le haut du volant", "Tendus", "Très repliés, coudes au corps"]$pg$::jsonb,0,$pg$Bras tendus, tu ne peux plus tourner vite ni garder les épaules au dossier. Poignets sur le haut du volant, épaules collées : c'est la bonne distance.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000021','C1c',$pg$Où sont tes mains sur le volant ?$pg$,$pg$["En haut, de part et d'autre", "En bas, réunies", "Une seule main tout en haut"]$pg$::jsonb,0,$pg$Les deux mains en haut, de chaque côté. C'est de là que tu peux tourner le plus vite sans jamais lâcher.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000022','C1c',$pg$Tu tournes dans une rue à angle droit. Comment passent tes mains ?$pg$,$pg$["Tu tires d'une main et tu laisses glisser l'autre", "Tu croises les bras", "Tu lâches le volant et tu le rattrapes"]$pg$::jsonb,0,$pg$Tirer et pousser, sans croiser les bras. Si l'airbag part, des bras croisés viennent te frapper le visage.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000023','C1c',$pg$Ta voiture serre trop à droite dans un virage. Où regardes-tu ?$pg$,$pg$["Loin, vers la sortie du virage", "Le bord droit de la route", "Le capot"]$pg$::jsonb,0,$pg$La voiture va là où tu regardes. Fixer le bord droit, c'est aller vers le bord droit. Vise la sortie.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000024','C1c',$pg$Une voiture est garée à droite sur une route étroite. Ta trajectoire ?$pg$,$pg$["Tu t'écartes tôt et progressivement", "Tu déboîtes au dernier moment", "Tu klaxonnes et tu passes"]$pg$::jsonb,0,$pg$On s'écarte tôt et doucement : les autres comprennent ce que tu fais, et tu gardes de la marge si une portière s'ouvre.$pg$,2,'post_validation',null),
('c1a70000-0000-4000-8000-000000000025','C1c',$pg$Tu roules dans ta voie. Où doit se trouver ta voiture ?$pg$,$pg$["Au milieu de sa voie", "Collée à la ligne du milieu", "Contre le bord droit"]$pg$::jsonb,0,$pg$Au milieu de ta voie. Trop à gauche tu inquiètes celui d'en face, trop à droite tu frôles les obstacles et les piétons.$pg$,1,'post_validation',null),
('c1a70000-0000-4000-8000-000000000026','C1c',$pg$En sortie de virage, le volant revient tout seul. Tu fais quoi ?$pg$,$pg$["Tu accompagnes le retour, mains posées dessus", "Tu le lâches complètement", "Tu forces dans l'autre sens"]$pg$::jsonb,0,$pg$On accompagne, mains posées. Un volant lâché peut s'arrêter de travers et la voiture repart en biais.$pg$,3,'post_validation',null)
on conflict (id) do nothing;

insert into public.question_translations (question_id, lang, question, options, explanation) values
('c1a70000-0000-4000-8000-000000000001','en',$pg$You're driving at night on full beam and a car comes towards you. What do you do?$pg$,$pg$["Switch to dipped headlights", "Keep the full beam on", "Turn everything off"]$pg$::jsonb,$pg$Full beam dazzles the oncoming driver for several seconds. You dip as soon as you see someone coming, ahead or behind.$pg$),
('c1a70000-0000-4000-8000-000000000001','ar',$pg$تقود ليلًا بالأضواء العالية وتأتي سيارة في الاتجاه المعاكس. ماذا تفعل؟$pg$,$pg$["تنتقل إلى الأضواء المنخفضة", "تبقي الأضواء العالية", "تطفئ كل شيء"]$pg$::jsonb,$pg$الأضواء العالية تُعمي السائق المقابل عدة ثوانٍ. تخفضها بمجرد أن ترى أحدًا قادمًا، أمامك أو خلفك.$pg$),
('c1a70000-0000-4000-8000-000000000002','en',$pg$The engine temperature warning light turns red. What do you do?$pg$,$pg$["Stop as soon as it's safe and switch the engine off", "Carry on, it will come back down", "Open the bonnet straight away"]$pg$::jsonb,$pg$Red means stop. An overheating engine can destroy itself in minutes. And you never open a cap on a boiling hot circuit.$pg$),
('c1a70000-0000-4000-8000-000000000002','ar',$pg$يتحوّل مؤشّر حرارة المحرك إلى الأحمر. ماذا تفعل؟$pg$,$pg$["تتوقّف حالما يكون ذلك آمنًا وتُطفئ المحرك", "تتابع، ستنخفض الحرارة", "تفتح غطاء المحرك فورًا"]$pg$::jsonb,$pg$الأحمر يعني التوقّف. المحرك الذي يسخن قد يتلف خلال دقائق. ولا تفتح أبدًا سدادة دارة ساخنة.$pg$),
('c1a70000-0000-4000-8000-000000000003','en',$pg$What are hazard lights for?$pg$,$pg$["Warning others of a danger or an unexpected stop", "Parking wherever you like", "Driving in fog"]$pg$::jsonb,$pg$They warn others of a danger: a sudden queue, a breakdown, an emergency stop. They never allow you to park.$pg$),
('c1a70000-0000-4000-8000-000000000003','ar',$pg$ما فائدة أضواء الخطر؟$pg$,$pg$["تحذير الآخرين من خطر أو توقّف مفاجئ", "الركن حيث تشاء", "القيادة في الضباب"]$pg$::jsonb,$pg$تحذّر الآخرين من خطر: ازدحام مفاجئ أو عطل أو توقّف اضطراري. وهي لا تسمح بالركن أبدًا.$pg$),
('c1a70000-0000-4000-8000-000000000004','en',$pg$The fuel needle reaches the reserve. Roughly how much is left?$pg$,$pg$["Enough for a few dozen more kilometres", "Nothing, the car is about to stop", "Half a tank"]$pg$::jsonb,$pg$The reserve leaves you a margin, often around fifty kilometres. That's no reason to wait: running dry damages the pump.$pg$),
('c1a70000-0000-4000-8000-000000000004','ar',$pg$يصل مؤشّر الوقود إلى الاحتياطي. كم بقي لك تقريبًا؟$pg$,$pg$["ما يكفي لعشرات الكيلومترات", "لا شيء، ستتوقّف السيارة", "نصف الخزان"]$pg$::jsonb,$pg$يترك الاحتياطي هامشًا، غالبًا نحو خمسين كيلومترًا. لكن هذا ليس سببًا للانتظار: السير حتى الجفاف يُتلف المضخّة.$pg$),
('c1a70000-0000-4000-8000-000000000005','en',$pg$Your rear window is covered in condensation. Which control?$pg$,$pg$["The rear demister, the button with wavy lines through a rectangle", "The front wipers", "The horn"]$pg$::jsonb,$pg$That button heats the rear glass. Setting off with an opaque rear window means driving without an interior mirror.$pg$),
('c1a70000-0000-4000-8000-000000000005','ar',$pg$نافذتك الخلفية مغطّاة بالبخار. أي زرّ تستعمل؟$pg$,$pg$["مزيل الضباب الخلفي، الزرّ ذو المستطيل والخطوط المتموّجة", "الماسحات الأمامية", "المنبّه"]$pg$::jsonb,$pg$هذا الزرّ يسخّن الزجاج الخلفي. الانطلاق بنافذة خلفية معتمة يعني القيادة بلا مرآة داخلية.$pg$),
('c1a70000-0000-4000-8000-000000000006','en',$pg$Your door isn't properly shut. How do you know before setting off?$pg$,$pg$["A door warning light comes on the dashboard", "The car refuses to start", "Nothing shows it"]$pg$::jsonb,$pg$A small car with open doors lights up on the dashboard. You shut it again while stopped, never while driving.$pg$),
('c1a70000-0000-4000-8000-000000000006','ar',$pg$بابك ليس مغلقًا جيدًا. كيف تعرف ذلك قبل الانطلاق؟$pg$,$pg$["يضيء مؤشّر الأبواب على لوحة القيادة", "ترفض السيارة أن تعمل", "لا شيء يدلّ على ذلك"]$pg$::jsonb,$pg$تضيء على لوحة القيادة صورة سيارة صغيرة بأبواب مفتوحة. تُغلقه وأنت متوقّف، لا أثناء السير.$pg$),
('c1a70000-0000-4000-8000-000000000011','en',$pg$You're adjusting your head restraint. Where should its top edge sit?$pg$,$pg$["Level with the top of your skull", "Level with your neck", "As low as possible"]$pg$::jsonb,$pg$A head restraint set too low levers your neck in a rear impact. Its top goes level with the top of your head.$pg$),
('c1a70000-0000-4000-8000-000000000011','ar',$pg$تضبط مسند الرأس. أين يجب أن تكون حافته العليا؟$pg$,$pg$["بمستوى أعلى رأسك", "بمستوى رقبتك", "في أدنى وضع ممكن"]$pg$::jsonb,$pg$مسند الرأس المنخفض جدًا يضغط على الرقبة عند صدمة خلفية. تُضبط حافته العليا بمستوى قمّة الرأس.$pg$),
('c1a70000-0000-4000-8000-000000000012','en',$pg$Where does the seatbelt cross your upper body?$pg$,$pg$["Across the middle of the shoulder, never on the neck", "Under the arm", "Right on the edge of the shoulder"]$pg$::jsonb,$pg$Across the middle of the shoulder, and flat across the hips. Under the arm or on the neck, it injures instead of holding you.$pg$),
('c1a70000-0000-4000-8000-000000000012','ar',$pg$أين يمرّ حزام الأمان على الجزء العلوي من جسمك؟$pg$,$pg$["في منتصف الكتف، لا على الرقبة أبدًا", "تحت الذراع", "على طرف الكتف تمامًا"]$pg$::jsonb,$pg$في منتصف الكتف، ومسطّحًا على الحوض. تحت الذراع أو على الرقبة يجرحك بدل أن يحميك.$pg$),
('c1a70000-0000-4000-8000-000000000013','en',$pg$You're setting the interior mirror. What should you see in it?$pg$,$pg$["The whole rear window, without moving your head", "Your face", "The right-hand side of the car"]$pg$::jsonb,$pg$The whole rear window, with your head straight. If you have to lean to see, it's badly set.$pg$),
('c1a70000-0000-4000-8000-000000000013','ar',$pg$تضبط المرآة الداخلية. ماذا يجب أن ترى فيها؟$pg$,$pg$["كامل النافذة الخلفية دون تحريك رأسك", "وجهك", "الجانب الأيمن من السيارة"]$pg$::jsonb,$pg$كامل النافذة الخلفية ورأسك مستقيم. إذا اضطررت للانحناء لترى، فهي مضبوطة بشكل خاطئ.$pg$),
('c1a70000-0000-4000-8000-000000000014','en',$pg$In a door mirror, how much of your own bodywork should you see?$pg$,$pg$["A small sliver, just to place yourself", "Half the mirror", "None at all"]$pg$::jsonb,$pg$Just a sliver, as a landmark. Too much bodywork and you're looking at your car instead of the road.$pg$),
('c1a70000-0000-4000-8000-000000000014','ar',$pg$في المرآة الجانبية، كم يجب أن ترى من هيكل سيارتك؟$pg$,$pg$["جزءًا صغيرًا فقط لتحديد موقعك", "نصف المرآة", "لا شيء إطلاقًا"]$pg$::jsonb,$pg$جزء صغير فقط كعلامة. إذا رأيت الكثير من الهيكل فأنت تنظر إلى سيارتك بدل الطريق.$pg$),
('c1a70000-0000-4000-8000-000000000015','en',$pg$In what order do you set up your driving position?$pg$,$pg$["Seat, head restraint, steering wheel, then mirrors", "Mirrors first", "Steering wheel then seat"]$pg$::jsonb,$pg$Each adjustment moves the next one. A mirror set before the seat has to be done again as soon as you move.$pg$),
('c1a70000-0000-4000-8000-000000000015','ar',$pg$بأي ترتيب تضبط وضعية القيادة؟$pg$,$pg$["المقعد، مسند الرأس، المقود، ثم المرايا", "المرايا أولًا", "المقود ثم المقعد"]$pg$::jsonb,$pg$كل ضبط يُزيح الذي بعده. المرآة المضبوطة قبل المقعد يجب إعادة ضبطها بمجرد أن تتحرّك.$pg$),
('c1a70000-0000-4000-8000-000000000016','en',$pg$You're properly seated at the wheel. How are your arms?$pg$,$pg$["Slightly bent, wrists reaching the top of the wheel", "Straight", "Very folded, elbows against your body"]$pg$::jsonb,$pg$With straight arms you can no longer steer quickly or keep your shoulders on the seat. Wrists on the top of the wheel, shoulders back: that's the right distance.$pg$),
('c1a70000-0000-4000-8000-000000000016','ar',$pg$أنت جالس جيدًا خلف المقود. كيف تكون ذراعاك؟$pg$,$pg$["مثنيتان قليلًا، ورسغاك يصلان أعلى المقود", "ممدودتان", "مثنيتان كثيرًا والمرفقان ملتصقان بالجسم"]$pg$::jsonb,$pg$بذراعين ممدودتين لا تستطيع الدوران بسرعة ولا إبقاء كتفيك على المسند. الرسغان على أعلى المقود والكتفان إلى الخلف: هذه هي المسافة الصحيحة.$pg$),
('c1a70000-0000-4000-8000-000000000021','en',$pg$Where are your hands on the steering wheel?$pg$,$pg$["High up, one on each side", "Low down, together", "One hand at the very top"]$pg$::jsonb,$pg$Both hands high, one each side. From there you can steer fastest without ever letting go.$pg$),
('c1a70000-0000-4000-8000-000000000021','ar',$pg$أين تضع يديك على المقود؟$pg$,$pg$["في الأعلى، واحدة على كل جانب", "في الأسفل، متجاورتين", "يد واحدة في الأعلى تمامًا"]$pg$::jsonb,$pg$كلتا اليدين في الأعلى، واحدة على كل جانب. من هناك تدير أسرع دون أن تترك المقود أبدًا.$pg$),
('c1a70000-0000-4000-8000-000000000022','en',$pg$You're turning into a right-angle street. How do your hands move?$pg$,$pg$["You pull with one hand and let the other slide", "You cross your arms", "You let go and catch the wheel again"]$pg$::jsonb,$pg$Pull and push, without crossing your arms. If the airbag goes off, crossed arms are thrown into your face.$pg$),
('c1a70000-0000-4000-8000-000000000022','ar',$pg$تنعطف في شارع بزاوية قائمة. كيف تتحرّك يداك؟$pg$,$pg$["تسحب بيد وتترك الأخرى تنزلق", "تتقاطع ذراعاك", "تترك المقود ثم تُمسكه من جديد"]$pg$::jsonb,$pg$سحب ودفع دون تقاطع الذراعين. إذا انفجرت الوسادة الهوائية، ارتدّت الذراعان المتقاطعتان إلى وجهك.$pg$),
('c1a70000-0000-4000-8000-000000000023','en',$pg$Your car is running wide to the right in a bend. Where do you look?$pg$,$pg$["Far ahead, towards the exit of the bend", "At the right-hand edge of the road", "At the bonnet"]$pg$::jsonb,$pg$The car goes where you look. Staring at the right-hand edge takes you to the right-hand edge. Aim for the exit.$pg$),
('c1a70000-0000-4000-8000-000000000023','ar',$pg$سيارتك تقترب كثيرًا من اليمين في المنعطف. إلى أين تنظر؟$pg$,$pg$["بعيدًا، نحو مخرج المنعطف", "إلى حافة الطريق اليمنى", "إلى غطاء المحرك"]$pg$::jsonb,$pg$السيارة تذهب حيث تنظر. التحديق في الحافة اليمنى يأخذك إلى الحافة اليمنى. اِستهدف المخرج.$pg$),
('c1a70000-0000-4000-8000-000000000024','en',$pg$A car is parked on the right on a narrow road. Your line?$pg$,$pg$["You move out early and gradually", "You pull out at the last moment", "You honk and go through"]$pg$::jsonb,$pg$You move out early and gently: others understand what you're doing, and you keep a margin if a door opens.$pg$),
('c1a70000-0000-4000-8000-000000000024','ar',$pg$سيارة مركونة على اليمين في طريق ضيّق. ما مسارك؟$pg$,$pg$["تبتعد مبكرًا وتدريجيًا", "تنحرف في اللحظة الأخيرة", "تُطلق المنبّه وتمرّ"]$pg$::jsonb,$pg$تبتعد مبكرًا وبهدوء: يفهم الآخرون ما تفعله، وتحتفظ بهامش إذا انفتح باب.$pg$),
('c1a70000-0000-4000-8000-000000000025','en',$pg$You're driving in your lane. Where should your car be?$pg$,$pg$["In the middle of its lane", "Hugging the centre line", "Against the right-hand edge"]$pg$::jsonb,$pg$In the middle of your lane. Too far left you worry the oncoming driver, too far right you brush obstacles and pedestrians.$pg$),
('c1a70000-0000-4000-8000-000000000025','ar',$pg$أنت تسير في مسارك. أين يجب أن تكون سيارتك؟$pg$,$pg$["في منتصف مسارها", "ملاصقة للخطّ الأوسط", "ملاصقة للحافة اليمنى"]$pg$::jsonb,$pg$في منتصف مسارك. إلى اليسار كثيرًا تُقلق القادم في الاتجاه المعاكس، وإلى اليمين كثيرًا تلامس العوائق والمشاة.$pg$),
('c1a70000-0000-4000-8000-000000000026','en',$pg$Coming out of a bend, the wheel returns by itself. What do you do?$pg$,$pg$["You guide it back with your hands resting on it", "You let go completely", "You force it the other way"]$pg$::jsonb,$pg$You guide it, hands resting on it. A wheel let go can stop crooked and the car sets off at an angle.$pg$),
('c1a70000-0000-4000-8000-000000000026','ar',$pg$عند الخروج من المنعطف يعود المقود وحده. ماذا تفعل؟$pg$,$pg$["ترافق عودته ويداك موضوعتان عليه", "تتركه تمامًا", "تديره بقوة في الاتجاه الآخر"]$pg$::jsonb,$pg$ترافقه ويداك عليه. المقود المتروك قد يتوقّف مائلًا فتنطلق السيارة منحرفة.$pg$)
on conflict (question_id, lang) do nothing;

-- ── Les tirets longs de la banque de questions ────────────────────
-- Français réécrit à la main (une incise se coupe dans la langue, pas
-- mécaniquement), traductions ramenées à la virgule.
update public.questions_competence set explanation = replace(explanation, ' — et jamais', '. Et jamais') where id='142e097a-2ec2-415c-8dc7-7798b87f7238';
update public.questions_competence set explanation = replace(explanation, ' — les yeux seuls', '. Les yeux seuls') where id='ca4bd680-d6fe-48f8-9534-d6f24fc2ad1b';
update public.questions_competence set explanation = replace(explanation, ' — jamais tout ou rien', ', jamais tout ou rien') where id='ddbd9068-e4fa-4435-b8a1-fb7cb7770b3b';
update public.questions_competence set explanation = replace(explanation, ' — ceux qui en sortent', '. Ceux qui en sortent') where id='0aad5f09-384f-4484-bbcc-c2bc48870612';
update public.questions_competence set explanation = replace(explanation, ' — il t''en voudra', '. Il t''en voudra') where id='feb299c0-5d8d-4cc9-af66-ec5f9d8648a0';
update public.questions_competence set explanation = replace(explanation, ' — et moins il boit', ', et moins il boit') where id='790e45bf-5409-4523-b902-a246f993645b';
update public.questions_competence set explanation = replace(explanation, ' — tu étais déjà prêt', ', tu étais déjà prêt') where id='b6958820-6684-4879-b8bd-e748ffed0956';
update public.questions_competence
set explanation = $pg$Le klaxon n'est pas banni. Il sert à prévenir d'un danger immédiat, et à rien d'autre.$pg$
where id = 'd5e744e0-271f-4462-adcb-bbf2ad5fc2a1';

update public.questions_competence set
  question = replace(question, ' — ', ', '),
  explanation = replace(explanation, ' — ', ', '),
  options = replace(options::text, ' — ', ', ')::jsonb
where question like '%—%' or explanation like '%—%' or options::text like '%—%';

update public.question_translations set
  question = replace(question, ' — ', case when lang='ar' then '، ' else ', ' end),
  explanation = replace(explanation, ' — ', case when lang='ar' then '، ' else ', ' end),
  options = replace(options::text, ' — ', case when lang='ar' then '، ' else ', ' end)::jsonb
where question like '%—%' or explanation like '%—%' or options::text like '%—%';
